<?php /** One component row of the bundle editor (`bundle-row-{n}`): the variant picker (single products only), the quantity, remove, the sets this component gives. Data: n, variantId, label, qty, sets */
$n = (string) $n;
?>
<div class="row g-2 align-items-end mb-2 bundle-row" id="bundle-row-<?= e($n) ?>">
    <div class="col-12 col-md-7"><label class="form-label fs-12 text-muted" for="bundle-row-<?= e($n) ?>-variant-open">Component variant</label><?= $n === '__N__' ? '<div class="input-group record-picker-field" id="bundle-row-__N__-variant-picker" data-picker-source="variant" data-picker-title="Variants" data-picker-placeholder="Choose a variant" data-picker-search="Search by SKU or product…" data-picker-params=\'{"single":1}\'><input type="hidden" name="components[__N__][variant]" id="bundle-row-__N__-variant" value="" data-picker-value /><button type="button" class="form-control text-start record-picker-open" id="bundle-row-__N__-variant-open" aria-haspopup="dialog" aria-controls="record-picker"><span class="record-picker-label text-muted">Choose a variant</span></button><button type="button" class="btn btn-light-brand record-picker-search-btn" id="bundle-row-__N__-variant-search-btn" aria-label="Search"><i class="feather-search"></i></button></div>' : picker_field(['id' => 'bundle-row-' . $n . '-variant', 'name' => 'components[' . $n . '][variant]', 'source' => 'variant', 'value' => $variantId, 'label' => $label, 'required' => true, 'params' => ['single' => 1], 'search' => 'Search by SKU or product…']) ?></div>
    <div class="col-6 col-md-2"><label class="form-label fs-12 text-muted" for="bundle-row-<?= e($n) ?>-qty">Quantity</label><input type="number" min="1" name="components[<?= e($n) ?>][qty]" id="bundle-row-<?= e($n) ?>-qty" class="form-control btn-touch" value="<?= (int) $qty ?>" required></div>
    <div class="col-4 col-md-2 fs-12 text-muted pb-2" id="bundle-row-<?= e($n) ?>-sets"><?= $sets !== null ? (int) $sets['own_available'] . ' available → ' . (int) $sets['sets_from_stock'] . ' sets' : '' ?></div>
    <div class="col-2 col-md-1"><button type="button" class="btn btn-light btn-touch w-100 bundle-row-remove" id="bundle-row-<?= e($n) ?>-remove-btn" aria-label="Remove"><i class="feather-x"></i></button></div>
</div>
