<?php
/** The exports (reports-admin.md "Proof": ≥ 20): the three accounting files and their gate, the catalog and the listings, the 92-day rule, the log, JSON mode. */
require __DIR__ . '/lib.php';
$w = admin_world();
[$nora, $sam, $vera, $owner, $omar] = [who('nora'), who('sam'), who('vera'), who('owner'), who('omar')];
$dl = static function (string $jar, array $f): array { $r = act_raw($jar, '/exports/download.php', $f); return [(int) $r['code'], $r]; };
$csv = static function (string $body): array { $rows = []; $h = fopen('php://memory', 'w+'); fwrite($h, substr($body, str_starts_with($body, "\xEF\xBB\xBF") ? 3 : 0)); rewind($h); while (($r = fgetcsv($h, 0, ',', '"', '')) !== false) { $rows[] = $r; } return $rows; };
$mo = gmdate('Y-m-01'); $today = gmdate('Y-m-d'); $end = gmdate('Y-m-d', strtotime('+1 day'));

echo "1. Sales closed\n";
[$c, $r] = $dl($owner, ['export' => 'sales_closed', 'format' => 'csv', 'from' => $mo, 'to' => $end]);
$t = $csv($r['body']);
$head = array_flip($t[0]);
$so2 = (string) one('SELECT number FROM sales_orders WHERE id = :o', ['o' => $w['so2']]);
$lines = array_values(array_filter(array_slice($t, 1), static fn (array $x): bool => $x[0] === $so2));
$nLines = (int) one("SELECT count(*) FROM sales_order_lines WHERE sales_order_id = :o AND status <> 'cancelled'", ['o' => $w['so2']]);
ok($c === 200 && count($lines) === $nLines && $nLines >= 1 && str_starts_with($r['body'], "\xEF\xBB\xBF"), "the CSV has one row per line of $so2 ($nLines)");
$cogs = (float) one("SELECT sum(l.qty * COALESCE(l.offer_cost, v.cost_price, 0)) FROM sales_order_lines l JOIN product_variants v ON v.id = l.variant_id WHERE l.sales_order_id = :o AND l.status <> 'cancelled'", ['o' => $w['so2']]);
ok(abs((float) $lines[0][$head['COGS']] - $cogs) < 0.005 && $lines[0][$head['Paid by transfer']] !== '' && (float) $lines[0][$head['Paid by transfer']] > 0 && $lines[0][$head['Balance due']] === '0.00', 'with its COGS (' . $lines[0][$head['COGS']] . '), the payments by method (a column per method seen: Paid by transfer) and the balance');
[$c, $j] = $dl($owner, ['export' => 'sales_closed', 'format' => 'json', 'from' => $mo, 'to' => $end]);
$doc = json_decode($j['body'], true);
$direct = json_decode((string) one('SELECT inv_share_sales_closed(CAST(:f AS date), CAST(:t AS date), 0, 500)', ['f' => $mo, 't' => $end]), true);
unset($doc['generated_at'], $direct['generated_at']);
ok($c === 200 && $doc['schema'] === 'os.inventory-sales/1' && $doc['orders'] == $direct['orders'] && $doc['totals'] == $direct['totals'] && str_contains((string) hdr($j, 'Content-Type'), 'application/json'), 'the JSON is the share\'s document (os.inventory-sales/1), orders and totals equal to the function\'s');
ok(str_contains((string) hdr($j, 'Content-Disposition'), 'filename="sales_closed-' . $mo . '-' . $end . '.json"') && hdr($j, 'X-Content-Type-Options') === 'nosniff', 'Content-Disposition names the file; nosniff');
[$c, $r] = $dl($owner, ['export' => 'sales_closed', 'format' => 'csv', 'from' => '2026-01-01', 'to' => '2026-06-01']);
ok($c === 422 && str_contains($r['body'], '92 days'), 'a period of more than 92 days → 422 before the function runs: "at most 92 days"');
[$c, $r] = $dl($owner, ['export' => 'sales_closed', 'format' => 'csv', 'from' => $today]);
ok($c === 422, 'a missing "to" → 422');

echo "2. Purchases received and the valuation\n";
$ps = psql_exec("SELECT count(*) FROM goods_receipts");
[$c, $r] = $dl($owner, ['export' => 'purchases_received', 'format' => 'json', 'from' => $mo, 'to' => $end]);
$pdoc = json_decode($r['body'], true);
ok($c === 200 && $pdoc['schema'] === 'os.inventory-purchases/1' && array_key_exists('suppliers', $pdoc) && !str_contains($r['body'], 'ship_to') && !str_contains($r['body'], '312-555'), 'purchases_received: the share\'s document, with no ship-to and no customer phone');
[$c, $r] = $dl($owner, ['export' => 'purchases_received', 'format' => 'csv', 'from' => $mo, 'to' => $end]);
$t = $csv($r['body']);
ok($c === 200 && $t[0][0] === 'Supplier' && in_array('Kind', $t[0], true) && in_array('Supplier SKU', $t[0], true), 'and as CSV: a row per receipt line and per delivered drop-ship line (' . (count($t) - 1) . ' rows)');
[$c, $r] = $dl($owner, ['export' => 'stock_valuation', 'format' => 'csv', 'as_of' => $today, 'by' => 'brand']);
$t = $csv($r['body']);
$units = (int) array_sum(array_map(static fn (array $x): int => (int) $x[1], array_slice($t, 1, -1)));
ok($c === 200 && $t[0][0] === 'Brand' && end($t)[0] === 'Total' && (int) end($t)[1] === $units && $units > 0, 'stock_valuation as of today by brand: a row per brand and a totals row (' . $units . ' units)');
[$c, $r] = $dl($owner, ['export' => 'stock_valuation', 'format' => 'json', 'as_of' => $today]);
ok($c === 200 && json_decode($r['body'], true)['cost_basis'] !== '' && json_decode($r['body'], true)['by'] === 'location', 'the valuation JSON carries its cost_basis; location by default');

echo "3. The gate\n";
[$c, $r] = $dl($sam, ['export' => 'sales_closed', 'format' => 'csv', 'from' => $mo, 'to' => $end]);
ok($c === 403, 'Sam (no reports.read) exporting sales_closed → 403');
[$c, $r] = $dl($omar, ['export' => 'sales_closed', 'format' => 'csv', 'from' => $mo, 'to' => $end]);
ok($c === 403 && str_contains($r['body'], 'The accounting files carry cost'), 'the analyst (reports.read, no cost wall) → 403 "The accounting files carry cost — the admin or the Buyer exports them."');
[$c1] = $dl($nora, ['export' => 'sales_closed', 'format' => 'csv', 'from' => $mo, 'to' => $end]);
[$c2] = $dl($owner, ['export' => 'purchases_received', 'format' => 'csv', 'from' => $mo, 'to' => $end]);
ok($c1 === 200 && $c2 === 200, 'Nora (reports.read with the cost wall) and the admin (exports.all) → 200');
[$c] = $dl($vera, ['export' => 'catalog', 'format' => 'csv']);
ok($c === 403, 'a Viewer cannot export even the catalog (reports.read)');
[$c, $html] = pg($omar, '/exports/');
ok($c === 200 && has_id($html, 'export-card-sales_closed-withheld') && preg_match('#id="export-card-sales_closed-csv-btn"[^>]*disabled#', $html) === 1 && preg_match('#id="export-card-catalog-csv-btn"[^>]*disabled#', $html) !== 1 && str_contains(text_of($html, 'export-card-sales_closed-withheld'), 'cost withheld'), 'the page below the wall: the three accounting cards disabled with "cost withheld — the admin or the Buyer exports these"; the catalog card live');
[$c, $html] = pg($nora, '/exports/');
ok($c === 200 && has_id($html, 'export-card-listings') && has_id($html, 'export-card-stock_valuation-json-btn') && !has_id($html, 'export-card-sales_closed-withheld'), 'Nora\'s page: five cards, buttons live');

echo "4. The catalog and the listings\n";
[$c, $r] = $dl($nora, ['export' => 'catalog', 'format' => 'csv']);
$t = $csv($r['body']); $h = array_flip($t[0]);
$nVar = (int) one('SELECT count(*) FROM product_variants');
ok($c === 200 && count($t) - 1 === $nVar && $h['Cost'] !== null, 'the catalog CSV: every variant (' . $nVar . ') with its identifiers');
$q = array_values(array_filter($t, static fn (array $x): bool => $x[$h['SKU']] === 'SMOKE-NW-CR-Q'))[0];
ok($q[$h['Cost']] !== '' && $q[$h['GTIN']] !== '' && $q[$h['Size']] === 'Queen', 'Nora\'s row has the cost; the Queen\'s GTIN is there');
[$c, $r] = $dl($omar, ['export' => 'catalog', 'format' => 'csv']);
$t2 = $csv($r['body']);
ok($c === 200 && array_unique(array_column(array_slice($t2, 1), $h['Cost'])) === [''] && count($t2) === count($t), 'the analyst\'s catalog has the same rows and no cost');
[$c, $r] = $dl($nora, ['export' => 'catalog', 'format' => 'json']);
$cj = json_decode($r['body'], true);
ok($c === 200 && $cj['schema'] === 'os.inventory-catalog/1' && $cj['count'] === $nVar && $cj['application'] === 'inventory' && isset($cj['rows'][0]['sku']), 'the catalog JSON: {schema os.inventory-catalog/1, generated_at, application, currency, count, rows}');
[$c, $r] = $dl($nora, ['export' => 'listings', 'format' => 'csv', 'source' => (string) $w['src_malouf']]);
$t = $csv($r['body']); $h = array_flip($t[0]);
$matched = array_values(array_filter(array_slice($t, 1), static fn (array $x): bool => $x[$h['Matched SKU']] !== ''));
ok($c === 200 && count($t) > 1 && array_unique(array_column(array_slice($t, 1), $h['Source'])) === ['SMOKE Malouf store'] && count($matched) >= 1 && $matched[0][$h['Match kind']] !== '', 'the listings of Malouf: one row per listing variant with the matched SKU and the match kind (' . (count($t) - 1) . ' rows)');
[$c, $r] = $dl($omar, ['export' => 'listings', 'format' => 'csv', 'source' => (string) $w['src_malouf']]);
$t3 = $csv($r['body']);
ok($c === 200 && array_unique(array_column(array_slice($t3, 1), $h['Cost'])) === [''], 'below the wall the listings\' cost column is empty');
[$c, $r] = $dl($nora, ['export' => 'listings', 'format' => 'json']);
ok($c === 200 && json_decode($r['body'], true)['schema'] === 'os.inventory-listings/1' && !str_contains($r['body'], 'credential') && !str_contains($r['body'], 'raw'), 'the listings JSON (every active source) carries no credential and no raw object');

echo "5. The log and JSON mode\n";
$since = last_activity_id();
$dl($owner, ['export' => 'sales_closed', 'format' => 'csv', 'from' => $mo, 'to' => $end]);
$lg = last_log('export.download', $since); $a = after_of($lg);
ok($lg !== null && $a['export'] === 'sales_closed' && $a['format'] === 'csv' && $a['rows'] >= 1 && $a['period'] == ['from' => $mo, 'to' => $end] && !str_contains($lg['after'], 'Alvarez'), 'export.download logged: the export, the format, the rows, the period — never the rows');
$since = last_activity_id();
$dl($nora, ['export' => 'listings', 'format' => 'csv', 'source' => (string) $w['src_malouf']]);
$lg = last_log('export.download', $since);
ok((int) $lg['source_id'] === $w['src_malouf'] && after_of($lg)['source_id'] === $w['src_malouf'], 'a listings export carries the source as the log\'s audit key');
$tok = person_token(1);
[$c, $b] = act_token('/exports/download.php', ['export' => 'catalog', 'format' => 'csv'], ['X-Action-Token: ' . $tok, 'X-Action-Relay: ' . relay_of($tok)]);
ok($c === 200 && $b['ok'] === true && $b['rows'] === $nVar && $b['bytes'] > 100 && $b['period'] === [] && $b['location'] === '/exports/' && !isset($b['body']), 'JSON mode answers the facts {ok, did, rows, bytes, period, location} and carries no file');
[$c, $b] = act_token('/exports/download.php', ['export' => 'catalog', 'format' => 'pdf'], ['X-Action-Token: ' . $tok, 'X-Action-Relay: ' . relay_of($tok)]);
ok($c === 422 && isset($b['error']['fields']['format']), 'a format that is neither csv nor json → 422 naming format');
[$c] = $dl($nora, ['export' => 'bogus', 'format' => 'csv']);
ok($c === 404, 'an export outside the five → 404');
finish();
