<?php
/** Sequences, tax rates, reason codes (reports-admin.md "Proof": ≥ 24): a number only rises, one default rate, a code is fixed, the lists and the forms. */
require __DIR__ . '/lib.php';
$w = admin_world();
[$nora, $sam, $owner] = [who('nora'), who('sam'), who('owner')];
$seq = static fn (string $k): array => q('SELECT * FROM document_sequences WHERE kind = :k', ['k' => $k])[0];

echo "1. Sequences\n";
[$c, $html] = pg($owner, '/admin/sequences');
ok($c === 200 && has_id($html, 'sequence-list-table') && array_reduce(['sales_order', 'purchase_order', 'goods_receipt', 'return', 'adjustment', 'transfer', 'count'], static fn (bool $a, string $k): bool => $a && has_id($html, "sequence-row-$k") && has_id($html, "sequence-row-$k-save-btn"), true), 'the seven sequences, a row and a Save each');
$next = $seq('sales_order')['next_value'] + 40;
$since = last_activity_id();
[$c, $b] = act($owner, '/admin/sequences.php', ['kind' => 'sales_order', 'next_value' => (string) $next]);
$lg = last_log('sequence.set', $since); $a = after_of($lg);
ok($c === 200 && (int) $seq('sales_order')['next_value'] === $next && $b['next_number'] === 'SO-' . str_pad((string) $next, 5, '0', STR_PAD_LEFT) && $a['kind'] === 'sales_order' && $a['next_value'] === $next, "raising sales_order to $next → the next number reads {$b['next_number']}; sequence.set logs the kind, before and after");
[, $q] = make_quote(who('sam'), $w['alvarez'], [['variant' => $w['queen'], 'qty' => 1, 'fulfilment' => 'stock:' . $w['wh']]], ['customer_reference' => 'S9-SEQ']);
ok((string) one('SELECT number FROM sales_orders WHERE id = :o', ['o' => $q['record_id']]) === 'SO-' . str_pad((string) $next, 5, '0', STR_PAD_LEFT), 'and the next order is numbered that');
[$c, $b] = act($owner, '/admin/sequences.php', ['kind' => 'sales_order', 'next_value' => '5']);
ok($c === 422 && str_contains(msg($b), 'never reused') && isset(fields($b)['next_value']), 'lowering the next value → 422 "a number is never reused"');
[$c, $b] = act($owner, '/admin/sequences.php', ['kind' => 'sales_order', 'prefix' => 'so-']);
ok($c === 422 && isset(fields($b)['prefix']), 'a prefix "so-" → 422');
[$c, $b] = act($owner, '/admin/sequences.php', ['kind' => 'sales_order', 'padding' => '13']);
ok($c === 422 && isset(fields($b)['padding']), 'padding 13 → 422');
[$c, $b] = act($owner, '/admin/sequences.php', ['kind' => 'invoice', 'next_value' => '5']);
ok($c === 422 && isset(fields($b)['kind']), 'a kind that is not one of the seven → 422');
[$c, $b] = act($nora, '/admin/sequences.php', ['kind' => 'sales_order', 'next_value' => (string) ($next + 5)]);
ok($c === 403 && (int) $seq('sales_order')['next_value'] === $next + 1, 'Nora (no sequences.manage) → 403');
[$c, $b] = act($owner, '/admin/sequences.php', ['kind' => 'count', 'prefix' => 'CT-', 'padding' => '4']);
ok($c === 200 && $seq('count')['prefix'] === 'CT-' && (int) $seq('count')['padding'] === 4, 'prefix and padding change on their own');
psql_exec("UPDATE document_sequences SET prefix = 'CNT-', padding = 5 WHERE kind = 'count'");

echo "2. Tax rates\n";
[$c, $b] = act($owner, '/admin/tax-rates/save.php', ['name' => 'Cook County 10.25 %', 'rate' => '10.25', 'is_default' => 'yes']);
$newId = $b['record_id'];
$defaults = q('SELECT id FROM tax_rates WHERE is_default AND archived_at IS NULL');
ok($c === 200 && count($defaults) === 1 && (int) $defaults[0]['id'] === $newId && (float) one('SELECT rate FROM tax_rates WHERE id = :i', ['i' => $newId]) === 10.25, 'a new rate made the default: the old default cleared in the same transaction, exactly one default remains');
[$c, $b] = act($owner, '/admin/tax-rates/save.php', ['name' => 'COOK county 10.25 %', 'rate' => '10']);
ok($c === 422 && str_contains(msg($b), 'already taken'), 'a duplicate name (ignoring case) → "already taken"');
$old = (int) one("SELECT id FROM tax_rates WHERE name = 'No tax'");
[$c, $b] = act($owner, '/admin/tax-rates/archive.php', ['tax_rate' => (string) $newId]);
ok($c === 422 && str_contains(msg($b), 'Make another rate the default first'), 'archiving the default → 422 "Make another rate the default first."');
[$c, $b] = act($owner, '/admin/tax-rates/save.php', ['name' => 'Temp 5', 'rate' => '5']);
$temp = $b['record_id'];
[$c, $b2] = act(who('sam'), '/orders/save.php', ['customer' => $w['alvarez'], 'lines' => json_encode([['variant' => $w['queen'], 'qty' => 1, 'fulfilment' => 'stock:' . $w['wh']]]), 'customer_reference' => 'S9-TEMP', 'tax_rate' => (string) $temp]);
psql_exec("UPDATE sales_orders SET tax_rate_id = $temp WHERE customer_reference = 'S9-TEMP'");
[$c, $html] = pg($owner, '/admin/tax-rates/');
ok(has_id($html, "tax-rate-row-$temp") && str_contains(text_of($html, "tax-rate-row-$temp"), '1 order'), 'the list shows the rate with the orders using it (1 order)');
$since = last_activity_id();
[$c, $b] = act($owner, '/admin/tax-rates/archive.php', ['tax_rate' => (string) $temp]);
[$c2, $html] = pg($owner, '/admin/tax-rates/');
ok($c === 200 && !has_id($html, "tax-rate-row-$temp") && has_id($html, "tax-rate-archived-$temp") && (int) one("SELECT tax_rate_id FROM sales_orders WHERE customer_reference = 'S9-TEMP'") === $temp && last_log('tax_rate.archive', $since) !== null, 'archiving the other: gone from the live list, listed apart as archived, the order that names it keeps it; tax_rate.archive logged');
[$c, $b] = act($owner, '/admin/tax-rates/save.php', ['tax_rate' => (string) $temp, 'name' => 'Temp 6', 'rate' => '6']);
ok($c === 422 && str_contains(msg($b), 'archived'), 'editing an archived rate → 422');
ok(pg($owner, "/admin/tax-rates/$temp/edit")[0] === 422, 'and its form is refused');
[$c, $b] = act($owner, '/admin/tax-rates/save.php', ['tax_rate' => (string) $newId, 'name' => 'Cook County 10.25 %', 'rate' => '10.25', 'is_default' => 'no']);
ok($c === 422 && str_contains(msg($b), 'default'), 'switching the only default off by editing it → 422 (make another the default instead)');
[$c, $b] = act($owner, '/admin/tax-rates/save.php', ['name' => 'Too much', 'rate' => '100']);
ok($c === 422 && isset(fields($b)['rate']), 'a rate of 100 % → 422 naming rate');
[$c, $b] = act($owner, '/admin/tax-rates/save.php', ['name' => '', 'rate' => '1']);
ok($c === 422 && isset(fields($b)['name']), 'no name → 422 naming name');
$since = last_activity_id();
[$c, $b] = act($owner, '/admin/tax-rates/save.php', ['tax_rate' => (string) $old, 'name' => 'No tax', 'rate' => '0', 'is_default' => 'yes']);
$lg = last_log('tax_rate.save', $since);
ok($c === 200 && (int) one('SELECT id FROM tax_rates WHERE is_default AND archived_at IS NULL') === $old && $lg !== null && after_of($lg)['is_default'] === true, 'making "No tax" the default again moves the one default back; tax_rate.save logged');
[$c] = act($nora, '/admin/tax-rates/save.php', ['name' => 'Nope', 'rate' => '1']);
ok($c === 403, 'Nora → 403');
[$c, $html] = pg($owner, "/admin/tax-rates/$newId/edit");
ok($c === 200 && has_id($html, 'tax-rate-form') && has_id($html, 'tax-rate-form-field-name') && has_id($html, 'tax-rate-form-field-rate') && has_id($html, 'tax-rate-form-field-is_default') && has_id($html, 'tax-rate-form-save-btn'), 'the form: name, rate, default, Save');

echo "3. Reason codes\n";
[$c, $b] = act($owner, '/admin/reason-codes/save.php', ['name' => 'Water damage', 'applies_to' => ['return']]);
$wd = $b['record_id'];
$rc = q('SELECT * FROM reason_codes WHERE id = :i', ['i' => $wd])[0];
ok($c === 200 && $rc['code'] === 'water_damage' && $rc['applies_to'] === '{return}' && $rc['affects_qty'] === true && $rc['active'] === true, '"Water damage" → water_damage, applies to return, moves quantity');
[, $d] = screen($sam, '/returns/new?order=' . $w['so1']);
ok(in_array('water_damage', array_column($d['reasons'] ?? [], 'code'), true), 'and it is in slice 8\'s return form');
[, $d] = screen(who('wes'), '/adjustments/new');
ok(!in_array('water_damage', array_column($d['reasons'] ?? [], 'code'), true), 'but not in the adjustment form (it applies to returns)');
[$c, $b] = act($owner, '/admin/reason-codes/save.php', ['name' => 'Damaged', 'code' => 'Damaged', 'applies_to' => ['return']]);
ok($c === 422 && str_contains(msg($b), 'already used'), 'a code "Damaged" again → 422 "That code is already used."');
$dam = (int) one("SELECT id FROM reason_codes WHERE code = 'damaged'");
[$c, $b] = act($owner, '/admin/reason-codes/save.php', ['reason' => (string) $dam, 'name' => 'Damaged goods', 'code' => 'broken', 'applies_to' => ['adjustment', 'return'], 'sort_order' => '1']);
ok($c === 200 && (string) one('SELECT code FROM reason_codes WHERE id = :i', ['i' => $dam]) === 'damaged' && (string) one('SELECT name FROM reason_codes WHERE id = :i', ['i' => $dam]) === 'Damaged goods' && str_contains($b['did'], 'the code stays damaged'), 'editing a seeded code keeps its code (the posted one ignored, and the answer says so): ' . $b['did']);
psql_exec("UPDATE reason_codes SET name = 'Damaged' WHERE id = $dam");
[$c, $b] = act($owner, '/admin/reason-codes/save.php', ['name' => 'Nothing applies', 'applies_to' => '']);
ok($c === 422 && isset(fields($b)['applies_to']), 'no applies_to → 422');
[$c, $b] = act($owner, '/admin/reason-codes/save.php', ['name' => 'Bad code', 'code' => '9lives', 'applies_to' => ['return']]);
ok($c === 422 && isset(fields($b)['code']), 'a code that does not start with a letter → 422');
[$c, $b] = act($owner, '/admin/reason-codes/save.php', ['name' => 'Spill', 'applies_to' => ['adjustment']]);
$spill = $b['record_id'];
[$c, $b] = act(who('wes'), '/adjustments/save.php', ['location' => $w['wh'], 'reason' => 'spill', 'notes' => 'S9 spill']);
$adj = $b['record_id'];
[$c, $b] = act($owner, '/admin/reason-codes/save.php', ['reason' => (string) $spill, 'name' => 'Spill', 'active' => 'no']);
[, $d] = screen(who('wes'), '/adjustments/new');
[$c3, $html] = pg(who('wes'), "/adjustments/$adj");
ok($c === 200 && !in_array('spill', array_column($d['reasons'] ?? [], 'code'), true) && $c3 === 200 && str_contains($html, 'Spill'), 'the inactive reason leaves the picker and stays on the old adjustment');
[$c, $html] = pg($owner, '/admin/reason-codes/');
ok($c === 200 && has_id($html, "reason-code-row-$wd") && has_id($html, "reason-code-row-$wd-edit-btn") && has_id($html, 'reason-code-list-add-btn') && str_contains($html, 'water_damage'), 'the list: a row and an Edit for each, and Add a reason code');
[$c, $html] = pg($owner, "/admin/reason-codes/$wd/edit");
ok($c === 200 && preg_match('#id="reason-code-form-field-code"[^>]*readonly#', $html) === 1 && has_id($html, 'reason-code-form-field-affects_qty'), 'the edit form shows the code read-only');
[$c] = act($nora, '/admin/reason-codes/save.php', ['name' => 'Nope']);
ok($c === 403, 'Nora → 403');
$since = last_activity_id();
act($owner, '/admin/reason-codes/save.php', ['reason' => (string) $wd, 'name' => 'Water damage', 'sort_order' => '8']);
$lg = last_log('reason_code.save', $since);
ok($lg !== null && after_of($lg)['code'] === 'water_damage' && after_of($lg)['changed'] === ['sort_order'], 'reason_code.save logged with the code and the fields changed');
finish();
