<?php
/** Watches that fire, and the dispatches pass (returns-worker.md "Proof": watches and dispatches ≥ 26): the watch fires once per state change and dispatches its agent; the pass turns the dispatch into one chat turn through the kernel, with every answer and failure. */
require __DIR__ . '/lib.php';
$w = returns_world();
[$nora, $sam, $wes, $vera, $owner] = [$w['nora'], $w['sam'], $w['wes'], $w['vera'], $w['owner']];
$lv = $w['lv_zinus_k'];
$watch = $w['watch_sam'];
kernel_clean();
$mk = static function (string $title = 'S8 dispatch') use ($watch, $lv): int {
    psql_exec("INSERT INTO agent_dispatches (record_type, record_id, agent_member_id, kind, via, acting_member_id, watch_id, listing_variant_id, detail) VALUES ('watch', $watch, 45, 'watch', 'chat', 41, $watch, $lv, '$title')");
    return (int) one('SELECT max(id) FROM agent_dispatches');
};
$row = static fn (int $id): array => q('SELECT * FROM agent_dispatches WHERE id = :i', ['i' => $id])[0];
// anything left from the earlier proofs is settled first
psql_exec("UPDATE agent_dispatches SET status = 'failed' WHERE status = 'sent'");

echo "1. The watch fires once per state change\n";
psql_exec("UPDATE listing_variants SET availability = 'out_of_stock' WHERE id = $lv");
wk('watches');
$wr = q('SELECT * FROM watches WHERE id = :w', ['w' => $watch])[0];
ok($wr['last_state'] === false && (int) $wr['fire_count'] === 0, 'the offer is out of stock: the watch is armed (last_state false), nothing fired');
$n0 = last_notification_id(); $o0 = last_outbox_id(); $d0 = last_dispatch_id(); $since = last_activity_id();
psql_exec("UPDATE listing_variants SET availability = 'in_stock' WHERE id = $lv");
$r = wk('watches');
$wr = q('SELECT * FROM watches WHERE id = :w', ['w' => $watch])[0];
ok(($r['watches']['fired'] ?? 0) === 1 && (int) $wr['fire_count'] === 1 && $wr['fired_at'] !== null && $wr['last_state'] === true, 'it goes back in stock: the `watches` pass fires Sam\'s watch once (fired_at, fire_count 1)');
$n = notifications_for(41, 'watch', $n0);
$ob = outbox_rows($o0);
ok(count($n) === 1 && str_starts_with($n[0]['title'], 'Back in stock:') && array_column($ob, 'channel') === ['email', 'text'], 'a `watch` notice for Sam, with an e-mail and — he chose text_me — a text row queued');
$d = dispatch_rows($d0);
ok(count($d) === 1 && $d[0]['kind'] === 'watch' && $d[0]['via'] === 'chat' && (int) $d[0]['acting_member_id'] === 41 && (int) $d[0]['agent_member_id'] === EXPERT && (int) $d[0]['watch_id'] === $watch && (int) $d[0]['listing_variant_id'] === $lv && $d[0]['status'] === 'sent' && (int) $d[0]['attempts'] === 1, 'an agent_dispatches row: kind watch, via chat, acting Sam, the expert, the watch and the listing variant');
$f = after_of(last_log('watch.fire', $since));
ok($f['notified'] > 0 && $f['texted'] === true && $f['dispatched'] > 0 && (int) $f['fire_count'] === 1, 'watch.fire is logged with notified, texted and dispatched');
$r = wk('watches');
ok(($r['watches']['fired'] ?? 1) === 0 && (int) q('SELECT fire_count FROM watches WHERE id = :w', ['w' => $watch])[0]['fire_count'] === 1 && count(dispatch_rows($d0)) === 1, 'a second pass fires nothing');
psql_exec("UPDATE listing_variants SET availability = 'out_of_stock' WHERE id = $lv");
wk('watches');
psql_exec("UPDATE listing_variants SET availability = 'in_stock' WHERE id = $lv");
$r = wk('watches');
ok(($r['watches']['fired'] ?? 0) === 1 && (int) q('SELECT fire_count FROM watches WHERE id = :w', ['w' => $watch])[0]['fire_count'] === 2 && count(dispatch_rows($d0)) === 2, 'out and in again fires again (fire_count 2) and dispatches again');

echo "2. The dispatches pass: a reply\n";
psql_exec("UPDATE agent_dispatches SET status = 'failed' WHERE id > $d0 AND id < " . (int) (last_dispatch_id()));       // leave the newest one live
$live = last_dispatch_id();
$long = rtrim(str_repeat('We found a purchase order to raise: Zinus has the King in stock at 649.00. ', 5));
kstate(['chat' => ['run_id' => 71, 'request_id' => 'req-71', 'status' => 'succeeded', 'finished' => true, 'reply' => $long, 'actions' => [], 'cost' => 0.0123, 'currency' => 'USD']]);
$n0 = last_notification_id(); $since = last_activity_id();
$r = wk('dispatches');
$dr = $row($live); $cl = chat_log();
ok(($r['dispatches']['called'] ?? 0) === 1 && ($r['dispatches']['answered'] ?? 0) === 1, 'the pass calls the kernel once and the dispatch is answered: ' . json_encode($r['dispatches'] ?? null));
ok(count($cl) === 1 && $cl[0]['method'] === 'POST' && $cl[0]['agent'] === '45' && $cl[0]['acting'] === '41' && $cl[0]['conversation_id'] === '' && $cl[0]['screen'] === 'watch' && (int) $cl[0]['context']['record_id'] === $watch && $cl[0]['context']['entity'] === 'watch', 'the kernel was asked as agent 45 for acting member 41, from the `watch` screen of that watch, with no conversation');
ok(str_contains($cl[0]['utterance'], 'Back in stock:') && str_contains($cl[0]['utterance'], 'Set by SMOKE Sam') && str_contains($cl[0]['utterance'], one('SELECT number FROM sales_orders WHERE id = :o', ['o' => $w['main']])) && str_contains($cl[0]['utterance'], 'Propose; never send, place, price or delete.') && !str_contains($cl[0]['utterance'], 'Alvarez'), 'the utterance names the watch, who set it, the sold order waiting on the King and the limit — and no customer');
ok($dr['status'] === 'answered' && (int) $dr['run_id'] === 71 && $dr['request_id'] === 'req-71' && mb_strlen($dr['reply_excerpt']) === 200 && $dr['answered_at'] !== null, 'answered: run_id, request_id, a reply excerpt of 200 characters, answered_at');
$n = notifications_for(41, 'agent_drafted', $n0);
ok(count($n) === 1 && str_starts_with($n[0]['title'], 'SMOKE Inventory expert: Back in stock:') && $n[0]['body'] === $long && $n[0]['record_type'] === 'agent_dispatch', 'Sam gets an `agent_drafted` notice with the reply in full');
$lg = last_log('agent.reply', $since); $a = after_of($lg);
ok($lg !== null && $lg['source'] === 'cron' && $a['reply_length'] === mb_strlen($long) && $a['run_id'] === 71 && (int) $a['dispatch_id'] === $live && !str_contains($lg['after'], 'purchase order to raise') && $a['cost'] == 0.0123, 'agent.reply logged with the length, the run, the cost — never the words');
ok(last_log('agent.dispatch', $since) !== null, 'agent.dispatch was logged when the call was made');
$r = wk('dispatches');
ok(($r['dispatches']['called'] ?? 1) === 0 && count(chat_log()) === 1, 'an answered dispatch is not called again');

echo "3. A run still going, a refusal, a paused write\n";
$id = $mk();
kstate(['chat' => ['run_id' => 77, 'status' => 'running', 'finished' => false], 'chat_http' => 202]);
$r = wk('dispatches');
$dr = $row($id);
ok(($r['dispatches']['called'] ?? 0) === 1 && $dr['status'] === 'sent' && (int) $dr['run_id'] === 77 && ($r['dispatches']['running'] ?? 0) === 1, 'the kernel took it (202, not finished): status stays sent with the run id kept');
kstate(['chat_runs' => ['77' => ['run_id' => 77, 'request_id' => 'req-77', 'status' => 'succeeded', 'finished' => true, 'reply' => 'Done: I drafted a purchase order.']]], ['chat', 'chat_http']);
$c0 = count(chat_log()); $n0 = last_notification_id();
$r = wk('dispatches');
$cl = array_slice(chat_log(), $c0);
$dr = $row($id);
ok(count($cl) === 1 && $cl[0]['method'] === 'GET' && (int) $cl[0]['run'] === 77 && $dr['status'] === 'answered' && $dr['reply_excerpt'] === 'Done: I drafted a purchase order.' && ($r['dispatches']['polled'] ?? 0) === 1 && count(notifications_for(41, 'agent_drafted', $n0)) === 1, 'the next pass GETs the run: finished, answered, Sam told');
$id = $mk();
kstate(['chat_status' => 403, 'chat_message' => 'That agent has no access to Inventory.']);
$r = wk('dispatches'); $dr = $row($id); $since = last_activity_id();
ok($dr['status'] === 'refused' && $dr['detail'] === 'That agent has no access to Inventory.' && ($r['dispatches']['refused'] ?? 0) === 1, 'the kernel says 403: refused, with its sentence kept');
$c0 = count(chat_log());
wk('dispatches');
ok(count(chat_log()) === $c0 && after_of(q("SELECT * FROM activity_log WHERE action = 'agent.fail' AND entity_id = :i ORDER BY id DESC LIMIT 1", ['i' => $id])[0])['status'] === 'refused', 'a refusal is not retried; agent.fail was logged');
$id = $mk();
kstate(['chat_status' => 409, 'chat_message' => 'The expert is busy.'], []);
wk('dispatches');
ok($row($id)['status'] === 'refused' && $row($id)['detail'] === 'The expert is busy.', '409 (busy) is a refusal too');
$id = $mk();
kernel_clean();
kstate(['chat' => ['run_id' => 5, 'status' => 'paused', 'finished' => true, 'reply' => '', 'approval_request_id' => 12]]);
$r = wk('dispatches'); $dr = $row($id);
ok($dr['status'] === 'awaiting_approval' && $dr['detail'] === 'approval #12 awaits a person' && (int) $dr['run_id'] === 5 && ($r['dispatches']['awaiting_approval'] ?? 0) === 1, 'the agent\'s own write paused in the kernel: awaiting_approval, "approval #12 awaits a person"');

echo "4. Failures: backoff, three calls, one notice\n";
kernel_clean();
psql_exec("UPDATE agent_dispatches SET status = 'failed' WHERE status = 'sent'");
$id = $mk();
kstate(['chat_status' => 500]);
$n0 = last_notification_id();
$r = wk('dispatches'); $dr = $row($id);
ok(($r['dispatches']['retried'] ?? 0) === 1 && (int) $dr['attempts'] === 2 && $dr['status'] === 'sent' && str_contains((string) $dr['detail'], 'not reachable'), 'a 500: attempts 2, still sent, the sentence in detail');
$c0 = count(chat_log());
wk('dispatches');
ok(count(chat_log()) === $c0, 'not due for 4 minutes: the next pass does not call');
$r = wk('dispatches', later(5)); $dr = $row($id);
ok(($r['dispatches']['retried'] ?? 0) === 1 && (int) $dr['attempts'] === 3 && $dr['status'] === 'sent' && count(chat_log()) === $c0 + 1, 'at 4 minutes it is called again and fails again: attempts 3');
wk('dispatches', later(6));
ok(count(chat_log()) === $c0 + 1, '…and is not due again before 8 minutes');
$r = wk('dispatches', later(9)); $dr = $row($id);
ok(($r['dispatches']['failed'] ?? 0) === 1 && $dr['status'] === 'failed' && (int) $dr['attempts'] === 3 && count(chat_log()) === $c0 + 2, 'the third failure is final: failed');
$told = q("SELECT * FROM notifications WHERE id > :s AND kind = 'agent_drafted' AND member_id = 41", ['s' => $n0]);
ok(count($told) === 1 && str_contains($told[0]['title'], 'could not answer'), 'Sam is told once ("could not answer")');
ok(after_of(q("SELECT * FROM activity_log WHERE action = 'agent.fail' AND entity_id = :i ORDER BY id DESC LIMIT 1", ['i' => $id])[0])['status'] === 'failed', 'agent.fail logged');

echo "5. Retry and the list\n";
kernel_clean();
[$c, $b] = act($nora, '/admin/dispatches/retry.php', ['dispatch' => $id]);
ok($c === 403, 'Nora retrying: 403 (agents.settings)');
$since = last_activity_id();
[$c, $b] = act($owner, '/admin/dispatches/retry.php', ['dispatch' => $id]);
$dr = $row($id); $a = after_of(last_log('agent.dispatch', $since));
ok($c === 200 && $dr['status'] === 'sent' && $dr['run_id'] === null && $dr['detail'] === null && $a['retry'] === true && last_log('agent.dispatch', $since)['source'] === 'web', 'the admin retries: sent again, no run, no detail; logged agent.dispatch with retry true (source web)');
[$c, $b] = act($owner, '/admin/dispatches/retry.php', ['dispatch' => $id]);
ok($c === 422 && str_contains(msg($b), 'Only a failed dispatch is retried.'), 'a dispatch that is not failed is not retried');
$r = wk('dispatches');
ok($row($id)['status'] === 'answered' && ($r['dispatches']['answered'] ?? 0) === 1, 'the next pass answers it');
[$c, $d] = screen($owner, '/admin/dispatches?status=answered');
ok($c === 200 && count($d['dispatches']) >= 3 && array_unique(array_column($d['dispatches'], 'status')) === ['answered'], 'the list filtered by status');
[$c, $d] = screen($owner, '/admin/dispatches?agent=45&status=refused');
ok($c === 200 && count($d['dispatches']) >= 2 && array_unique(array_column($d['dispatches'], 'agent_member_id')) === [45], 'and by agent');
$runId = $row($live)['run_id'];
$h = req('GET', '/admin/dispatches', ['jar' => $owner]);
ok($h['code'] === 200 && str_contains($h['body'], 'id="dispatch-list-table"') && str_contains($h['body'], 'https://os.example.invalid/ai/runs/71') && str_contains($h['body'], "id=\"dispatch-row-$id-retry-btn\"") === false, 'the page: the table, the run linked to the OS (`os.` for `app.`), no Retry on an answered one');
ok(req('GET', '/admin/dispatches', ['jar' => $nora])['code'] === 403 && req('GET', '/admin/dispatches', ['jar' => $sam])['code'] === 403, 'Nora and Sam may not open the list');

echo "6. At most five a pass\n";
kernel_clean();
psql_exec("UPDATE agent_dispatches SET status = 'failed' WHERE status = 'sent'");
$six = [];
for ($i = 0; $i < 6; $i++) { $six[] = $mk("S8 six $i"); }
$c0 = count(chat_log());
$r = wk('dispatches');
ok(($r['dispatches']['called'] ?? 0) === 5 && count(chat_log()) === $c0 + 5 && (int) one("SELECT count(*) FROM agent_dispatches WHERE id IN (" . implode(',', $six) . ") AND status = 'sent'") === 1, 'six are due: five are called, one is left');
$r = wk('dispatches');
ok(($r['dispatches']['called'] ?? 0) === 1, 'and the next pass takes the last');
finish();
