<?php
/** The Buyer agent's proposals (returns-worker.md "Proof": proposals ≥ 24): made by the agent, accepted by a person, dismissed with a reason and not made again for 30 days. */
require __DIR__ . '/lib.php';
$w = returns_world();
[$nora, $sam, $wes, $vera, $owner] = [$w['nora'], $w['sam'], $w['wes'], $w['vera'], $w['owner']];
kernel_clean();
$A = as_agent(run_token(47, 331));

echo "1. The agent proposes\n";
[$c, $b] = act_token('/purchasing/save.php', ['supplier' => $w['zinus'], 'lines' => json_encode([['variant' => $w['twin'], 'qty' => 6]]), 'notes' => 'SMOKE S8 reorder'], $A);
$po = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $po > 0 && po_row($po)['status'] === 'draft', 'the Buyer agent drafts a purchase order for the Twin (slice 6\'s purchase_order_draft)');
$since = last_activity_id();
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'reorder', 'subject' => 'Reorder the Twin from Zinus', 'variant' => $w['twin'], 'drafted_record' => $po, 'evidence' => json_encode(['on_hand' => 0, 'best_cost' => 321.5, 'supplier_lead_days' => 3]), 'confidence' => '0.9'], $A);
$p1 = (int) ($b['record_id'] ?? 0);
$row = $p1 ? q('SELECT * FROM buyer_proposals WHERE id = :i', ['i' => $p1])[0] : [];
$d = json_decode($row['detail'] ?? '{}', true);
ok($c === 200 && $p1 > 0 && $row['status'] === 'proposed' && $row['kind'] === 'reorder' && $row['subject_type'] === 'product_variant' && (int) $row['subject_id'] === $w['twin'] && $row['drafted_record_type'] === 'purchase_order' && (int) $row['drafted_record_id'] === $po && (int) $row['proposed_by'] === 47 && $row['note_date'] === gmdate('Y-m-d') && $d['confidence'] == 0.9 && $d['evidence']['best_cost'] == 321.5, 'a reorder is proposed: its subject, the drafted purchase order, who, the day, the evidence and the confidence kept in the detail');
$lg = last_log('buyer.propose', $since); $a = after_of($lg);
ok($lg !== null && $lg['source'] === 'agent' && (int) $a['proposal_id'] === $p1 && $a['kind'] === 'reorder' && $a['drafted_record_type'] === 'purchase_order' && (int) $a['drafted_record_id'] === $po && !str_contains($lg['after'], '321.5'), 'logged buyer.propose (source agent) with the ids — not the evidence');
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'reorder', 'subject' => 'again', 'variant' => $w['twin']], $A);
ok($c === 422 && str_contains(msg($b), 'Already proposed on') && (int) ($b['error']['record_id'] ?? 0) === $p1, 'the same kind and subject again while it is open: "Already proposed on …" pointing at the first');
$mp = (int) one('SELECT id FROM match_proposals ORDER BY id LIMIT 1');
if ($mp === 0) {
    $lvu = (int) one("SELECT id FROM listing_variants WHERE external_variant_id = 'S8-UNM-1'");
    psql_exec("INSERT INTO match_proposals (listing_variant_id, variant_id, confidence, evidence, proposed_by) VALUES ($lvu, {$w['twin']}, 0.7, '{}', 47)");
    $mp = (int) one('SELECT id FROM match_proposals ORDER BY id DESC LIMIT 1');
}
$lvu = (int) one("SELECT id FROM listing_variants WHERE external_variant_id = 'S8-UNM-2'");
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'match', 'subject' => 'Match S8 unmatched 2', 'listing_variant' => $lvu, 'drafted_record' => $mp, 'evidence' => json_encode(['sku' => 'S8U2', 'why' => 'same title']), 'confidence' => '0.75'], $A);
$p2 = (int) ($b['record_id'] ?? 0);
ok($c === 200 && one('SELECT drafted_record_type FROM buyer_proposals WHERE id = :i', ['i' => $p2]) === 'match_proposal' && one('SELECT subject_type FROM buyer_proposals WHERE id = :i', ['i' => $p2]) === 'listing_variant', 'a match proposal with evidence and confidence, drafting a match proposal');
$kl = sol_of($w['main'], 'SMOKE-NW-CR-K');
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'at_risk', 'subject' => 'The King on the open order', 'line' => $kl['id']], $A);
$p3 = (int) ($b['record_id'] ?? 0);
ok($c === 200 && one('SELECT subject_type FROM buyer_proposals WHERE id = :i', ['i' => $p3]) === 'sales_order_line' && one('SELECT drafted_record_type FROM buyer_proposals WHERE id = :i', ['i' => $p3]) === null, 'an at_risk proposal about an order line');
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'price', 'subject' => 'x', 'variant' => 999999], $A);
ok($c === 404, 'a variant nobody can see: 404');
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'sing', 'subject' => 'x', 'variant' => $w['twin']], $A);
ok($c === 422 && isset(fields($b)['kind']), 'a kind that is none: a field error');
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'price', 'subject' => 'x', 'variant' => $w['twin'], 'listing_variant' => $lvu], $A);
ok($c === 422 && isset(fields($b)['variant']), 'two records at once: refused (exactly one)');
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'price', 'subject' => 'x', 'variant' => $w['queen'], 'drafted_record' => $po], $A);
ok($c === 422 && isset(fields($b)['drafted_record']), 'a price proposal drafts nothing: refused');
[$c] = act($sam, '/proposals/save.php', ['kind' => 'price', 'subject' => 'x', 'variant' => $w['queen']]);
ok($c === 403, 'Sam may not propose (purchasing.write)');

echo "2. A person decides\n";
$since = last_activity_id();
[$c, $b] = act_token('/proposals/accept.php', ['proposal' => $p1], $A);
ok($c === 403 && str_contains(msg($b), 'A person accepts a proposal.') && one('SELECT status FROM buyer_proposals WHERE id = :i', ['i' => $p1]) === 'proposed', 'the agent accepting its own proposal: 403 "A person accepts a proposal."');
[$c, $b] = act($sam, '/proposals/accept.php', ['proposal' => $p1]);
ok($c === 403, 'Sam accepting: 403 (purchasing.write)');
[$c, $b] = act($nora, '/proposals/accept.php', ['proposal' => $p1]);
$row = q('SELECT * FROM buyer_proposals WHERE id = :i', ['i' => $p1])[0];
ok($c === 200 && $row['status'] === 'accepted' && (int) $row['decided_by'] === 40 && $row['decided_at'] !== null && po_row($po)['status'] === 'draft', 'Nora accepts the reorder: accepted, decided by her — and the purchase order is still a draft');
ok(last_log('buyer.accept', $since) !== null && last_log('buyer.accept', $since)['source'] === 'web', 'logged buyer.accept');
[$c, $b] = act($nora, '/proposals/accept.php', ['proposal' => $p1]);
ok($c === 422 && str_contains(msg($b), 'already accepted'), 'accepting twice: "already accepted"');
[$c, $b] = act($nora, '/proposals/dismiss.php', ['proposal' => $p2, 'reason' => 'Not the same product']);
$row = q('SELECT * FROM buyer_proposals WHERE id = :i', ['i' => $p2])[0];
$d = json_decode($row['detail'], true);
ok($c === 200 && $row['status'] === 'dismissed' && $d['dismiss_reason'] === 'Not the same product' && $d['confidence'] == 0.75, 'Nora dismisses the match with a reason: dismissed, the reason kept beside the evidence');
ok(after_of(last_log('buyer.dismiss'))['reason'] === 'Not the same product', 'logged buyer.dismiss with the reason');
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'match', 'subject' => 'Match S8 unmatched 2', 'listing_variant' => $lvu], $A);
ok($c === 422 && preg_match('/^Dismissed on .+: Not the same product$/', msg($b)) === 1, 'proposing it again within 30 days: "Dismissed on <date>: Not the same product"');
psql_exec("UPDATE buyer_proposals SET decided_at = now() - interval '31 days' WHERE id = $p2");
[$c, $b] = act_token('/proposals/save.php', ['kind' => 'match', 'subject' => 'Match S8 unmatched 2 (again)', 'listing_variant' => $lvu], $A);
$p4 = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $p4 > $p2, 'after 31 days it may be proposed again');
[$c, $b] = act_token('/proposals/dismiss.php', ['proposal' => $p3, 'reason' => 'checked: fine'], $A);
ok($c === 200 && one('SELECT status FROM buyer_proposals WHERE id = :i', ['i' => $p3]) === 'dismissed', 'the agent may dismiss (a person or an agent)');
[$c, $b] = act($nora, '/proposals/dismiss.php', ['proposal' => $p1]);
ok($c === 422 && str_contains(msg($b), 'already accepted'), 'dismissing an accepted proposal: refused');

echo "3. The list\n";
[$c, $d] = screen($nora, '/proposals/');
ok($c === 200 && $d['status'] === 'proposed' && in_array($p4, array_column($d['proposals'], 'proposal_id'), true) && !in_array($p1, array_column($d['proposals'], 'proposal_id'), true) && $d['counts']['accepted'] >= 1 && $d['counts']['dismissed'] >= 2 && $d['counts']['proposed'] >= 1, 'the proposed tab holds the open one, the counts of the three tabs are there');
[$c, $d] = screen($nora, '/proposals/?status=accepted');
$x = array_values(array_filter($d['proposals'], static fn ($p) => $p['proposal_id'] === $p1))[0] ?? null;
ok($x !== null && $x['subject'] === 'SMOKE-NW-CR-T — SMOKE Cloudrest Hybrid' || ($x !== null && str_starts_with((string) $x['subject'], 'SMOKE-NW-CR-T')), 'the accepted tab holds the reorder, with the subject\'s label');
ok(($x['drafted'] ?? '') === po_row($po)['number'], 'and the drafted purchase order\'s number');
[$c, $d] = screen($nora, '/proposals/?status=dismissed&kind=match');
ok($c === 200 && array_unique(array_column($d['proposals'], 'kind')) === ['match'] && in_array($p2, array_column($d['proposals'], 'proposal_id'), true), 'filtered by kind');
[$c, $d] = screen($nora, '/proposals/?status=accepted&date=2020-01-01');
ok($c === 200 && $d['proposals'] === [], 'and by date');
$r = req('GET', '/proposals/', ['jar' => $nora]);
ok($r['code'] === 200 && str_contains($r['body'], "id=\"proposal-card-$p4\"") && str_contains($r['body'], "id=\"proposal-card-$p4-accept-btn\"") && str_contains($r['body'], "id=\"proposal-card-$p4-dismiss-btn\"") && str_contains($r['body'], 'id="proposal-list-note"') && str_contains($r['body'], 'Morning note —'), 'the page: a card with Accept and Dismiss, the morning note above, collapsed');
$r = req('GET', '/proposals/?status=accepted', ['jar' => $nora]);
ok(str_contains($r['body'], "id=\"proposal-card-$p1\"") && !str_contains($r['body'], "id=\"proposal-card-$p1-accept-btn\"") && str_contains($r['body'], "id=\"proposal-card-$p1-drafted\"") , 'an accepted card has neither button, and links its drafted purchase order');
ok(req('GET', '/proposals/', ['jar' => $sam])['code'] === 403 && req('GET', '/proposals/', ['jar' => $vera])['code'] === 403 && req('GET', '/proposals/', ['jar' => $owner])['code'] === 200, 'Sam and Vera may not open it; the admin may');

echo "4. Cost and the note\n";
psql_exec("INSERT INTO buyer_proposals (kind, subject_type, subject_id, title, proposed_by, detail) VALUES ('price', 'product_variant', {$w['queen']}, 'S8 expert price', 45, '{\"best_cost\": 450, \"margin\": 12, \"cost\": 3, \"seen\": \"yes\"}')");
as_db(45);
$rows = q('SELECT detail FROM mcp_buyer_proposals');
$dd = json_decode($rows[0]['detail'] ?? '{}', true);
ok(count($rows) === 1 && $dd === ['seen' => 'yes'], 'a caller without cost sees only the proposals they made, and the view strips best_cost, margin and cost from the detail');
as_db(40);
$dn = json_decode(q("SELECT detail FROM mcp_buyer_proposals WHERE title = 'S8 expert price'")[0]['detail'], true);
ok($dn['best_cost'] == 450, 'the Buyer sees the cost');
$n = call_fn(40, 'morning_note', [null, 5])['result'];
$titles = array_column($n['proposals'], 'title');
ok(in_array('Reorder the Twin from Zinus', $titles, true) && in_array('Match S8 unmatched 2 (again)', $titles, true) && in_array(['kind' => 'reorder', 'drafted_record_type' => 'purchase_order', 'drafted_record_id' => $po, 'status' => 'accepted'], $n['drafted'], true), 'the morning note\'s `proposals` list today\'s, `drafted` the records they drafted with their status');
ok(str_contains($n['markdown'], 'Drafts and proposals:') && str_contains($n['markdown'], '#' . $p1 . ' reorder: Reorder the Twin from Zinus (accepted) — drafted purchase order ' . $po), 'and the markdown lists them by number');
$rd = call_fn(40, 'recently_dismissed', [30])['result'];
ok(in_array($p3, array_column($rd, 'proposal_id'), true) && !in_array($p2, array_column($rd, 'proposal_id'), true), 'recently_dismissed(30) lists the dismissals of the last month (not the one of 31 days ago)');
finish();
