<?php
/** Request, lines, approve, deny, disposition (returns-worker.md "Proof": request and lines ≥ 30, approve/deny/disposition ≥ 18). */
require __DIR__ . '/lib.php';
$w = returns_world();
[$nora, $sam, $wes, $vera, $owner] = [$w['nora'], $w['sam'], $w['wes'], $w['vera'], $w['owner']];
$q1 = sol_of($w['so1'], 'SMOKE-NW-CR-Q');
$k1 = sol_of($w['so1'], 'SMOKE-NW-CR-K');
$q2 = sol_of($w['so2'], 'SMOKE-NW-CR-Q');
$lines = static fn (array $l): string => json_encode($l);

echo "1. Request\n";
$since = last_activity_id(); $nid = last_notification_id(); $ob = last_outbox_id();
[$c, $b] = act($sam, '/returns/save.php', ['order' => $w['so1'], 'lines' => $lines([['line' => $q1['id'], 'qty' => 1, 'reason' => 'comfort', 'disposition' => 'restock']]), 'location' => $w['wh'], 'method' => 'pickup', 'scheduled_on' => date('Y-m-d', strtotime('+2 days')), 'notes' => 'SMOKE S8-RA1']);
$ra1 = (int) ($b['record_id'] ?? 0);
$r1 = $ra1 ? return_row($ra1) : [];
ok($c === 200 && $ra1 > 0 && str_starts_with((string) ($r1['number'] ?? ''), 'RA-') && $r1['status'] === 'requested', "Sam requests a return on SO-1 line 1 (comfort, restock, the warehouse): {$r1['number']} requested");
ok((int) $r1['customer_id'] === $w['alvarez'] && (int) $r1['requested_by'] === 41 && (int) $r1['location_id'] === $w['wh'] && $b['location'] === "/returns/$ra1?notice=requested", 'the trigger set the customer; requested by Sam; the location is the warehouse; the location lands on the return');
$lg = last_log('return.request', $since);
$a = after_of($lg);
ok($lg !== null && (int) $lg['sales_order_id'] === $w['so1'] && $lg['source'] === 'web' && $a['number'] === $r1['number'] && $a['lines'][0]['sku'] === 'SMOKE-NW-CR-Q' && $a['lines'][0]['reason_code'] === 'comfort' && $a['currency'] === 'USD' && $lg['entity_type'] === 'return_authorization', 'logged return.request with sales_order_id, the lines (sku, qty, reason_code, disposition) and the currency');
$n = notifications_for(40, 'return', $nid);
ok(count($n) === 1 && $n[0]['record_type'] === 'return' && (int) $n[0]['record_id'] === $ra1 && str_contains($n[0]['title'], $r1['number'] . ' requested on') , 'Nora, the Buyer, is told (a `return` notice naming the return)');
$o = outbox_rows($ob);
ok(count($o) === 1 && $o[0]['channel'] === 'email' && (int) $o[0]['member_id'] === 40 && $o[0]['dedupe_key'] === "return:$ra1:requested:email" && $o[0]['status'] === 'queued', 'and an e-mail is queued by her preferences (dedupe return:<id>:requested)');

echo "2. What the database refuses\n";
[$sq] = [null];
[, $bq] = make_quote($sam, $w['alvarez'], [['variant' => $w['queen'], 'qty' => 1, 'fulfilment' => 'stock:' . $w['wh']]], ['customer_reference' => 'S8-QUOTE']);
$quote = (int) $bq['record_id'];
$ql = sol_of($quote, 'SMOKE-NW-CR-Q');
[$c, $b] = act($sam, '/returns/save.php', ['order' => $quote, 'lines' => $lines([['line' => $ql['id'], 'qty' => 1, 'reason' => 'comfort']]), 'location' => $w['wh']]);
ok($c === 422 && str_contains(msg($b), 'A return is against a confirmed order (it is quote)'), 'a return on a quote: the trigger\'s sentence');
[$c, $b] = act($sam, '/returns/save.php', ['order' => $w['so2'], 'lines' => $lines([['line' => $q2['id'], 'qty' => 2, 'reason' => 'comfort']]), 'location' => $w['wh']]);
ok($c === 422 && msg($b) === 'Line 1 shipped 1 and 1 may still come back' && isset(fields($b)['lines.' . $q2['id'] . '.qty']), "qty 2 on a line that shipped 1: \"Line 1 shipped 1 and 1 may still come back\", naming lines.{$q2['id']}.qty");
[$c, $b] = act($sam, '/returns/save.php', ['order' => $w['so2'], 'lines' => $lines([['line' => $q2['id'], 'qty' => 1, 'reason' => 'found']]), 'location' => $w['wh']]);
ok($c === 422 && str_contains(msg($b), 'That reason is not a return reason'), 'an adjustment-only reason (found): "That reason is not a return reason"');
[$c, $b] = act($sam, '/returns/save.php', ['order' => $w['so2'], 'lines' => $lines([['line' => $q2['id'], 'qty' => 1, 'reason' => 'nonsense']]), 'location' => $w['wh']]);
ok($c === 422 && isset(fields($b)['lines.' . $q2['id'] . '.reason']), 'a reason that is no code at all: a field error on the line');
[$c, $b] = act($sam, '/returns/save.php', ['order' => $w['so2'], 'lines' => $lines([['line' => $q2['id'], 'qty' => 1, 'reason' => 'comfort'], ['line' => $q2['id'], 'qty' => 1, 'reason' => 'damaged']]), 'location' => $w['wh']]);
ok($c === 422 && str_contains(msg($b), 'already on this return'), 'the same order line twice on one return: "already on this return"');
[$c, $b] = act($sam, '/returns/save.php', ['order' => $w['so1'], 'lines' => $lines([['line' => $q1['id'], 'qty' => 1, 'reason' => 'comfort']]), 'location' => $w['wh']]);
ok($c === 422 && str_contains(msg($b), 'Line 1 shipped 1 and 0 may still come back'), 'a second return on the same line while the first is open: the trigger counts the pending quantity');
[$c, $b] = act($sam, '/returns/save.php', ['order' => $w['so2'], 'lines' => '[]', 'location' => $w['wh']]);
ok($c === 422 && msg($b) === 'Choose at least one line to return.', 'no lines: "Choose at least one line to return."');
[$c, $b] = act($sam, '/returns/save.php', ['order' => $w['so2'], 'lines' => $lines([['line' => $q2['id'], 'qty' => 1, 'reason' => 'comfort']])]);
ok($c === 422 && isset(fields($b)['location']), 'a restock with no place to come back to: "Say where it comes back to." on the location field');
[$c, $b] = act($vera, '/returns/save.php', ['order' => $w['so1'], 'lines' => $lines([['line' => $q1['id'], 'qty' => 1, 'reason' => 'comfort']]), 'location' => $w['wh']]);
ok($c === 403, 'Vera (a Viewer) may not request a return');
[$c, $b] = act($sam, '/returns/save.php', ['order' => 999999, 'lines' => $lines([['line' => $q1['id'], 'qty' => 1, 'reason' => 'comfort']])]);
ok($c === 404, 'an order that is not there: 404');

echo "3. Change the return and its lines\n";
$since = last_activity_id();
$when = date('Y-m-d', strtotime('+3 days'));
[$c, $b] = act($sam, '/returns/save.php', ['return' => $ra1, 'method' => 'drop_off', 'scheduled_on' => $when]);
$r1 = return_row($ra1);
ok($c === 200 && $r1['method'] === 'drop_off' && $r1['scheduled_on'] === $when && count(return_lines_of($ra1)) === 1 && $r1['notes'] === 'SMOKE S8-RA1', 'return_update changes the method and the date and keeps the lines and the notes');
$lg = last_log('return.update', $since);
ok($lg !== null && after_of($lg)['changed'] === ['method', 'scheduled_on'] && json_decode($lg['before'], true)['method'] === 'pickup', 'logged return.update with the fields changed, before and after');
$rl1 = (int) return_lines_of($ra1)[0]['id'];
[$c, $b] = act($sam, '/returns/lines/save.php', ['return_line' => $rl1, 'condition_note' => 'wrapped, unopened']);
ok($c === 200 && one('SELECT condition_note FROM return_lines WHERE id = :i', ['i' => $rl1]) === 'wrapped, unopened' && (int) one('SELECT qty FROM return_lines WHERE id = :i', ['i' => $rl1]) === 1, 'return_line_add with return_line changes a line: only the note, the rest as it was');
[$c, $b] = act($sam, '/returns/lines/save.php', ['return' => $ra1, 'line' => $q1['id'], 'qty' => 1, 'reason' => 'comfort']);
ok($c === 422 && str_contains(msg($b), 'already on this return') && isset(fields($b)['line']), 'adding the line that is on the return: "already on this return — change its quantity"');
[$c, $b] = act($sam, '/returns/lines/save.php', ['return' => $ra1, 'line' => $k1['id'], 'qty' => 1, 'reason' => 'damaged', 'disposition' => 'return_to_supplier', 'condition_note' => 'scuffed']);
$rl2 = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $rl2 > 0 && count(return_lines_of($ra1)) === 2 && after_of(last_log('return.line_add'))['sku'] === 'SMOKE-NW-CR-K', 'return_line_add puts the drop-ship King on the return (damaged, return to the supplier)');
[$c, $b] = act($sam, '/returns/lines/remove.php', ['return_line' => $rl2]);
ok($c === 200 && count(return_lines_of($ra1)) === 1 && after_of(last_log('return.line_remove'))['sku'] === 'SMOKE-NW-CR-K', 'return_line_remove takes it off again, logged');
[$c, $b] = act($sam, '/returns/lines/save.php', ['return' => $ra1, 'line' => $q2['id'], 'qty' => 1, 'reason' => 'comfort']);
ok($c === 422 && str_contains(msg($b), 'not on the order'), 'a line of another order: "not on the order"');

echo "4. Lists and the page\n";
[$c, $d] = screen($sam, '/returns/');
ok($c === 200 && in_array($ra1, array_column($d['returns'], 'return_id'), true) && $d['returns'][0]['order_number'] !== '' && !isset($d['returns'][0]['email']), 'the list holds the return with its order and customer name — no contact details');
[$c, $d] = screen($sam, '/returns/?status=approved');
ok($c === 200 && !in_array($ra1, array_column($d['returns'], 'return_id'), true), 'filtered by status approved it is not there');
[$c, $d] = screen($sam, '/returns/?awaiting_disposition=1');
ok($c === 200 && $d['returns'] === [], 'awaiting disposition: empty until a return is received (or an approved one passes its date)');
$r = req('GET', "/returns/$ra1", ['jar' => $nora]);
ok($r['code'] === 200 && str_contains($r['body'], 'id="return-view-approve-btn"') && str_contains($r['body'], 'id="return-view-deny-btn"') && !str_contains($r['body'], 'return-view-receive-btn') && !str_contains($r['body'], 'return-view-close-btn') && str_contains($r['body'], "id=\"return-line-$rl1\""), 'the view shows the line and, for the Buyer on a requested return, Approve and Deny — not Receive or Close');
$r = req('GET', "/returns/$ra1", ['jar' => $sam]);
ok(!str_contains($r['body'], 'return-view-approve-btn') && str_contains($r['body'], 'return-view-edit-btn'), 'Sam sees Edit and no Approve');
$r = req('GET', "/returns/$ra1", ['jar' => $vera]);
ok($r['code'] === 200 && !str_contains($r['body'], 'return-view-edit-btn') && !str_contains($r['body'], 'return-view-approve-btn') && !str_contains($r['body'], 'notes-form'), 'a Viewer reads the return and changes nothing');
[$c, $d] = screen($vera, "/returns/$ra1");
ok($c === 200 && $d['return']['lines'][0]['sku'] === 'SMOKE-NW-CR-Q' && !isset($d['return']['customer_email']), 'the JSON of the return (lines, reason, disposition) — no contact details');

echo "5. Approve, deny\n";
$since = last_activity_id(); $nid = last_notification_id();
[$c, $b] = act($sam, '/returns/approve.php', ['return' => $ra1]);
ok($c === 403, 'Sam approving: 403 (returns.write)');
[$c, $b] = act($nora, '/returns/approve.php', ['return' => $ra1]);
$r1 = return_row($ra1);
ok($c === 200 && $r1['status'] === 'approved' && (int) $r1['approved_by'] === 40 && $r1['approved_at'] !== null, 'Nora approves: approved by her');
$n = notifications_for(41, 'return', $nid);
ok(count($n) === 1 && str_contains($n[0]['title'], 'approved —') && str_contains($n[0]['title'], 'Drop-off'), 'Sam, the requester, is told: "approved — Drop-off on …"');
ok(after_of(last_log('return.approve', $since))['status'] === 'approved', 'logged return.approve');
[$c, $b] = act($nora, '/returns/approve.php', ['return' => $ra1]);
ok($c === 422 && str_contains(msg($b), 'a requested return is approved'), 'approving twice: "a requested return is approved"');
// a second return, denied
[$c, $b] = act($sam, '/returns/save.php', ['order' => $w['so2'], 'lines' => $lines([['line' => $q2['id'], 'qty' => 1, 'reason' => 'changed_mind', 'disposition' => 'dispose']]), 'notes' => 'SMOKE S8-RA2']);
$ra2 = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $ra2 > 0 && one('SELECT status FROM return_authorizations WHERE id = :i', ['i' => $ra2]) === 'requested', 'a second return (SO-2, changed mind, dispose — no place needed to come back to) is requested');
[$c, $b] = act($nora, '/returns/deny.php', ['return' => $ra2]);
ok($c === 422 && isset(fields($b)['reason']), 'denying without a reason: a field error');
[$c, $b] = act($nora, '/returns/deny.php', ['return' => $ra2, 'reason' => 'Past the trial period']);
$r2 = return_row($ra2);
ok($c === 200 && $r2['status'] === 'denied' && $r2['deny_reason'] === 'Past the trial period' && (int) $r2['denied_by'] === 40, 'denied with its reason');
$n = q("SELECT * FROM notifications WHERE member_id = 41 AND kind = 'return' AND record_id = :r AND title LIKE '%denied%'", ['r' => $ra2]);
ok(count($n) === 1 && $n[0]['body'] === 'Past the trial period', 'the requester is told with the reason in the body');
$r = req('GET', "/returns/$ra2", ['jar' => $sam]);
ok(str_contains($r['body'], 'Past the trial period') && str_contains($r['body'], 'id="return-view-status"'), 'the page shows the reason');
$rl3 = (int) return_lines_of($ra2)[0]['id'];
[$c, $b] = act($sam, '/returns/lines/save.php', ['return_line' => $rl3, 'qty' => 1, 'condition_note' => 'x']);
ok($c === 422 && str_contains(msg($b), 'The lines of a return change while it is requested or approved (it is denied)'), 'return_line_add (changing a line) on a denied return: the trigger\'s words');
[$c, $b] = act($sam, '/returns/lines/remove.php', ['return_line' => $rl3]);
ok($c === 422 && str_contains(msg($b), 'The lines of a return change while it is requested or approved (it is denied)') && count(return_lines_of($ra2)) === 1, 'return_line_remove on a denied return: the same words, the line stays');
[$c, $b] = act($sam, '/returns/save.php', ['return' => $ra2, 'method' => 'pickup']);
ok($c === 422 && str_contains(msg($b), 'while it is requested or approved'), 'return_update on a denied return: refused in the same words');

echo "6. Disposition\n";
$since = last_activity_id();
[$c, $b] = act($nora, '/returns/disposition.php', ['return_line' => $rl1, 'disposition' => 'floor_model', 'location' => $w['sr']]);
$l = return_lines_of($ra1)[0];
ok($c === 200 && $l['disposition'] === 'floor_model' && (int) $l['location_id'] === $w['sr'], 'disposition set to floor_model on the line with the showroom');
$lg = last_log('return.disposition', $since); $a = after_of($lg);
ok($lg !== null && (int) $lg['sales_order_id'] === $w['so1'] && $a['sku'] === 'SMOKE-NW-CR-Q' && $a['disposition'] === 'floor_model' && json_decode($lg['before'], true)['disposition'] === 'restock' && (int) $a['location_id'] === $w['sr'], 'logged return.disposition with before and after');
[$c, $b] = act($nora, '/returns/disposition.php', ['return_line' => $rl1, 'disposition' => 'dispose']);
ok($c === 200 && return_lines_of($ra1)[0]['disposition'] === 'dispose', 'dispose needs no location');
[$c, $b] = act($sam, '/returns/disposition.php', ['return_line' => $rl1, 'disposition' => 'restock', 'location' => $w['wh']]);
ok($c === 403, 'Sam setting a disposition: 403 (returns.write)');
[$c, $b] = act($nora, '/returns/disposition.php', ['return_line' => $rl1, 'disposition' => 'fling']);
ok($c === 422 && isset(fields($b)['disposition']), 'a disposition that is none: a field error');
[$c, $b] = act($nora, '/returns/disposition.php', ['return_line' => $rl1, 'disposition' => 'floor_model', 'location' => $w['sr']]);
ok($c === 200 && return_lines_of($ra1)[0]['disposition'] === 'floor_model', 'and back to a floor model at the showroom, ready to be received');
[$c, $b] = act($nora, '/returns/disposition.php', ['return_line' => 999999, 'disposition' => 'dispose']);
ok($c === 404, 'a line that is not there: 404');
finish();
