<?php
/**
 * Proof: the kernel's hand-off under the shell, the mirror (capability + roles), the badges, Omar refused, the agent on the action-token
 * path, revocation and sign-out (sso-shell.md "The receiver", "Every request", "Proof: sso"). Run through tests/phase2/run.sh.
 */
require __DIR__ . '/lib.php';
$L = 'https://app.example.invalid/launcher?app=inventory';
$refusedWith = fn (int $since): ?string => (($r = activity('member.sign_on.refused', $since)) ? (json_decode((string) end($r)['after'], true)['reason'] ?? null) : null);

echo "1. A hand-off opens a session once\n";
$sinceLog = last_activity_id();
$url = handoff(40);
$jn = jar();
$r = req('GET', $url, ['jar' => $jn]);
ok($r['code'] === 302 && $r['location'] === '/', "the hand-off answers 302 to / ({$r['code']} {$r['location']})");
$m = q('SELECT display_name, capability, status, roles FROM members WHERE id = 40')[0] ?? null;
ok($m && $m['display_name'] === 'SMOKE Nora' && $m['capability'] === 'write' && $m['status'] === 'active', 'the mirror row follows the claims (name, capability write, active)');
ok($m && $m['roles'] === '{buyer,user,warehouse}', 'and claims.roles landed in members.roles ({buyer,user,warehouse})');
$home = page($jn, '/');
ok($home['code'] === 200 && str_contains($home['body'], 'id="home-header"') && badge_of($jn) === 'Buyer', 'the home answers 200 with the role badge "Buyer"');
ok(str_contains($home['body'], 'id="shell-sidebar"') && str_contains($home['body'], 'id="shell-tabbar"') && str_contains($home['body'], 'id="assistant-bar"') && str_contains($home['body'], 'id="bell"') && str_contains($home['body'], 'id="header-business-name"'), 'the shell is whole: the sidebar, the tab bar, the command bar, the bell, the business name');
ok(str_contains($home['body'], 'id="page-content"') && str_contains($home['body'], 'data-screen="home"') && str_contains($home['body'], 'id="csrf-token-meta"'), '#page-content is stamped data-screen="home"; the CSRF meta is there');
ok(count(activity('member.sign_on', $sinceLog)) === 1 && str_contains((string) activity('member.sign_on', $sinceLog)[0]['after'], '"roles"'), 'member.sign_on is logged with capability and roles');
$r = req('GET', $url, ['jar' => jar()]);
ok($r['code'] === 403 && $refusedWith($sinceLog) === 'replay', "the same URL again: 403, reason logged as replay ({$r['code']})");
ok(!preg_match('/replay|nonce|signature|token|audience/i', preg_replace('/sign-on link|launcher/i', '', $r['body'])), 'and the page never says which check failed');
$r = req('GET', handoff(40, ['app' => 'hr']), ['jar' => jar()]);
ok($r['code'] === 403 && $refusedWith($sinceLog) === 'token', 'a token made for app_key hr: 403 (audience)');
$r = req('GET', handoff(40, ['ttl' => -5]), ['jar' => jar()]);
ok($r['code'] === 403, 'an expired token: 403');
$r = req('GET', handoff(40, ['key' => str_repeat('ab', 32)]), ['jar' => jar()]);
ok($r['code'] === 403, 'a token signed with another key: 403');
$u = handoff(40);
$r = req('GET', preg_replace('/claims=([^&.]+)/', 'claims=x$1', $u), ['jar' => jar()]);
ok($r['code'] === 403 && $refusedWith($sinceLog) === 'claims', 'tampered claims: 403 (claims)');
$r = req('GET', handoff(41, ['claims' => fixture()['claims']['40'] + ['member_id' => 40]]), ['jar' => jar()]);
ok($r['code'] === 403, 'claims of another member beside the token: 403');
$r = req('GET', handoff(40, ['claims' => ['status' => 'suspended'] + fixture()['claims']['40']]), ['jar' => jar()]);
ok($r['code'] === 403 && $refusedWith($sinceLog) === 'status', 'a suspended member: 403 (status)');
$r = req('GET', handoff(40, ['claims' => ['capability' => null] + fixture()['claims']['40']]), ['jar' => jar()]);
ok($r['code'] === 403 && $refusedWith($sinceLog) === 'capability', 'no capability on this application: 403 (capability)');
$r = req('GET', handoff(46), ['jar' => jar()]);
ok($r['code'] === 403 && $refusedWith($sinceLog) === 'capability', 'Omar — in the directory with no grant here — is refused (capability)');
$r = req('GET', handoff(999), ['jar' => jar()]);
ok($r['code'] === 403, 'an unknown member (no claims at all): 403');
ok(req('GET', '/sso', ['jar' => jar()])['code'] === 403, '/sso with no token: the one refusal page');
ok(q('SELECT roles FROM members WHERE id = 40')[0]['roles'] === '{buyer,user,warehouse}', 'a refused hand-off changed nothing in the mirror');

echo "2. Every admitted fixture member lands on the home with their badge\n";
$badges = [1 => 'Super-admin', 40 => 'Buyer', 41 => 'Sales', 42 => 'Warehouse', 43 => 'Viewer', 44 => 'Viewer'];
$wrong = [];
foreach ($badges as $id => $want) { [$j, $r] = sign_on($id); $b = badge_of($j); if ($r['code'] !== 302 || $b !== $want) { $wrong[] = "$id: {$r['code']} '$b'"; } }
ok($wrong === [], 'six people sign on and wear Super-admin / Buyer / Sales / Warehouse / Viewer / Viewer' . ($wrong ? ': ' . implode('; ', $wrong) : ''));
[$jv, ] = sign_on(43);
$h = page($jv, '/')['body'];
ok(!str_contains($h, 'id="nav-receipt-list"') && !str_contains($h, 'id="nav-match-queue"') && !str_contains($h, 'id="nav-watch-list"') && !str_contains($h, 'id="nav-group-admin"') && str_contains($h, 'id="nav-product-list"') && str_contains($h, 'id="nav-my-settings"'), 'Vera (Viewer): no Receive, no Match queue, no Watches, no Admin group; Products and Me are there');
ok(!str_contains($h, 'id="nav-group-reports"'), 'and no Reports group (reports.read is not the Viewer\'s)');
$h = page($jn, '/')['body'];
ok(str_contains($h, 'id="nav-receipt-list"') && str_contains($h, 'id="nav-match-queue"') && str_contains($h, 'id="nav-source-template-list"') && str_contains($h, 'id="nav-report-list"') && !str_contains($h, 'id="nav-group-admin"'), 'Nora (Buyer): Receive, Match queue, Templates and Reports, no Admin group');
[$ja, ] = sign_on(1);
$h = page($ja, '/')['body'];
ok(str_contains($h, 'id="nav-group-admin"') && str_contains($h, 'id="nav-admin-settings"') && str_contains($h, 'id="nav-feed-key-list"') && str_contains($h, 'id="nav-agent-list"') && str_contains($h, 'id="nav-connection-list"'), 'the owner\'s menu holds the Admin group (settings, feed keys, agents, connections)');
ok(str_contains($h, 'id="header-business-name">Inventory<'), 'the header shows the application\'s name while inv_settings.business_name is empty');
pdo()->exec("UPDATE inv_settings SET business_name = 'SMOKE Mattress Co' WHERE id = 1");
ok(str_contains(page($ja, '/')['body'], 'id="header-business-name">SMOKE Mattress Co<'), 'and the business\'s name once the setting is there');
pdo()->exec("UPDATE inv_settings SET business_name = NULL WHERE id = 1");

echo "3. The agent on the action-token path; an unknown id refused\n";
ok(q('SELECT capability, roles FROM members WHERE id = 45')[0] === ['capability' => 'write', 'roles' => '{user}'], 'the feed admitted the expert (45, access[] user)');
$since = last_activity_id();
$tok = run_token(45, 77);
kernel_state(function ($s) { $s['facts']['77'] = ['valid' => true, 'is_agent' => true, 'member_id' => 45, 'run_id' => 77, 'request_id' => 'req-run-77', 'trigger' => 'chat', 'endpoints' => [['name' => 'Records MCP']]]; return $s; });
$r = req('GET', '/trail', ['headers' => as_agent($tok)]);
ok($r['code'] === 200 && isset(json_decode($r['body'], true)['data']['rows']), 'the expert with a run token and the relay reaches a JSON screen (the trail, 200)');
ok(req('GET', '/', ['headers' => as_agent($tok)])['code'] === 403, 'but not the home (require_human): 403');
ok(req('GET', '/settings/tokens/', ['headers' => as_agent($tok)])['code'] === 403 && req('GET', '/notifications', ['headers' => as_agent($tok)])['code'] === 403, 'nor Tokens or Notifications: 403');
ok(req('POST', '/assistant/ask.php', ['headers' => as_agent($tok), 'form' => ['utterance' => 'hi']])['code'] === 403, 'nor the command bar: 403');
ok(req('POST', '/settings/tokens/mint.php', ['headers' => as_agent($tok), 'form' => ['label' => 'agent']])['code'] === 403, 'nor mint a person\'s token: 403');
$r = req('GET', '/trail', ['headers' => ['Accept: application/json', 'X-Action-Token: ' . person_token(4242)]]);
ok($r['code'] === 401 && (int) one('SELECT count(*) FROM members WHERE id = 4242') === 0 && count(activity('member.refused', $since)) === 1, 'an action token for an id with no mirror row: 401, NO row created, member.refused logged');
$tok2 = run_token(46, 78);
$r = req('GET', '/trail', ['headers' => as_agent($tok2)]);
ok($r['code'] === 401 && q('SELECT capability FROM members WHERE id = 46')[0]['capability'] === null, 'a run token for Omar (a person, no grant): 401, no admission');
kernel_state(function ($s) { unset($s['facts']); return $s; });

echo "4. Roles from the claims — and without them, the capability\n";
[$j1, ] = sign_on(40, ['claims' => ['roles' => ['user']] + fixture()['claims']['40']]);
ok(q('SELECT roles FROM members WHERE id = 40')[0]['roles'] === '{user}' && badge_of($j1) === 'Sales', 'a hand-off naming only user: members.roles = {user}, badge "Sales"');
ok(page($j1, '/receipts/')['code'] === 403 && page($j1, '/orders/')['code'] === 200, 'and the doors follow at once: Receive 403, Orders 200');
[$j2, ] = sign_on(40, ['claims' => ['roles' => ['buyer', 'user', 'warehouse', 'nonsense']] + fixture()['claims']['40']]);
ok(q('SELECT roles FROM members WHERE id = 40')[0]['roles'] === '{buyer,user,warehouse}', 'a role inv_roles does not know is dropped ({buyer,user,warehouse} from buyer,user,warehouse,nonsense)');
$c = fixture()['claims']['1']; unset($c['roles']);
[$j3, ] = sign_on(1, ['claims' => $c]);
ok(in_array(q('SELECT roles FROM members WHERE id = 1')[0]['roles'], ['{}', '{admin}'], true), 'a kernel from before roles sends none: the mirror keeps what it had');
ok(page($j3, '/admin/settings')['code'] === 200 && badge_of($j3) === 'Super-admin', 'the super-admin holds every right (the admin settings 200) and wears the Super-admin badge');
$c = fixture()['claims']['41']; $c['roles'] = []; $c['capability'] = 'admin';
[$j4, ] = sign_on(41, ['claims' => $c]);
ok(q('SELECT roles FROM members WHERE id = 41')[0]['roles'] === '{}' && page($j4, '/admin/settings')['code'] === 200 && badge_of($j4) === 'Inventory admin', 'roles {} with capability admin: every right (admin settings 200), badge "Inventory admin"');
$c['capability'] = 'write';
[$j5, ] = sign_on(41, ['claims' => $c]);
ok(page($j5, '/admin/settings')['code'] === 403 && page($j5, '/orders/')['code'] === 200 && badge_of($j5) === 'Sales', 'roles {} with capability write: Sales (admin settings 403, Orders 200)');
$c['capability'] = 'read';
[$j6, ] = sign_on(41, ['claims' => $c]);
ok(page($j6, '/receipts/')['code'] === 403 && page($j6, '/products/')['code'] === 200 && badge_of($j6) === 'Viewer', 'roles {} with capability read: a Viewer (Receive 403, Products 200)');
sign_on(41);   // restore Sam as the fixture has him

echo "5. Revocation — the next request lands on the launcher\n";
[$jr, ] = sign_on(41);
ok(page($jr, '/')['code'] === 200, 'Sam is signed in');
kernel_state(fn ($s) => $s + ['incremental' => incr(['access' => [['member_id' => 41, 'role' => null, 'roles' => [], 'capability' => null, 'scopes' => []]]], '2026-01-01T00:01:00.000000Z')]);
$out = sync();
ok(str_contains($out, '1 holdings'), "the sync applies Sam's access row with no capability: $out");
$r = page($jr, '/');
ok($r['code'] === 302 && $r['location'] === $L, 'his next request: 302 to the launcher with ?app=inventory');
ok(q("SELECT ended_by FROM member_sessions WHERE member_id = 41 ORDER BY created_at DESC LIMIT 1")[0]['ended_by'] === 'directory', "member_sessions shows ended_by = 'directory'");
ok(q('SELECT capability, roles FROM members WHERE id = 41')[0] === ['capability' => null, 'roles' => '{}'], 'the mirror holds no capability and no roles for him');
$r = req('GET', handoff(41, ['claims' => ['capability' => null, 'roles' => []] + fixture()['claims']['41']]), ['jar' => jar()]);
ok($r['code'] === 403 && $refusedWith($sinceLog) === 'capability', 'and a new hand-off for him, with the claims the kernel would now send, is refused');
kernel_state(function ($s) { $s['incremental'] = incr(['access' => [['member_id' => 41, 'role' => 'user', 'roles' => ['user'], 'capability' => 'write', 'scopes' => []]]], '2026-01-01T00:02:00.000000Z'); return $s; });
sync();
ok(q('SELECT capability, roles FROM members WHERE id = 41')[0] === ['capability' => 'write', 'roles' => '{user}'], 'granted again by the feed: capability write, roles {user}');
kernel_state(function ($s) { unset($s['incremental']); return $s; });

echo "6. Sign-out\n";
$notice = fn (int $m, string $app = APP, ?int $issued = null): string => ($p = $m . '.' . ($issued ?? time()) . '.' . $app) . '.' . hash_hmac('sha256', 'sso-logout:' . $p, need('ACTION_TOKEN_KEY'));
[$jk, ] = sign_on(41);
[$jk2, ] = sign_on(41);
ok(page($jk, '/')['code'] === 200 && page($jk2, '/')['code'] === 200, 'Sam holds two sessions');
$since = last_activity_id();
$r = req('POST', '/sso/logout', ['form' => ['notice' => $notice(41)]]);
ok($r['code'] === 204 && $r['body'] === '', 'the kernel\'s sign-out notice: 204, no body');
ok(page($jk, '/')['code'] === 302 && page($jk2, '/')['code'] === 302, 'every session of his ends: the next requests go to the launcher');
ok(q("SELECT DISTINCT ended_by FROM member_sessions WHERE member_id = 41 AND ended_at IS NOT NULL AND ended_by = 'kernel'") !== [] && count(activity('member.sign_out', $since)) === 1, "ended_by = 'kernel' and member.sign_out logged once");
[$jk3, ] = sign_on(41);
$r = req('POST', '/sso/logout', ['form' => ['notice' => 'garbage']]);
ok($r['code'] === 204 && count(activity('member.sign_out.refused', $since)) === 1, 'an invalid notice: 204 and member.sign_out.refused logged');
$r = req('POST', '/sso/logout', ['form' => ['notice' => $notice(41, 'hr')]]);
ok($r['code'] === 204 && page($jk3, '/')['code'] === 200, 'a notice made for another application: 204 and changes nothing');
$r = req('POST', '/sso/logout', ['form' => ['notice' => $notice(41, APP, time() - 600)]]);
ok($r['code'] === 204 && page($jk3, '/')['code'] === 200, 'a stale notice (10 minutes old): 204 and changes nothing');
$r = req('POST', '/sso/logout', ['raw' => json_encode(['notice' => $notice(41)]), 'headers' => ['Content-Type: application/json']]);
ok($r['code'] === 204 && page($jk3, '/')['code'] === 302, 'the notice as JSON works too');
ok(req('GET', '/sso/logout')['code'] === 405, 'GET /sso/logout: 405');
[$jo, ] = sign_on(40);
$r = req('POST', '/logout.php', ['jar' => $jo, 'form' => []]);
ok($r['code'] === 403 && page($jo, '/')['code'] === 200, 'own sign-out without the CSRF token: 403, still signed in');
$r = req('POST', '/logout.php', ['jar' => $jo, 'form' => ['csrf_token' => csrf_of(page($jo, '/')['body'])]]);
ok($r['code'] === 302 && $r['location'] === 'https://app.example.invalid/launcher' && page($jo, '/')['code'] === 302, 'own sign-out (POST + CSRF): 302 to the launcher, this session ended');
ok(page($jo, '/')['location'] === $L, 'and a signed-out visitor is sent to the launcher with ?app=inventory');
ok(req('GET', '/login.php')['location'] === $L, '/login.php is only a redirect to the launcher (no form, no password)');
finish();
