<?php /** One price-sheet row (`supplier-item-row-{id}`), edited in place (Pattern C). Data: r, mayWrite, seesCost, here */ $id = $r['supplier_item_id']; $fid = 'supplier-item-row-' . $id . '-form'; ?>
<tr id="supplier-item-row-<?= $id ?>" class="<?= $r['active'] ? '' : 'text-muted' ?>">
    <td><?php if ($mayWrite): ?><input form="<?= $fid ?>" type="text" name="supplier_sku" value="<?= e((string) $r['supplier_sku']) ?>" class="form-control btn-touch" style="min-width:7rem" aria-label="Supplier SKU" id="supplier-item-row-<?= $id ?>-supplier_sku"><?php else: ?><code><?= e((string) $r['supplier_sku']) ?></code><?php endif; ?></td>
    <td><?= hx_link(with_back('/variants/' . $r['variant_id'], $here), e($r['sku']), 'fw-semibold') ?><div class="fs-11 text-muted"><?= e((string) $r['product_name']) ?><?= $r['size_name'] ? ' · ' . e($r['size_name']) : '' ?></div></td>
    <td class="text-end"><?php if ($mayWrite && $seesCost): ?><input form="<?= $fid ?>" type="text" name="cost" value="<?= e((string) $r['cost']) ?>" class="form-control btn-touch text-end" style="width:6rem" inputmode="decimal" aria-label="Cost" id="supplier-item-row-<?= $id ?>-cost"><?php else: ?><?= cost_cell_src($r['cost'], $seesCost) ?><?php endif; ?></td>
    <td class="text-end"><?php if ($mayWrite): ?><input form="<?= $fid ?>" type="number" name="lead_time_days" value="<?= e((string) $r['lead_time_days']) ?>" min="0" class="form-control btn-touch text-end" style="width:5rem" aria-label="Lead time" id="supplier-item-row-<?= $id ?>-lead"><?php else: ?><?= $r['lead_time_days'] ?? '' ?><?php endif; ?></td>
    <td class="text-end"><?php if ($mayWrite): ?><input form="<?= $fid ?>" type="number" name="moq" value="<?= (int) $r['moq'] ?>" min="1" class="form-control btn-touch text-end" style="width:5rem" aria-label="MOQ" id="supplier-item-row-<?= $id ?>-moq"><?php else: ?><?= (int) $r['moq'] ?><?php endif; ?></td>
    <td><?= $r['active'] ? '<span class="badge bg-soft-success text-success">active</span>' : '<span class="badge bg-soft-dark text-dark">inactive</span>' ?></td>
    <td class="d-none d-md-table-cell text-nowrap"><?= e(ago($r['last_seen_at'])) ?></td>
    <td class="d-none d-md-table-cell"><?= $r['source_id'] !== null ? hx_link(with_back('/sources/' . $r['source_id'], $here), e((string) ($r['source_name'] ?? 'source #' . $r['source_id']))) : '<span class="text-muted">typed</span>' ?></td>
    <td class="text-end text-nowrap"><?php if ($mayWrite): ?>
        <form method="post" action="/supplier-items/save.php" hx-post="/supplier-items/save.php" hx-target="closest tr" hx-swap="outerHTML" id="<?= $fid ?>" class="d-inline"><?= csrf_field() ?><input type="hidden" name="supplier_item" value="<?= $id ?>"><button type="submit" class="btn btn-light btn-touch" id="supplier-item-row-<?= $id ?>-save">Save</button></form>
        <form method="post" action="/supplier-items/remove.php" hx-post="/supplier-items/remove.php" hx-target="#flash" hx-confirm="Remove <?= e($r['sku']) ?> from <?= e($r['supplier_name']) ?>'s price sheet?" class="d-inline"><?= csrf_field() ?><input type="hidden" name="supplier_item" value="<?= $id ?>"><button type="submit" class="btn btn-light btn-touch" id="supplier-item-row-<?= $id ?>-remove" aria-label="Remove"><i class="feather-x"></i></button></form>
    <?php endif; ?></td>
</tr>
