<?php
/** Minting (feed.md "Proof" ≈ 22): the copy-once box, only the hash stored, nothing of the key in any log row, the limits the settings give, every refusal in words, who may, the list and the usage page. */
require __DIR__ . '/lib.php';
$w = feed_world();
$owner = $w['owner'];
[$jar] = sign_on(1);
$csrf = page_csrf($jar);
$since = last_activity_id();
$run = substr(md5((string) microtime(true)), 0, 6);

echo "1. The copy-once box\n";
$r = req('POST', '/admin/feed-keys/mint.php', ['jar' => $jar, 'form' => ['label' => "KT Site $run", 'consumer_kind' => 'website', 'csrf_token' => $csrf]]);
ok($r['code'] === 302 && preg_match('~^/admin/feed-keys/\?notice=minted#feed-key-row-(\d+)$~', $r['location'], $m) === 1, 'the form post lands on the keys page at the new row with a notice (302)');
$kid = (int) ($m[1] ?? 0);
$page = req('GET', $r['location'], ['jar' => $jar]);
preg_match('~id="feed-key-minted-value"[^>]*value="(feed_[0-9a-f]{48})"~', $page['body'], $mm);
$raw = $mm[1] ?? '';
ok($page['code'] === 200 && $raw !== '' && str_contains($page['body'], 'id="feed-key-minted"') && str_contains($page['body'], 'id="feed-key-minted-copy-btn"') && str_contains($page['body'], 'Shown once — store it now; it cannot be shown again.'), 'the next page shows the key once, `feed_` + 48 hex, in a read-only field with a Copy button and the warning');
$again = req('GET', '/admin/feed-keys/', ['jar' => $jar]);
ok($again['code'] === 200 && !str_contains($again['body'], 'id="feed-key-minted"') && !str_contains($again['body'], $raw), 'a reload does not show the key again — it is nowhere on the page');
$row = $kid ? key_row($kid) : [];
ok(($row['token_hash'] ?? '') === hash('sha256', $raw) && ($row['token_hash'] ?? '') !== $raw && ($row['scope'] ?? '') === 'feed' && (int) ($row['member_id'] ?? 0) === 1, 'the row stores only the sha256 of the key (scope feed, minted by the admin)');
$hits = (int) one("SELECT count(*) FROM activity_log WHERE activity_log::text LIKE :a OR activity_log::text LIKE :b", ['a' => '%' . substr($raw, 5) . '%', 'b' => '%' . ($row['token_hash'] ?? 'x') . '%']);
ok($hits === 0, 'neither the key nor its hash is in any activity_log row (every column of every row searched)');
ok((int) $row['rate_per_minute'] === 60 && (int) $row['rate_per_day'] === 10000 && $row['expires_at'] === null && $row['consumer_kind'] === 'website' && $row['price_list_id'] === null, 'the limits the trigger filled from the settings: 60 a minute, 10,000 a day; no expiry; a website key');
$log = last_log('feed.key_mint', $since);
$a = after_of($log);
ok($log !== null && (int) $log['token_id'] === $kid && $log['entity_type'] === 'feed_key' && (int) $log['entity_id'] === $kid && $a['label'] === "KT Site $run" && $a['consumer_kind'] === 'website' && (int) $a['rate_per_minute'] === 60 && $log['source'] === 'web', 'feed.key_mint is logged with token_id = the key, the label and the facts');
ok($log !== null && !str_contains((string) $log['after'], 'feed_') && !array_key_exists('token_hash', $a) && !array_key_exists('key', $a), 'the log row carries no key, no hash');

echo "2. Refusals\n";
[$c, $b] = act($owner, '/admin/feed-keys/mint.php', ['label' => "KT P $run", 'consumer_kind' => 'partner']);
ok($c === 422 && isset(fields($b)['price_list']), 'a partner key with no price list: 422 naming price_list');
[$c, $b] = act($owner, '/admin/feed-keys/mint.php', ['label' => "KT W $run", 'consumer_kind' => 'website', 'price_list' => $w['dealer20']]);
ok($c === 422 && (fields($b)['price_list'] ?? '') === "A price list goes on a partner's key.", 'a website key with a price list: 422 "A price list goes on a partner\'s key."');
[$c, $b] = act($owner, '/admin/feed-keys/mint.php', ['label' => "KT I $run", 'consumer_kind' => 'partner', 'price_list' => $w['inactive5']]);
ok($c === 422 && (fields($b)['price_list'] ?? '') === 'That price list is inactive.', 'an inactive price list: 422 "That price list is inactive."');
[$c, $b] = act($owner, '/admin/feed-keys/mint.php', ['label' => "KT L $run", 'rate_per_minute' => '0', 'rate_per_day' => '99999999']);
ok($c === 422 && isset(fields($b)['rate_per_minute']) && isset(fields($b)['rate_per_day']), 'a limit of 0 and one over the ceiling: a field error each (inv_int\'s bounds)');
[$c, $b] = act($owner, '/admin/feed-keys/mint.php', ['label' => "KT E $run", 'expires_at' => date('Y-m-d', strtotime('-1 day'))]);
ok($c === 422 && isset(fields($b)['expires_at']), 'an expiry of yesterday: 422');
[$c, $b] = act($owner, '/admin/feed-keys/mint.php', ['label' => '', 'consumer_kind' => 'robot']);
ok($c === 422 && isset(fields($b)['label']) && isset(fields($b)['consumer_kind']), 'no label and an unknown kind: a field error each');
[$c, $b, $rawE, $idE] = mint_key("KT Exp $run", ['expires_at' => date('Y-m-d', strtotime('+3 days')), 'rate_per_minute' => '5']);
$expiry = $idE ? (string) key_row($idE)['expires_at'] : '';
ok($c === 200 && $idE > 0 && strtotime($expiry) > time() + 2 * 86400 && strtotime($expiry) < time() + 4 * 86400 && (int) key_row($idE)['rate_per_minute'] === 5, 'an expiry three days out is stored as that day\'s end; a limit given is kept');
[$c, $b] = act($w['nora'], '/admin/feed-keys/mint.php', ['label' => "KT Nora $run"]);
ok($c === 403 && str_contains(msg($b), "feed's keys"), 'Nora (the Buyer): 403 in words');
[$c, $b] = act($w['vera'], '/admin/feed-keys/mint.php', ['label' => "KT Vera $run"]);
ok($c === 403, 'Vera (a viewer): 403');
ok(req('GET', '/admin/feed-keys/', ['jar' => $w['nora']])['code'] === 403 && req('GET', '/admin/feed-keys/new', ['jar' => $w['nora']])['code'] === 403 && req('GET', '/admin/price-lists/', ['jar' => $w['nora']])['code'] === 403, 'the keys page, the mint form and the price lists are Nora\'s 403');

echo "3. The list and the usage page\n";
$list = req('GET', '/admin/feed-keys/', ['jar' => $jar]);
$b = $list['body'];
ok(str_contains($b, 'id="feed-key-list-table"') && str_contains($b, 'id="feed-key-list-cards"') && str_contains($b, 'id="feed-key-list-mint-btn"') && str_contains($b, 'id="feed-key-list-howto"'), 'the list: the table, the cards, the Mint button and the note on the feed\'s URL');
ok(str_contains($b, 'id="feed-key-row-' . $w['k_website'] . '"') && str_contains($b, 'id="feed-key-row-' . $w['k_partner'] . '"') && str_contains($b, 'id="feed-key-row-' . $w['k_sister'] . '"') && str_contains($b, 'id="feed-key-card-' . $w['k_partner'] . '"'), 'the three keys of the world are rows (and cards)');
ok(str_contains($b, 'bg-soft-success text-success">partner store') && str_contains($b, 'bg-soft-info text-info">website') && str_contains($b, 'bg-soft-secondary text-secondary">another installation') && str_contains($b, 'Dealer 20'), 'the consumer chips (website info, installation secondary, partner success) and the partner\'s price list');
ok(!str_contains($b, 'id="feed-key-row-' . $kid . '-from"') && str_contains($b, 'id="feed-key-row-' . $kid . '-rotate-btn"') && str_contains($b, 'id="feed-key-row-' . $kid . '-revoke-btn"') && str_contains($b, 'hx-confirm='), 'a fresh key has no "rotated from"; Rotate and Revoke are there, each behind a confirm');
$u = req('GET', "/admin/feed-keys/?key=$kid", ['jar' => $jar]);
ok($u['code'] === 200 && str_contains($u['body'], 'id="feed-key-usage"') && str_contains($u['body'], 'id="feed-key-usage-empty"') && str_contains($u['body'], 'No calls yet.'), '?key= shows the key\'s usage — empty before a call');
$sv = last_log('screen.view', $since);
$views = q("SELECT * FROM activity_log WHERE action = 'screen.view' AND screen = 'feed-key-list' AND token_id = :k", ['k' => $kid]);
ok(count($views) >= 1 && (int) (json_decode((string) $views[0]['after'], true)['key'] ?? 0) === $kid, 'screen.view of the keys page with ?key= carries after.key');
[$c, $d] = screen($owner, '/admin/feed-keys/');
$json = json_encode($d, JSON_UNESCAPED_SLASHES);
ok($c === 200 && count($d['keys']) >= 4 && !str_contains($json, $raw) && !str_contains($json, 'token_hash') && !str_contains($json, hash('sha256', $raw)) && str_contains($json, '/api/v1/availability'), 'the JSON read lists the keys and the feed\'s URL — no key, no hash');
[$c, $d] = screen($owner, "/admin/feed-keys/?key=$kid&bucket=minute");
ok($c === 200 && $d['usage']['bucket'] === 'minute' && $d['usage']['rows'] === [] && $d['usage']['totals']['calls'] === 0, 'the usage as JSON: minute buckets, empty');
$f = req('GET', '/admin/feed-keys/new', ['jar' => $jar]);
ok($f['code'] === 200 && str_contains($f['body'], 'id="feed-key-form"') && str_contains($f['body'], 'id="feed-key-form-field-label"') && str_contains($f['body'], 'id="feed-key-form-field-consumer_kind"') && str_contains($f['body'], 'id="feed-key-form-field-price_list"') && str_contains($f['body'], 'id="feed-key-form-save-btn"') && str_contains($f['body'], 'id="feed-key-form-cancel-btn"') && str_contains($f['body'], 'placeholder="60"') && str_contains($f['body'], 'placeholder="10000"'), 'the mint form: label, who asks, price list, both limits (the settings\' defaults as placeholders), expiry, Mint and Cancel');
finish();
