<?php
/** Rotate and revoke (feed.md "Proof" ≈ 12 + 8): a new key shown once, the old one living the overlap and no longer, the usage of each its own, a revoked key refused in the function's words; revoking; a minter who is gone shuts the door and the page says so. */
require __DIR__ . '/lib.php';
$w = feed_world();
$owner = $w['owner'];
$run = substr(md5((string) microtime(true)), 0, 6);
$gtin = $w['queen_gtin'];
$since = last_activity_id();

echo "1. Rotate\n";
[, , $old, $oid] = mint_key("Rot site $run", ['consumer_kind' => 'website']);
[$c0] = feed_get("gtin=$gtin", $old);
[$c, $b] = act($owner, '/admin/feed-keys/rotate.php', ['key' => $oid]);
$new = (string) ($b['key'] ?? '');
$nid = (int) ($b['record_id'] ?? 0);
ok($c === 200 && $c0 === 200 && preg_match('/^feed_[0-9a-f]{48}$/', $new) === 1 && $new !== $old && $nid > 0 && $nid !== $oid && ($b['refresh'] ?? '') === 'feedChanged', 'rotate answers the new key once (JSON), with a new record id');
$nr = key_row($nid);
$or = key_row($oid);
ok((int) $nr['rotated_from'] === $oid && $nr['label'] === "Rot site $run" && (int) $nr['member_id'] === 1 && $nr['consumer_kind'] === 'website' && (int) $nr['rate_per_minute'] === 60 && $nr['token_hash'] === hash('sha256', $new), 'the new key: rotated_from the old id, the same label, minter, kind and limits; only its hash stored');
$gap = strtotime((string) $or['expires_at']) - (time() + 24 * 3600);
ok($or['expires_at'] !== null && abs($gap) < 120 && $or['revoked_at'] === null && $b['old_key_id'] === $oid && abs(strtotime((string) $b['old_expires_at']) - strtotime((string) $or['expires_at'])) < 2, 'the old key\'s expires_at is now + 24 h (the setting); the reply says when the old key stops');
[$ca] = feed_get("gtin=$gtin", $old);
[$cb] = feed_get("gtin=$gtin", $new);
ok($ca === 200 && $cb === 200, 'both keys answer during the overlap');
psql_exec("UPDATE feed_keys SET expires_at = now() - interval '1 second' WHERE id = $oid");
[$ca] = feed_get("gtin=$gtin", $old);
[$cb] = feed_get("gtin=$gtin", $new);
ok($ca === 401 && $cb === 200, 'with the old key\'s time up it answers 401 and the new one still answers');
$uo = (int) one("SELECT COALESCE(sum(calls), 0) FROM key_usage WHERE token_id = :k AND bucket_kind = 'day'", ['k' => $oid]);
$un = (int) one("SELECT COALESCE(sum(calls), 0) FROM key_usage WHERE token_id = :k AND bucket_kind = 'day'", ['k' => $nid]);
ok($uo === 2 && $un === 2, 'the usage is each key\'s own (buckets by key): 2 calls on the old one, 2 on the new');
$log = last_log('feed.key_rotate', $since);
$a = after_of($log);
ok($log !== null && (int) $log['token_id'] === $nid && (int) $log['entity_id'] === $nid && (int) $a['rotated_from'] === $oid && $a['label'] === "Rot site $run" && !str_contains((string) $log['after'], $new) && !str_contains((string) $log['after'], $old), 'feed.key_rotate: the new key is the entity and token_id, rotated_from the old; neither key in the row');
[$c, $b] = act($owner, '/admin/feed-keys/rotate.php', ['key' => $oid]);
ok($c === 422 && msg($b) === 'Only a live key is rotated', 'rotating the key that has run out: 422 "Only a live key is rotated"');
[, , $rv, $rvid] = mint_key("Rot revoked $run");
act($owner, '/admin/feed-keys/revoke.php', ['key' => $rvid]);
[$c, $b] = act($owner, '/admin/feed-keys/rotate.php', ['key' => $rvid]);
ok($c === 422 && msg($b) === 'Only a live key is rotated', 'rotating a revoked key: the function\'s words, 422');
[$c, $b] = act($owner, '/admin/feed-keys/rotate.php', ['key' => 999999]);
ok($c === 404 && msg($b) === 'Feed key not found.', 'rotating a key that is not there: 404');
[$c, $b] = act($w['nora'], '/admin/feed-keys/rotate.php', ['key' => $nid]);
ok($c === 403, 'Nora may not rotate: 403');

echo "2. Rotate in a browser: the copy-once box and the overlap\n";
[$jar] = sign_on(1);
$csrf = page_csrf($jar);
[, , $bk, $bid] = mint_key("Rot browser $run");
$r = req('POST', '/admin/feed-keys/rotate.php', ['jar' => $jar, 'form' => ['key' => $bid, 'csrf_token' => $csrf]]);
$lastNew = (int) one('SELECT max(id) FROM feed_keys WHERE rotated_from = :k', ['k' => $bid]);
ok($r['code'] === 302 && $r['location'] === "/admin/feed-keys/?notice=rotated#feed-key-row-$lastNew", 'a form post rotates and lands on the new row (302)');
$page = req('GET', $r['location'], ['jar' => $jar]);
ok(preg_match('~id="feed-key-minted-value"[^>]*value="feed_[0-9a-f]{48}"~', $page['body']) === 1 && str_contains($page['body'], 'id="feed-key-minted-old"') && str_contains($page['body'], 'The old key stops working at'), 'the new key is shown once, with "The old key stops working at …"');
$again = req('GET', '/admin/feed-keys/', ['jar' => $jar]);
ok(!str_contains($again['body'], 'id="feed-key-minted"'), 'and not again on a reload');
ok(str_contains($again['body'], 'id="feed-key-row-' . $bid . '-status"') && preg_match('~id="feed-key-row-' . $bid . '-status">expiring at [A-Z][a-z]{2} \d+~', $again['body']) === 1 && str_contains($again['body'], 'id="feed-key-row-' . $lastNew . '-from"'), 'the list marks the old key "expiring at <time>" and the new one "rotated from" it');

echo "3. Revoke\n";
[, , $rk, $rkid] = mint_key("Rev key $run");
[$c1] = feed_get("gtin=$gtin", $rk);
[$c, $b] = act($owner, '/admin/feed-keys/revoke.php', ['key' => $rkid]);
[$c2] = feed_get("gtin=$gtin", $rk);
ok($c1 === 200 && $c === 200 && ($b['refresh'] ?? '') === 'feedChanged' && $c2 === 401 && key_row($rkid)['revoked_at'] !== null && (int) key_row($rkid)['revoked_by'] === 1, 'revoked: 200, and 401 on the very next call (revoked_at, revoked_by set)');
$log = last_log('feed.key_revoke', $since);
ok($log !== null && (int) $log['token_id'] === $rkid && after_of($log)['label'] === "Rev key $run" && !str_contains((string) $log['after'], $rk), 'feed.key_revoke logged with token_id and the label — never the key');
[$c, $b] = act($owner, '/admin/feed-keys/revoke.php', ['key' => $rkid]);
ok($c === 422 && msg($b) === 'That key is already revoked.', 'revoking again: 422 "That key is already revoked."');
[, , $mk, $mid] = mint_key("Rev mid-overlap $run");
[, $rb] = act($owner, '/admin/feed-keys/rotate.php', ['key' => $mid]);
act($owner, '/admin/feed-keys/revoke.php', ['key' => $mid]);
[$cx] = feed_get("gtin=$gtin", $mk);
[$cy] = feed_get("gtin=$gtin", (string) $rb['key']);
ok($cx === 401 && $cy === 200, 'revoking a key mid-overlap revokes only it; the new one answers');
$page = req('GET', '/admin/feed-keys/', ['jar' => $jar]);
ok(!str_contains($page['body'], 'id="feed-key-row-' . $rkid . '-revoke-btn"') && !str_contains($page['body'], 'id="feed-key-row-' . $rkid . '-rotate-btn"') && str_contains($page['body'], 'id="feed-key-row-' . $rkid . '-status">revoked'), 'a revoked key shows "revoked" and no Rotate or Revoke');

echo "4. A minter who is gone\n";
$wesCap = (string) one('SELECT capability FROM members WHERE id = 42');
$raw = 'feed_' . bin2hex(random_bytes(24));
psql_exec("INSERT INTO feed_keys (member_id, label, token_hash, consumer_kind) VALUES (42, 'Wes key $run', '" . hash('sha256', $raw) . "', 'website')");
$wid = (int) one("SELECT id FROM feed_keys WHERE label = 'Wes key $run'");
[$cw] = feed_get("gtin=$gtin", $raw);
psql_exec('UPDATE members SET capability = NULL WHERE id = 42');
[$cw2, $bw2] = feed_get("gtin=$gtin", $raw);
[$cok] = feed_get("gtin=$gtin", $new);
$page = req('GET', '/admin/feed-keys/', ['jar' => $jar]);
ok($cw === 200 && $cw2 === 401 && ($bw2['error']['code'] ?? '') === 'unauthorized' && $cok === 200, 'a key minted by Wes answers; when his grant is withdrawn in the mirror it answers 401, and the admin\'s keys are unaffected');
ok(preg_match('~id="feed-key-row-' . $wid . '-status"[^>]*>minter no longer here~', $page['body']) === 1 && str_contains($page['body'], 'bg-soft-danger'), 'the page marks it "minter no longer here" (danger)');
psql_exec("UPDATE members SET capability = '$wesCap' WHERE id = 42");
[$cw3] = feed_get("gtin=$gtin", $raw);
ok($cw3 === 200, 'the minter\'s grant is the key\'s: given back, it answers again (the key itself was never touched)');
finish();
