<?php
/** JSON mode (sources.md "Proof — JSON mode"): every handler under a signed action token answers {ok, did, record_id, location, refresh}; _partial; 422 fields; the expert; an eval run persists nothing. */
require __DIR__ . '/lib.php';
$w = sources_world();
$H = ['X-Action-Token: ' . person_token(40)];
$shape = static fn (int $c, array $b, string $refresh = 'sourceChanged'): bool => $c === 200 && ($b['ok'] ?? false) === true && isset($b['did'], $b['location']) && array_key_exists('record_id', $b) && ($b['refresh'] ?? '') === $refresh;
echo "1. Nora's action token\n";
[$c, $b] = act_token('/sources/save.php', ['connector' => 'woocommerce', 'name' => 'SMOKE Token store', 'base_url' => FIX, 'schedule_minutes' => '0'], $H);
ok($shape($c, $b) && $b['record_id'] > 0, 'source_create');
$s = (int) $b['record_id'];
[$c, $b] = act_token('/sources/save.php', ['source' => $s, 'settings' => json_encode(['vendor' => 'Meadowlark']), '_partial' => '1'], $H);
ok($shape($c, $b) && source_row($s)['name'] === 'SMOKE Token store' && (int) source_row($s)['schedule_minutes'] === 0, 'source_update with _partial keeps the name and the schedule');
[$c, $b] = act_token('/sources/save.php', ['source' => $s, 'rate_per_second' => '20', '_partial' => '1'], $H);
ok($c === 422 && $b['error']['code'] === 'invalid' && isset($b['error']['fields']['rate_per_second']), '422 {error: {code: invalid, fields}} names the field');
[$c, $b] = act_token('/sources/schedule.php', ['source' => $s, 'schedule_minutes' => '720'], $H);
ok($shape($c, $b) && $b['schedule_minutes'] === 720, 'source_schedule_set');
[$c, $b] = act_token('/sources/probe.php', ['source' => $s], $H);
ok($shape($c, $b) && $b['state'] === 'ok' && is_array($b['facts']), 'source_probe answers its state and facts');
[$c, $b] = act_token('/sources/pull.php', ['source' => $s], $H);
ok($shape($c, $b) && $b['queued'] === true && $b['pull_id'] === $b['record_id'], 'source_pull answers queued and the pull id');
[$c, $b] = act_token('/sources/pause.php', ['source' => $s], $H);
ok($shape($c, $b), 'source_pause');
[$c, $b] = act_token('/sources/resume.php', ['source' => $s], $H);
ok($shape($c, $b), 'source_resume');
[$c, $b] = act_token('/sources/search.php', ['q' => 'cloudrest', 'source' => $w['src_shopify']], $H);
ok($c === 200 && $b['ok'] === true && isset($b['asked'], $b['rows'], $b['query']), 'source_search answers its envelope {query, asked[], rows[]}' . ($c === 200 ? '' : ': ' . $c . ' ' . json_encode($b)));
$lv = (int) lv_by($w['src_woo'], 'sku', 'ML-AB-SK')['id'];
[$c, $b] = act_token('/listings/propose.php', ['listing_variant' => $lv], $H);
ok($shape($c, $b, 'listingChanged') && isset($b['written']), 'match_propose (a fresh scoring)');
[$c, $b] = act_token('/supplier-items/save.php', ['supplier' => $w['dealer'], 'variant' => 'SMOKE-NW-CR-T', 'lead_time_days' => '4'], $H);
ok($shape($c, $b, 'supplierChanged'), 'supplier_item_save (the variant by SKU)');
[$c, $b] = act_token('/sources/credential.php', ['source' => $w['src_shopify'], 'kind' => 'bearer', 'label' => 'token by token', 'token' => 'shpat_x'], $H);
ok($shape($c, $b) && $b['last4'] === 'at_x' && !str_contains(json_encode($b), 'shpat_x'), 'source_credential_set (never the secret in the reply)');
psql_exec("UPDATE sources SET credential_id = NULL WHERE id = {$w['src_shopify']}; DELETE FROM source_credentials WHERE source_id = {$w['src_shopify']}");
echo "2. The expert\n";
$rt = run_token(45, 92);
kernel_state(function ($s) { $s['facts']['92'] = ['valid' => true, 'is_agent' => true, 'member_id' => 45, 'run_id' => 92, 'request_id' => 'req-run-92', 'trigger' => 'chat', 'endpoints' => [['name' => 'Records MCP']]]; return $s; });
pdo()->exec("UPDATE members SET roles = '{buyer,user}' WHERE id = 45");
[$c, $b] = act_token('/sources/save.php', ['connector' => 'woocommerce', 'name' => 'SMOKE Agent store', 'base_url' => FIX, 'schedule_minutes' => '0'], as_agent($rt));
ok($c === 200 && (int) q("SELECT agent_run_id FROM activity_log WHERE action = 'source.create' ORDER BY id DESC LIMIT 1")[0]['agent_run_id'] === 92, 'the expert creates a source (source agent, run 92 — on the MCP path it pauses: other)');
$as = (int) $b['record_id'];
[$c, $b] = act_token('/sources/pull.php', ['source' => $as], as_agent($rt));
ok($c === 200 && $b['queued'] === true, 'the expert queues a pull (free for an agent)');
[$c, $b] = act_token('/sources/delete.php', ['source' => $as], as_agent($rt));
ok($c === 403, 'the expert is refused source_delete (no records.delete)');
$reg = json_decode((string) file_get_contents(dirname(__DIR__, 3) . '/mcp/action_registry.json'), true)['actions'];
ok($reg['source_create']['approval'] === 'other' && $reg['source_delete']['approval'] === 'deletion' && $reg['listing_forget']['approval'] === 'deletion' && $reg['source_credential_set']['approval'] === 'other', 'the registry: source_create and source_credential_set pause an agent (other); source_delete and listing_forget (deletion)');
echo "3. An eval run persists nothing\n";
kernel_state(function ($s) { $s['facts']['93'] = ['valid' => true, 'is_agent' => true, 'is_eval' => true, 'member_id' => 45, 'run_id' => 93, 'request_id' => 'req-run-93', 'trigger' => 'eval', 'endpoints' => [['name' => 'Records MCP']]]; return $s; });
$pulls0 = (int) one('SELECT count(*) FROM source_pulls');
$lst0 = (int) one('SELECT count(*) FROM listings');
$snap0 = (int) one('SELECT count(*) FROM offer_snapshots');
[$c, $b] = act_token('/sources/search.php', ['q' => 'cloudrest', 'source' => $w['src_shopify']], as_agent(run_token(45, 93)));
ok($c === 200 && $b['eval'] === true && $b['asked'][0]['pull_id'] === null, 'under an eval run the connector is asked and answers' . ($c === 200 ? '' : ': ' . $c . ' ' . json_encode($b)));
ok((int) one('SELECT count(*) FROM source_pulls') === $pulls0 && (int) one('SELECT count(*) FROM listings') === $lst0 && (int) one('SELECT count(*) FROM offer_snapshots') === $snap0, '…no pull row, no listing, no snapshot written');
ok(after_of(last_log('source.search'))['eval'] === true, 'logged source.search with eval: true');
pdo()->exec("UPDATE members SET roles = '{user}' WHERE id = 45");
kernel_state(function ($s) { unset($s['facts']); return $s; });
act(as_member(1), '/sources/delete.php', ['source' => $s]);
act(as_member(1), '/sources/delete.php', ['source' => $as]);
finish();
