<?php
/** The listing view (sources.md "Proof — The listing view"): the variants with the match column; the Queen's chart after the pulls — the change points, the bands, a heartbeat that draws no marker; since; cost walled; raw fields by right; the proposals card; the trail. */
require __DIR__ . '/lib.php';
$w = sources_world();
$nora = as_member(40);
$vera = as_member(43);
$shop = $w['src_shopify'];
$mattress = (int) one("SELECT id FROM listings WHERE source_id = :s AND title LIKE '%Mattress%'", ['s' => $shop]);
$q = (int) lv_by($shop, 'sku', 'NW-CR-Q')['id'];
echo "1. The variants\n";
[$c, $d] = screen($nora, '/listings/' . $mattress);
ok($c === 200 && count($d['variants']) === 6 && $d['selected'] === (int) $d['variants'][0]['listing_variant_id'], 'six variants; the first selected by default');
$qrow = array_values(array_filter($d['variants'], static fn ($v) => $v['listing_variant_id'] === $q))[0];
ok($qrow['our_sku'] === 'SMOKE-NW-CR-Q' && $qrow['match_kind'] === 'gtin', 'the Queen\'s match column: our SKU and the kind');
$html = page($nora, '/listings/' . $mattress . '?listing_variant=' . $q)['body'];
ok(str_contains($html, 'id="listing-variant-row-' . $q . '"') && str_contains($html, 'table-active') && str_contains($html, 'id="listing-variant-row-' . $q . '-unmatch"'), 'the selected row highlighted; Unmatch for Nora');
echo "2. The chart\n";
[$c, $d] = screen($nora, '/listings/' . $mattress . '?listing_variant=' . $q);
$prices = array_column($d['history'], 'price');
ok(in_array('999.00', $prices, true) && in_array('949.00', $prices, true), 'the Queen\'s history holds both prices (999.00, then 949.00 after the v2 pull)');
$av = array_column($d['availability']['runs'], 'availability');
ok(array_slice($av, 0, 2) === ['in_stock', 'out_of_stock'], 'the availability runs: in_stock → out_of_stock');
ok($d['summary']['changes'] >= 1 && (float) $d['summary']['price_min'] === 949.0 && (float) $d['summary']['price_max'] >= 999.0, 'the summary: changes, the price range — ' . json_encode($d['summary']));
psql_exec("UPDATE offer_snapshots SET observed_at = observed_at - interval '2 days' WHERE listing_variant_id = $q");
$hb = (int) one('SELECT inv_snapshot_heartbeat()');
[$c, $d] = screen($nora, '/listings/' . $mattress . '?listing_variant=' . $q);
$last = end($d['history']);
ok($hb >= 1 && $last['is_heartbeat'] === true && $last['pull_id'] === null, 'inv_snapshot_heartbeat() (called by SQL a day later) writes a heartbeat point');
$html = page($nora, '/listings/' . $mattress . '?listing_variant=' . $q)['body'];
preg_match('~<figure class="viz-root" id="listing-offer-chart".*?</figure>~s', $html, $fig);
$markers = substr_count($fig[0] ?? '', 'class="viz-marker');
$expect = 0;
foreach ($d['history'] as $r) { if (!$r['is_heartbeat']) { $expect += ($r['price'] !== null ? 1 : 0) + ($r['compare_at_price'] !== null ? 1 : 0); } }
ok($markers === $expect, 'the heartbeat draws no marker (' . $markers . ' markers for ' . $expect . ' non-heartbeat values of ' . count($d['history']) . ' points)');
ok(str_contains($fig[0] ?? '', 'viz-band-in_stock') && str_contains($fig[0] ?? '', 'viz-band-out_of_stock') && str_contains($fig[0] ?? '', 'pull #'), 'the bands in_stock → out_of_stock; a point names its pull');
ok(str_contains($html, 'id="listing-offer-table"') && str_contains($html, '>heartbeat<'), 'the snapshots table beneath, the heartbeat marked');
[$c, $d30] = screen($nora, '/listings/' . $mattress . '?listing_variant=' . $q . '&since=30');
ok($d30['since_days'] === 30 && str_contains(page($nora, '/listings/' . $mattress . '?listing_variant=' . $q . '&since=180')['body'], 'id="listing-offer-since-180"'), 'since 30 / 90 / 180 / 365');
echo "3. Cost and raw by right\n";
$feedL = (int) one("SELECT id FROM listings WHERE source_id = :s AND title LIKE '%CloudRest%'", ['s' => $w['src_feed']]);
[$c, $d] = screen($nora, '/listings/' . $feedL);
ok(count(array_filter(array_column($d['variants'], 'cost_price'))) >= 3, 'the dealer feed\'s costs shown to Nora');
[$c, $d] = screen(as_member(41), '/listings/' . $feedL);
ok(array_filter(array_column($d['variants'], 'cost_price')) === [] && array_filter(array_column($d['history'], 'cost_price')) === [], 'Sam: cost null in the variants and the history (the views, inv_offer_history())');
$html = page($vera, '/listings/' . $feedL)['body'];
ok(str_contains($html, 'title="cost withheld">—') && !str_contains($html, '649.00'), 'Vera sees "—" for cost');
[$c, $d] = screen($nora, '/listings/' . $mattress);
ok(is_array($d['raw']) && isset($d['raw']['images']), 'the raw fields for Nora (listings.match)');
[$c, $d] = screen($vera, '/listings/' . $mattress);
ok($d['raw'] === null && !str_contains(page($vera, '/listings/' . $mattress)['body'], 'id="listing-raw"'), '…absent for Vera (the view)');
echo "4. Proposals, the trail\n";
$fqL = (int) one("SELECT listing_id FROM listing_variants WHERE sku = 'PQ-FND-Q'");
[$c, $d] = screen($nora, '/listings/' . $fqL);
ok(count($d['proposals']) >= 1 && $d['proposals'][0]['evidence_words'] !== '', 'the proposals card: ' . ($d['proposals'][0]['evidence_words'] ?? ''));
$html = page($nora, '/listings/' . $fqL)['body'];
ok(preg_match('~id="proposal-row-\d+-accept"~', $html) === 1 && !str_contains(page($vera, '/listings/' . $fqL)['body'], '-accept"'), 'Accept for Nora; none for Vera');
ok(str_contains(page($nora, '/listings/' . $mattress)['body'], 'id="listing-trail"'), 'the trail card');
finish();
