<?php
/** Matching (sources.md "Proof — Matching"): a person's match never crosses sizes and survives the next pull; unmatch; an inactive variant never matched; the agent's rule (an identifier, or a person's proposal); a proposal of a person; the log. */
require __DIR__ . '/lib.php';
$w = sources_world();
$nora = as_member(40);
[$shop, $woo] = [$w['src_shopify'], $w['src_woo']];
$since = last_activity_id();
$txl = lv_by($woo, 'external_variant_id', '201');
$ck = lv_by($woo, 'external_variant_id', '203');
echo "1. A person's match\n";
[$c, $b] = act($nora, '/listings/match.php', ['listing_variant' => $txl['id'], 'variant' => $w['queen']]);
ok($c === 422 && str_starts_with(msg($b), 'A match never crosses sizes: the listing is twin_xl, the variant is queen'), 'a cross-size match is refused in inv_listing_match()\'s words: "' . msg($b) . '"');
[$c, $b] = act($nora, '/listings/match.php', ['listing_variant' => $txl['id'], 'variant' => $w['twin_xl']]);
$r = q('SELECT variant_id, match_kind, match_confidence, matched_by FROM listing_variants WHERE id = :i', ['i' => $txl['id']])[0];
ok($c === 200 && (int) $r['variant_id'] === $w['twin_xl'] && $r['match_kind'] === 'manual' && $r['match_confidence'] === '1.000' && (int) $r['matched_by'] === 40, 'Nora matches the Woo Twin XL to our Twin XL: manual, 1.000, by her');
$l = last_log('listing.match', $since);
ok($l !== null && (int) $l['source_id'] === $woo && after_of($l)['sku'] === 'SMOKE-NW-CR-TXL' && after_of($l)['match_kind'] === 'manual', 'listing.match logged with source_id, sku, match_kind');
age_source($woo, '361 minutes');
psql_exec("UPDATE sources SET paused_at = NULL WHERE id = $woo");
worker_pulls();
ok(q('SELECT match_kind FROM listing_variants WHERE id = :i', ['i' => $txl['id']])[0]['match_kind'] === 'manual', 'the next pull keeps the person\'s match');
[$c, $b] = act($nora, '/listings/unmatch.php', ['listing_variant' => $txl['id']]);
ok($c === 200 && one('SELECT variant_id FROM listing_variants WHERE id = :i', ['i' => $txl['id']]) === null && last_log('listing.unmatch', $since) !== null, 'unmatched, logged');
[$c, $b] = act($nora, '/listings/unmatch.php', ['listing_variant' => $txl['id']]);
ok($c === 422, 'unmatching an unmatched one is refused');
echo "2. An inactive variant\n";
$full = lv_by($shop, 'sku', 'NW-CR-F');
act($nora, '/listings/unmatch.php', ['listing_variant' => $full['id']]);
psql_exec("UPDATE product_variants SET active = false WHERE id = {$w['full']}");
age_source($shop, '31 minutes');
worker_pulls();
ok(one('SELECT variant_id FROM listing_variants WHERE id = :i', ['i' => $full['id']]) === null, 'an inactive variant is never matched by the rules (the Full stays unmatched after a pull)');
psql_exec("UPDATE product_variants SET active = true WHERE id = {$w['full']}");
echo "3. The expert\n";
$rt = run_token(45, 91);
kernel_state(function ($s) { $s['facts']['91'] = ['valid' => true, 'is_agent' => true, 'member_id' => 45, 'run_id' => 91, 'request_id' => 'req-run-91', 'trigger' => 'chat', 'endpoints' => [['name' => 'Records MCP']]]; return $s; });
pdo()->exec("UPDATE members SET roles = '{buyer,user}' WHERE id = 45");
[$c, $b] = act_token('/listings/match.php', ['listing_variant' => $full['id'], 'variant' => $w['full']], as_agent($rt));
ok($c === 200 && (int) one('SELECT variant_id FROM listing_variants WHERE id = :i', ['i' => $full['id']]) === $w['full'], 'the expert matches a pair that shares a GTIN: admitted');
$row = q("SELECT source, agent_run_id FROM activity_log WHERE action = 'listing.match' ORDER BY id DESC LIMIT 1")[0];
ok($row['source'] === 'agent' && (int) $row['agent_run_id'] === 91, '…logged as source agent, run 91');
[$c, $b] = act_token('/listings/match.php', ['listing_variant' => $ck['id'], 'variant' => $w['ck']], as_agent($rt));
ok($c === 403 && msg($b) === 'An agent matches only by identifier or a person\'s proposal — propose it (match_propose)', 'a pair sharing nothing: 403 in the handler\'s words');
$man = $w['src_manual'];
$mtxl = lv_by($man, 'sku', 'PQ-TXL');
$best = q("SELECT id, proposed_by FROM match_proposals WHERE listing_variant_id = :l AND status = 'proposed' ORDER BY confidence DESC LIMIT 1", ['l' => $mtxl['id']])[0] ?? null;
ok($best !== null && $best['proposed_by'] === null, 'the matcher scored the phone quote\'s Twin XL after its pull (a proposal by the matcher)');
[$c, $b] = act_token('/listings/proposals/accept.php', ['proposal' => $best['id']], as_agent($rt));
ok($c === 403 && msg($b) === 'An agent never accepts its own, another agent\'s or the matcher\'s proposal — a person does', 'the expert accepting the matcher\'s proposal: the SQL\'s refusal');
[$c, $b] = act_token('/listings/propose.php', ['listing_variant' => $ck['id'], 'variant' => $w['ck'], 'confidence' => '0.8'], as_agent($rt));
$ap = (int) $b['record_id'];
ok($c === 200 && (int) one('SELECT proposed_by FROM match_proposals WHERE id = :p', ['p' => $ap]) === 45, 'the expert may propose (its proposal is its own)');
[$c, $b] = act_token('/listings/match.php', ['listing_variant' => $ck['id'], 'variant' => $w['ck']], as_agent($rt));
ok($c === 403, '…but not match its own proposal');
psql_exec("DELETE FROM match_proposals WHERE id = $ap");
echo "4. A person's proposal\n";
[$c, $b] = act($nora, '/listings/propose.php', ['listing_variant' => $ck['id'], 'variant' => $w['ck'], 'confidence' => '0.7', 'evidence' => json_encode(['size' => true, 'note' => 'same mattress'])]);
$pp = (int) $b['record_id'];
ok($c === 200 && (int) one('SELECT proposed_by FROM match_proposals WHERE id = :p', ['p' => $pp]) === 40 && one('SELECT confidence FROM match_proposals WHERE id = :p', ['p' => $pp]) === '0.700', 'Nora proposes the Woo Cal King for our Cal King (0.7, her evidence)');
$l = last_log('listing.propose', $since);
ok(after_of($l)['proposed_by'] === 40 && after_of($l)['evidence'] === ['size', 'note'] && after_of($l)['written'] === 1, 'listing.propose logged with the proposer and the evidence keys');
[$c, $b] = act($nora, '/listings/propose.php', ['listing_variant' => $ck['id'], 'variant' => $w['ck']]);
ok($c === 422 && msg($b) === 'That pair is already proposed', 'proposing it again: "That pair is already proposed"');
[$c, $b] = act_token('/listings/match.php', ['listing_variant' => $ck['id'], 'variant' => $w['ck']], as_agent($rt));
$r = q('SELECT variant_id, match_kind FROM listing_variants WHERE id = :i', ['i' => $ck['id']])[0];
ok($c === 200 && $r['match_kind'] === 'proposed_accepted' && one('SELECT status FROM match_proposals WHERE id = :p', ['p' => $pp]) === 'accepted', 'the expert\'s listing_match on a person\'s pending proposal lands as proposed_accepted through inv_proposal_accept()');
ok(after_of(last_log('listing.match', $since))['proposal_id'] === $pp, '…and the log names the proposal');
pdo()->exec("UPDATE members SET roles = '{user}' WHERE id = 45");
kernel_state(function ($s) { unset($s['facts']); return $s; });
ok(act(as_member(41), '/listings/match.php', ['listing_variant' => $txl['id'], 'variant' => $w['twin_xl']])[0] === 403, 'Sam (no listings.match) may not match');
finish();
