<?php
/** Probes (sources.md "Proof — Probe"): ok, blocked (a rung climbed, the Buyer told), misconfigured (a mapped column the file lacks, a bad address), refused while a pull runs, logged. */
require __DIR__ . '/lib.php';
$w = sources_world();
$nora = as_member(40);
$since = last_activity_id();
echo "1. ok\n";
[$c, $b] = act($nora, '/sources/probe.php', ['source' => $w['src_shopify']]);
ok($c === 200 && $b['state'] === 'ok' && str_contains($b['message'], 'public catalog is open'), 'the Shopify fixture: ok — "' . ($b['message'] ?? '') . '"');
$p = q('SELECT kind, status FROM source_pulls WHERE id = :p', ['p' => $b['pull_id']])[0];
ok($p['kind'] === 'probe' && $p['status'] === 'ok', 'a probe pull row, finished ok');
ok(source_row($w['src_shopify'])['last_ok_at'] === null && source_row($w['src_shopify'])['robots_state'] === 'ok', 'an ok probe records robots ok but is not a pull: last_ok_at stays empty (db/019)');
$l = last_log('source.probe', $since);
ok($l !== null && after_of($l)['state'] === 'ok' && after_of($l)['pull_id'] === $b['pull_id'] && (int) $l['source_id'] === $w['src_shopify'], 'source.probe logged with the state and the pull id');
$html = req('POST', '/sources/probe.php', ['jar' => $nora, 'headers' => ['HX-Request: true', 'HX-Target: source-probe-result'], 'form' => ['source' => $w['src_shopify'], 'csrf_token' => csrf_of(page($nora, '/')['body'])]])['body'];
ok(str_contains($html, 'id="source-probe-result"') && str_contains($html, 'id="source-probe-state"') && str_contains($html, 'id="source-probe-facts"'), 'from the screen the answer renders inline: the state badge, the sentence, the facts');
echo "2. blocked\n";
[$c, $b] = act($nora, '/sources/probe.php', ['source' => $w['src_walled']]);
ok($c === 200 && $b['state'] === 'blocked', 'the walled store: blocked — "' . ($b['message'] ?? '') . '"');
$r = source_row($w['src_walled']);
ok((int) $r['consecutive_failures'] === 1 && $r['backoff_until'] !== null && abs(strtotime($r['backoff_until']) - time() - 3600) < 120, 'the source climbs one rung: backing off an hour');
$n = q("SELECT kind, member_id FROM notifications WHERE record_type = 'source' AND record_id = :s", ['s' => $w['src_walled']]);
$keys = array_column(q("SELECT dedupe_key FROM notification_outbox WHERE record_type = 'source' AND record_id = :s", ['s' => $w['src_walled']]), 'dedupe_key');
ok(count($n) === 1 && $n[0]['kind'] === 'pull_blocked' && (int) $n[0]['member_id'] === 40, 'the Buyer (the source\'s creator — no Buyer is set) is told once: pull_blocked');
ok(count($keys) === 1 && preg_match('~^pull_failed:' . $w['src_walled'] . ':1:\d+:email$~', $keys[0]) === 1, 'the mail is keyed pull_failed:<source>:1:<the streak> (once per rung of a streak): ' . ($keys[0] ?? ''));
act($nora, '/sources/probe.php', ['source' => $w['src_walled']]);
ok(count(q("SELECT 1 FROM notifications WHERE record_type = 'source' AND record_id = :s", ['s' => $w['src_walled']])) === 2, 'the second rung is a second notice (once per rung)');
[$c, $b] = act($nora, '/sources/resume.php', ['source' => $w['src_walled']]);
$r = source_row($w['src_walled']);
ok((int) $r['consecutive_failures'] === 0 && $r['backoff_until'] === null && $r['robots_state'] === 'unknown', 'resume clears the ladder; a blocked robots state becomes unknown');
echo "3. misconfigured\n";
$feedSettings = json_decode(source_row($w['src_feed'])['settings'], true);
$bad = $feedSettings;
$bad['mapping']['cost'] = 'Wholesale';
psql_exec("UPDATE sources SET settings = '" . str_replace("'", "''", json_encode($bad)) . "' WHERE id = {$w['src_feed']}");
[$c, $b] = act($nora, '/sources/probe.php', ['source' => $w['src_feed']]);
ok($c === 200 && $b['state'] === 'misconfigured' && str_contains($b['message'], 'Wholesale'), 'a feed whose mapping names a column the file lacks: misconfigured, naming it — "' . ($b['message'] ?? '') . '"');
ok(in_array('Dealer Cost', (array) ($b['facts']['columns'] ?? []), true), '…and the facts list the file\'s columns for the mapping screen');
psql_exec("UPDATE sources SET settings = '" . str_replace("'", "''", json_encode($feedSettings)) . "' WHERE id = {$w['src_feed']}");
act($nora, '/sources/resume.php', ['source' => $w['src_feed']]);
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'shopify', 'name' => 'SMOKE Bad address', 'base_url' => 'https://bad.example']);
$bad = (int) $b['record_id'];
psql_exec("UPDATE sources SET base_url = 'ftp://nowhere' WHERE id = $bad");
[$c, $b] = act($nora, '/sources/probe.php', ['source' => $bad]);
ok($c === 200 && $b['state'] === 'misconfigured' && $b['message'] !== '', 'a bad address: misconfigured with the connector\'s sentence — "' . ($b['message'] ?? '') . '"');
act(as_member(1), '/sources/delete.php', ['source' => $bad]);
echo "4. Not while a pull runs\n";
psql_exec("INSERT INTO source_pulls (source_id, kind, status) VALUES ({$w['src_woo']}, 'scheduled', 'running')");
[$c, $b] = act($nora, '/sources/probe.php', ['source' => $w['src_woo']]);
ok($c === 422 && msg($b) === 'A pull is running; probe when it finishes.', 'refused while a pull is running: "' . msg($b) . '"');
psql_exec("DELETE FROM source_pulls WHERE source_id = {$w['src_woo']} AND status = 'running'");
[$c, $b] = act(as_member(43), '/sources/probe.php', ['source' => $w['src_shopify']]);
ok($c === 403, 'Vera may not probe');
finish();
