<?php
/** Pulls (sources.md "Proof — Pulls"): the worker's pass — Shopify (GTIN), the dealer feed (supplier SKU, the price sheet), the marked-up site (MPN + size), the Woo store (a marketplace id), the manual sheet; nothing due twice; the cache; a change written once; Pull now queued; a live search. */
require __DIR__ . '/lib.php';
$w = sources_world();
$nora = as_member(40);
[$shop, $feed, $jl, $woo, $man, $walled] = [$w['src_shopify'], $w['src_feed'], $w['src_jsonld'], $w['src_woo'], $w['src_manual'], $w['src_walled']];
psql_exec("UPDATE sources SET active = false WHERE name = 'SMOKE UA'; UPDATE sources SET paused_at = now(), paused_reason = 'proof: later' WHERE id IN ($walled, $jl)");
$since = last_activity_id();
echo "1. The first pass\n";
$rep = worker_pulls();
ok(($rep['pulls'] ?? 0) === 3 && ($rep['ok'] ?? 0) === 3, 'the pass pulls the three sources due (Shopify, the feed, Woo): ' . json_encode($rep));
$p = last_pull($shop);
ok($p['kind'] === 'scheduled' && $p['status'] === 'ok' && (int) $p['listings_seen'] === 3 && (int) $p['listings_new'] === 3 && (int) $p['listings_changed'] === 0 && (int) $p['variants_changed'] === 0, 'Shopify: a scheduled pull — seen 3, new 3, changed 0, variants changed 0 (the upsert\'s counts)');
ok((int) one('SELECT count(*) FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = :s', ['s' => $shop]) === 10, 'ten listing variants (six mattress sizes, three toppers, a pillow)');
ok((int) one('SELECT count(*) FROM offer_snapshots WHERE pull_id = :p', ['p' => $p['id']]) === 10, 'every variant one snapshot');
$gt = q("SELECT lv.variant_id, lv.match_kind, lv.match_confidence, lv.matched_by FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = :s AND lv.match_kind = 'gtin'", ['s' => $shop]);
ok(count($gt) === 8 && in_array($w['queen'], array_map('intval', array_column($gt, 'variant_id')), true) && in_array($w['ck'], array_map('intval', array_column($gt, 'variant_id')), true), 'the six mattress sizes and the two Queen toppers matched by GTIN (rule 1) — the Cal King\'s "8-50123-45005-9" too');
ok(array_unique(array_column($gt, 'match_confidence')) === ['1.000'] && array_filter(array_column($gt, 'matched_by')) === [], 'confidence 1.000, matched by the matcher (NULL)');
$pol = json_decode($p['policy'], true);
ok($pol['robots'] === 'ok' && is_array($pol['hosts']) && isset($pol['hosts']['127.0.0.1']) && $pol['requests'] === [] && (int) $pol['requests_total'] === 2, 'the policy: robots a scalar ok, hosts the map, only the requests that were not ok (none of 2)');
ok((int) $p['http_requests'] === 2 && (int) $p['bytes'] > 0 && str_contains((string) $pol['user_agent'], 'MaluDB-Inventory') === str_contains((string) $pol['user_agent'], 'no contact'), 'http_requests and bytes from the client; the user-agent recorded');
$r = source_row($shop);
ok($r['last_ok_at'] !== null && (int) $r['consecutive_failures'] === 0 && $r['backoff_until'] === null, 'last_ok_at set, the ladder clear');
ok(count(q("SELECT 1 FROM activity_log WHERE action = 'listing.new' AND source_id = :s AND id > :i", ['s' => $shop, 'i' => $since])) === 3, 'listing.new ×3');
$l = q("SELECT * FROM activity_log WHERE action = 'source.pull_done' AND source_id = :s ORDER BY id DESC LIMIT 1", ['s' => $shop])[0];
ok(after_of($l)['listings_seen'] === 3 && after_of($l)['status'] === 'ok' && $l['source'] === 'cron' && (int) $l['entity_id'] === (int) $p['id'], 'source.pull_done logged by the worker (source cron) with the counts');
ok(q("SELECT 1 FROM activity_log WHERE action = 'source.pull_start' AND source_id = :s AND id > :i", ['s' => $shop, 'i' => $since]) !== [], 'source.pull_start logged');
echo "2. The dealer feed\n";
$fp = last_pull($feed);
ok($fp['status'] === 'ok' && (int) $fp['listings_seen'] === 3, 'the dealer file read: three listings (the rows grouped by Model; the pillow on its own): ' . $fp['listings_seen']);
ok(str_contains((string) $fp['error'], 'neither') || str_contains(json_encode(json_decode($fp['policy'], true)['connector'] ?? []), '"rows_skipped":1'), 'the row with no identifiers skipped and counted');
$s2 = q("SELECT lv.sku, lv.variant_id, lv.match_kind, lv.match_confidence FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = :s AND lv.match_kind = 'supplier_sku' ORDER BY lv.sku", ['s' => $feed]);
ok(count($s2) === 2 && (int) $s2[0]['variant_id'] === $w['ck'] && (int) $s2[1]['variant_id'] === $w['pillow_v'] && $s2[0]['match_confidence'] === '0.950', 'the Cal King (its UPC fails the check digit) and the pillow matched by supplier SKU (rule 2, 0.950)');
$si = q('SELECT cost, lead_time_days, last_seen_at, source_id FROM supplier_items WHERE supplier_id = :d AND variant_id = :v', ['d' => $w['dealer'], 'v' => $w['ck']])[0];
ok($si['cost'] === '649.00' && (int) $si['source_id'] === $feed && $si['last_seen_at'] !== null, 'the price sheet kept by the feed: the Cal King\'s cost 649.00 (was 600.00), last seen, the feed named');
ok((int) one('SELECT count(*) FROM supplier_items WHERE supplier_id = :d AND source_id = :f', ['d' => $w['dealer'], 'f' => $feed]) >= 5, 'the feed\'s GTIN-matched rows joined the price sheet too');
echo "3. The Woo store\n";
$wq = q("SELECT lv.variant_id, lv.match_kind FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = :s AND lv.external_variant_id = :e", ['s' => $woo, 'e' => $w['queen_asin']])[0] ?? null;
ok($wq !== null && (int) $wq['variant_id'] === $w['queen'] && $wq['match_kind'] === 'marketplace_id', 'the Queen variation matched by marketplace id (rule 4)');
ok((int) one('SELECT count(*) FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = :s AND lv.variant_id IS NULL', ['s' => $woo]) >= 2, 'the other variations wait unmatched (the queue\'s)');
echo "4. Nothing due twice; the cache; a change\n";
$rep = worker_pulls();
ok(($rep['pulls'] ?? -1) === 0, 'a second pass within the schedules runs nothing');
age_source($shop, '31 minutes');
$n0 = (int) one('SELECT count(*) FROM offer_snapshots');
$rep = worker_pulls();
$p2 = last_pull($shop);
ok(($rep['pulls'] ?? 0) === 1 && (int) $p2['id'] !== (int) $p['id'] && $p2['status'] === 'ok', 'aged 31 minutes, the Shopify store is due again');
ok((int) one('SELECT count(*) FROM offer_snapshots WHERE pull_id = :p', ['p' => $p2['id']]) === 0 && (int) one('SELECT count(*) FROM offer_snapshots') === $n0, '…nothing changed: no new snapshot');
ok((int) (json_decode($p2['policy'], true)['cached'] ?? 0) >= 1, 'the ETag answered 304: a cached request in the policy');
fix_variant('v2');
age_source($shop, '31 minutes');
$since3 = last_activity_id();
worker_pulls();
$p3 = last_pull($shop);
$snap = q('SELECT o.price, o.availability FROM offer_snapshots o WHERE o.pull_id = :p', ['p' => $p3['id']]);
ok(count($snap) === 1 && $snap[0]['price'] === '949.00' && $snap[0]['availability'] === 'out_of_stock' && (int) $p3['variants_changed'] === 1, 'the Queen\'s price and availability changed: one snapshot (949.00, out of stock), variants_changed 1');
$oc = q("SELECT after FROM activity_log WHERE action = 'offer.change' AND id > :i", ['i' => $since3]);
ok(count($oc) === 1 && json_decode($oc[0]['after'], true)['fields'] == ['price', 'availability'], 'offer.change logged with the field names, never the values');
fix_variant('v1');
echo "5. The marked-up site (MPN + size)\n";
psql_exec("UPDATE product_variants SET barcode = NULL WHERE id = {$w['king']}");     // the page's King carries the same GTIN: rule 1 would win — rule 3 is proven alone
psql_exec("UPDATE sources SET paused_at = NULL, paused_reason = NULL WHERE id = $jl");
$logBefore = count(fix_log());
worker_pulls();
psql_exec("UPDATE product_variants SET barcode = '00850123450042' WHERE id = {$w['king']}");
$jp = last_pull($jl);
ok($jp['status'] === 'ok' && (int) $jp['listings_seen'] >= 3, 'the sitemap\'s product children read: ' . $jp['listings_seen'] . ' listings');
$k = q("SELECT lv.variant_id, lv.match_kind FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = :s AND lv.mpn = :m", ['s' => $jl, 'm' => $w['king_mpn']])[0] ?? null;
ok($k !== null && (int) $k['variant_id'] === $w['king'] && $k['match_kind'] === 'mpn', 'the King matched by MPN + size (rule 3)');
$paths = array_column(array_slice(fix_log(), $logBefore), 'path');
ok(!in_array('/private/dealer-pricing.html', $paths, true) && in_array('/products/cloudrest-hybrid.html', $paths, true), 'the robots-disallowed /private/ page was never requested (the router\'s log)');
ok(q("SELECT 1 FROM listings WHERE source_id = :s AND url LIKE '%northwind-platform-frame%'", ['s' => $jl]) !== [], 'the Open Graph page is a listing');
echo "6. The manual sheet, Pull now\n";
[$c, $b] = act($nora, '/sources/pull.php', ['source' => $man]);
ok($c === 200 && $b['queued'] === true && $b['pull_id'] === $b['record_id'] && str_contains($b['location'], '#pull-row-' . $b['pull_id']), 'Pull now: queued, the pull id the record, the location the pull\'s row');
$qid = (int) $b['pull_id'];
ok(q('SELECT status, policy FROM source_pulls WHERE id = :p', ['p' => $qid])[0]['policy'] === '{"queued": true}', 'a running row marked queued');
ok(str_contains(page($nora, '/sources/' . $man)['body'], 'queued'), 'the source page shows it queued');
[$c, $b] = act($nora, '/sources/pull.php', ['source' => $man]);
ok($c === 422 && str_starts_with(msg($b), 'Pulled '), 'a second Pull now while it waits: refused (the five-minute rule speaks first) — "' . msg($b) . '"');
$rep = worker_pulls();
$mp = q('SELECT * FROM source_pulls WHERE id = :p', ['p' => $qid])[0];
ok(($rep['queued'] ?? 0) === 1 && $mp['status'] === 'ok' && (int) $mp['listings_seen'] === 2 && (json_decode($mp['policy'], true)['queued'] ?? null) === null, 'the next pass runs it first with the same pull id; its policy replaced; two listings');
ok(one('SELECT cost_price FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = :s AND lv.sku = :k', ['s' => $man, 'k' => 'PQ-TXL']) === '360.00', 'the typed cost carried (cost_price)');
[$c, $b] = act($nora, '/sources/pull.php', ['source' => $man]);
ok($c === 422 && preg_match('/^Pulled \d+ minutes? ago — try again at \d\d:\d\d UTC$/', msg($b)) === 1, 'Pull now within 5 minutes refused with the time: "' . msg($b) . '"');
echo "7. A live search\n";
$logBefore = count(fix_log());
$pulls0 = (int) one("SELECT count(*) FROM source_pulls WHERE source_id = :s AND kind IN ('scheduled', 'manual')", ['s' => $shop]);
[$c, $b] = act($nora, '/sources/search.php', ['q' => 'hybrid', 'source' => $shop]);
ok($c === 200 && $b['query'] === 'hybrid' && count($b['asked']) === 1 && $b['asked'][0]['status'] === 'ok' && $b['asked'][0]['pull_id'] !== null, 'source_search asks the Shopify store live: {query, asked[ok, pull_id]}');
$sp = q('SELECT kind, status, query FROM source_pulls WHERE id = :p', ['p' => $b['asked'][0]['pull_id']])[0];
ok($sp['kind'] === 'search' && $sp['status'] === 'ok' && $sp['query'] === 'hybrid', 'a `search` pull row with its query');
$paths = array_column(array_slice(fix_log(), $logBefore), 'path');
ok(in_array('/search/suggest.json', $paths, true) && count(array_filter($paths, static fn ($x) => str_ends_with((string) $x, '.js'))) >= 1, 'suggest.json, then each hit\'s .js (the router\'s log)');
ok(count(array_filter($b['rows'], static fn ($r) => $r['kind'] === 'matched')) >= 1, 'the answer\'s rows carry the matched variants\' availability');
ok((int) one("SELECT count(*) FROM source_pulls WHERE source_id = :s AND kind IN ('scheduled', 'manual')", ['s' => $shop]) === $pulls0, 'a search pull never counts as a pull (removals ignore it)');
ok(after_of(last_log('source.search'))['query'] === 'hybrid' && after_of(last_log('source.search'))['eval'] === false, 'source.search logged with the query');
[$c, $b] = act($nora, '/sources/search.php', ['q' => 'x']);
ok($c === 422 && isset(fields($b)['q']), 'a query of one character is refused');
[$c, $b] = act($nora, '/sources/search.php', ['q' => 'hybrid', 'source' => $feed]);
ok($c === 200 && $b['asked'][0]['status'] === 'no live search', 'a feed has no live search: answered from the last pull ("no live search")');
[$c, $b] = act(as_member(42), '/sources/search.php', ['q' => 'hybrid']);
ok($c === 403, 'Wes (no orders.write) may not ask the sources');
finish();
