<?php
/** The match queue (sources.md "Proof — The queue"): what waits, the best proposal in words; Accept, Dismiss (the next surfaces, and stays dismissed after a pull), Pick another, Score again (the matcher's), Not ours; the filters. */
require __DIR__ . '/lib.php';
$w = sources_world();
$nora = as_member(40);
[$shop, $woo, $man, $jl] = [$w['src_shopify'], $w['src_woo'], $w['src_manual'], $w['src_jsonld']];
$since = last_activity_id();
echo "1. What waits\n";
[$c, $d] = screen($nora, '/matching/');
$lvs = array_column($d['rows'], 'listing_variant_id');
ok($c === 200 && in_array((int) lv_by($woo, 'external_variant_id', '201')['id'], $lvs, true) && in_array((int) lv_by($woo, 'sku', 'ML-WP-Q')['id'], $lvs, true), 'the Woo store\'s unmatched variations wait in the queue');
$removedLv = (int) lv_by($shop, 'sku', 'HP-LT-K-3')['id'];
ok(!in_array($removedLv, $lvs, true), 'a removed listing\'s variant does not');
ok($d['counts']['queued'] === count($lvs) && $d['counts']['with_proposal'] >= 2, 'the counts: ' . json_encode($d['counts']));
$mtxl = (int) lv_by($man, 'sku', 'PQ-TXL')['id'];
$row = array_values(array_filter($d['rows'], static fn ($r) => $r['listing_variant_id'] === $mtxl))[0];
ok($row['best_proposal']['sku'] === 'SMOKE-NW-CR-TXL' && (float) $row['best_proposal']['confidence'] >= 0.7, 'the phone quote\'s best proposal: our Cloudrest Twin XL (' . $row['best_proposal']['confidence'] . ')');
$html = page($nora, '/matching/')['body'];
ok(preg_match('~id="queue-row-' . $mtxl . '-evidence">([^<]+)<~', $html, $m) === 1 && str_contains($m[1], 'brand in the title') && str_contains($m[1], 'size matches'), 'its evidence in words: "' . ($m[1] ?? '') . '"');
echo "2. Accept\n";
$others = (int) one("SELECT count(*) FROM match_proposals WHERE listing_variant_id = :l AND status = 'proposed'", ['l' => $mtxl]);
[$c, $b] = act($nora, '/listings/proposals/accept.php', ['proposal' => $row['best_proposal']['proposal_id'], 'return_to' => '/matching/']);
$r = q('SELECT variant_id, match_kind FROM listing_variants WHERE id = :i', ['i' => $mtxl])[0];
ok($c === 200 && (int) $r['variant_id'] === variant_id('SMOKE-NW-CR-TXL') && $r['match_kind'] === 'proposed_accepted' && str_starts_with($b['location'], '/matching/'), 'Accept: matched proposed_accepted, back on the queue');
ok($others >= 2 && (int) one("SELECT count(*) FROM match_proposals WHERE listing_variant_id = :l AND status = 'dismissed'", ['l' => $mtxl]) === $others - 1, 'the other proposals of that variant dismissed');
ok(!in_array($mtxl, array_column(screen($nora, '/matching/')[1]['rows'], 'listing_variant_id'), true), 'gone from the queue');
$l = last_log('listing.accept', $since);
ok($l !== null && after_of($l)['proposed_by'] === null && in_array('size', after_of($l)['evidence'], true), 'listing.accept logged: the proposer (the matcher) and the evidence keys');
echo "3. Dismiss, and it stays dismissed\n";
$fq = (int) lv_by($man, 'sku', 'PQ-FND-Q')['id'];
$ps = q("SELECT id, variant_id, confidence FROM match_proposals WHERE listing_variant_id = :l AND status = 'proposed' ORDER BY confidence DESC", ['l' => $fq]);
ok(count($ps) >= 2, 'the foundation quote has ' . count($ps) . ' proposals');
act($nora, '/listings/proposals/dismiss.php', ['proposal' => $ps[0]['id'], 'return_to' => '/matching/']);
$rowNow = array_values(array_filter(screen($nora, '/matching/')[1]['rows'], static fn ($r) => $r['listing_variant_id'] === $fq))[0];
ok((int) $rowNow['best_proposal']['proposal_id'] === (int) $ps[1]['id'], 'Dismiss: the next best surfaces');
ok(last_log('listing.dismiss', $since) !== null, 'listing.dismiss logged');
$n0 = (int) one('SELECT count(*) FROM match_proposals WHERE listing_variant_id = :l', ['l' => $fq]);
age_source($man, '6 minutes');
act($nora, '/sources/pull.php', ['source' => $man]);
worker_pulls();
ok(one('SELECT status FROM match_proposals WHERE id = :p', ['p' => $ps[0]['id']]) === 'dismissed' && (int) one('SELECT count(*) FROM match_proposals WHERE listing_variant_id = :l', ['l' => $fq]) === $n0, 'after the next pull the dismissed pair stays dismissed (not re-scored)');
echo "4. Pick another, Score again\n";
$prot = (int) lv_by($woo, 'sku', 'ML-WP-Q')['id'];
[$c, $b] = act($nora, '/listings/match.php', ['listing_variant' => $prot, 'variant' => $w['fnd_queen'], 'return_to' => '/matching/']);
ok($c === 200 && (int) one('SELECT variant_id FROM listing_variants WHERE id = :i', ['i' => $prot]) === $w['fnd_queen'], 'Pick another: a person\'s match from the queue (listing_match)');
psql_exec("DELETE FROM match_proposals WHERE listing_variant_id = $fq AND status = 'proposed'");
[$c, $b] = act($nora, '/listings/propose.php', ['listing_variant' => $fq, 'return_to' => '/matching/']);
$fresh = q("SELECT proposed_by FROM match_proposals WHERE listing_variant_id = :l AND status = 'proposed'", ['l' => $fq]);
ok($c === 200 && $b['written'] >= 1 && count($fresh) === $b['written'] && array_filter(array_column($fresh, 'proposed_by')) === [], 'Score again: fresh proposals (' . $b['written'] . ') — the matcher\'s (proposer NULL)');
echo "5. Not ours\n";
$jll = (int) one("SELECT id FROM listings WHERE source_id = :s AND url LIKE '%cloudrest-hybrid%'", ['s' => $jl]);
$matched0 = (int) one('SELECT count(*) FROM listing_variants WHERE listing_id = :l AND variant_id IS NOT NULL', ['l' => $jll]);
[$c, $b] = act($nora, '/listings/forget.php', ['listing' => $jll, 'return_to' => '/matching/']);
ok($c === 200 && $b['variants_unmatched'] === $matched0 && $matched0 >= 3, 'Not ours: every variant unmatched (' . $matched0 . ')');
ok(one('SELECT forgotten_at FROM mcp_listings WHERE listing_id = :l', ['l' => $jll]) !== null, 'forgotten_at visible on mcp_listings');
$lvIds = array_map('intval', array_column(q('SELECT id FROM listing_variants WHERE listing_id = :l', ['l' => $jll]), 'id'));
ok(array_intersect($lvIds, array_column(screen($nora, '/matching/')[1]['rows'], 'listing_variant_id')) === [], 'hidden from the queue');
age_source($jl, '1441 minutes');
psql_exec("UPDATE sources SET paused_at = NULL WHERE id = $jl");
worker_pulls();
ok((int) one('SELECT count(*) FROM listing_variants WHERE listing_id = :l AND variant_id IS NOT NULL', ['l' => $jll]) === 0, 'the next pull does not re-match it (rule 1 would have)');
ok((int) one('SELECT count(*) FROM match_proposals mp JOIN listing_variants lv ON lv.id = mp.listing_variant_id WHERE lv.listing_id = :l AND mp.status = \'proposed\'', ['l' => $jll]) === 0, '…nor score it');
[$c, $b] = act($nora, '/listings/forget.php', ['listing' => $jll]);
ok($c === 422 && msg($b) === 'That listing was already marked not ours', 'a second forget: "already marked not ours"');
ok(after_of(last_log('listing.forget', $since))['variants'] === $matched0, 'listing.forget logged with the variants count');
echo "6. Filters, rights\n";
[$c, $d] = screen($nora, '/matching/?source=' . $woo);
ok(array_unique(array_column($d['rows'], 'source_id')) === [$woo], 'the source filter');
[$c, $d] = screen($nora, '/matching/?min_confidence=0.6');
ok(array_filter($d['rows'], static fn ($r) => $r['best_proposal'] === null || (float) $r['best_proposal']['confidence'] < 0.6) === [], 'min_confidence 0.6 keeps only rows whose best is at least 0.6');
ok(page(as_member(41), '/matching/')['code'] === 403, 'Sam (no listings.match) cannot open the queue');
finish();
