<?php
/** Removal and the ladder (sources.md "Proof — Removal and the ladder"): two full pulls without a listing remove it (the match stays); a partial pull removes nothing; blocked × 3 = an hour, a day, paused, the Buyer told per rung; resume; a credential that will not open. */
require __DIR__ . '/lib.php';
$w = sources_world();
$nora = as_member(40);
[$shop, $jl, $walled] = [$w['src_shopify'], $w['src_jsonld'], $w['src_walled']];
psql_exec("UPDATE sources SET paused_at = now(), paused_reason = 'proof: elsewhere' WHERE id NOT IN ($shop) AND active AND paused_at IS NULL");
$since = last_activity_id();
echo "1. Two full pulls without the topper and the pillow\n";
act_token('/sources/save.php', ['source' => $shop, 'settings' => json_encode(['collections' => ['mattresses']]), '_partial' => '1'], ['X-Action-Token: ' . person_token(40)]);
$topper = (int) one("SELECT id FROM listings WHERE source_id = :s AND title LIKE '%Topper%'", ['s' => $shop]);
$pillow = (int) one("SELECT id FROM listings WHERE source_id = :s AND title LIKE '%Pillow%'", ['s' => $shop]);
$mattress = (int) one("SELECT id FROM listings WHERE source_id = :s AND title LIKE '%Mattress%'", ['s' => $shop]);
age_source($shop, '31 minutes');
worker_pulls();
$a = last_pull($shop);
ok($a['status'] === 'ok' && (int) $a['listings_seen'] === 1 && (int) $a['listings_removed'] === 0, 'the first pull of the mattresses collection: seen 1, removed 0 (one full pull without them is not enough)');
ok(one('SELECT removed_at FROM listings WHERE id = :l', ['l' => $topper]) === null, 'the topper is still live');
age_source($shop, '31 minutes');
worker_pulls();
$b = last_pull($shop);
ok($b['status'] === 'ok' && (int) $b['listings_removed'] === 2, 'the second full pull: listings_removed 2 on that pull');
ok(one('SELECT removed_at FROM listings WHERE id = :l', ['l' => $topper]) !== null && one('SELECT removed_at FROM listings WHERE id = :l', ['l' => $pillow]) !== null, 'the topper and the pillow removed_at set');
$tv = q('SELECT availability, qty, removed_at, variant_id FROM listing_variants WHERE listing_id = :l', ['l' => $topper]);
ok(array_unique(array_column($tv, 'availability')) === ['unknown'] && array_filter(array_column($tv, 'qty'), static fn ($x) => $x !== null) === [], 'their variants: availability unknown, qty NULL');
ok(count(array_filter(array_column($tv, 'variant_id'))) === 2, 'the toppers\' matches stay');
ok((int) one('SELECT count(*) FROM offer_snapshots o JOIN listing_variants lv ON lv.id = o.listing_variant_id WHERE lv.listing_id = :l AND o.pull_id = :p AND o.availability = \'unknown\'', ['l' => $topper, 'p' => $b['id']]) === 3, 'a snapshot says so for each of the topper\'s variants');
ok(one('SELECT removed_at FROM listings WHERE id = :l', ['l' => $mattress]) === null, 'the mattress (seen) stays');
ok(count(q("SELECT 1 FROM activity_log WHERE action = 'listing.removed' AND source_id = :s AND id > :i", ['s' => $shop, 'i' => $since])) === 2, 'listing.removed ×2');
[$c, $d] = screen($nora, '/sources/' . $shop . '/listings?removed=1');
ok(count(array_filter($d['listings'], static fn ($l) => $l['removed_at'] !== null)) === 2, 'the listings screen shows them under "removed" when asked');
echo "2. A partial pull removes nothing\n";
psql_exec("UPDATE sources SET paused_at = NULL WHERE id = $jl");
$live0 = (int) one('SELECT count(*) FROM listings WHERE source_id = :s AND removed_at IS NULL', ['s' => $jl]);
act_token('/sources/save.php', ['source' => $jl, 'settings' => json_encode(['urls' => [FIX . '/products/cloudrest-hybrid.html', FIX . '/products/harbor-latex-topper.html', FIX . '/wall']]), '_partial' => '1'], ['X-Action-Token: ' . person_token(40)]);
for ($i = 0; $i < 2; $i++) { age_source($jl, '1441 minutes'); worker_pulls(); }
$jp = last_pull($jl);
ok($jp['status'] === 'partial' && (int) $jp['listings_removed'] === 0, 'a marked-up site whose URL list ends at a wall: partial, listings_removed 0');
ok((int) one('SELECT count(*) FROM listings WHERE source_id = :s AND removed_at IS NULL', ['s' => $jl]) === $live0, 'after two partial pulls the listings they did not reach are still live');
ok((int) source_row($jl)['consecutive_failures'] === 0, 'a partial pull is not a failure: the ladder stays clear');
psql_exec("UPDATE sources SET paused_at = now() WHERE id = $jl");
echo "3. The ladder\n";
psql_exec("UPDATE sources SET paused_at = NULL, paused_reason = NULL WHERE id = $walled");
$n0 = (int) one("SELECT count(*) FROM notifications WHERE record_type = 'source' AND record_id = :s", ['s' => $walled]);
$since2 = last_activity_id();
worker_pulls();
$r = source_row($walled);
ok(last_pull($walled)['status'] === 'blocked' && (int) $r['consecutive_failures'] === 1 && abs(strtotime($r['backoff_until']) - time() - 3600) < 120, 'blocked once: backing off an hour');
worker_pulls();
ok((int) one("SELECT count(*) FROM source_pulls WHERE source_id = :s AND kind = 'scheduled'", ['s' => $walled]) === 1, 'skipped by inv_sources_due() while backing off');
age_source($walled, '61 minutes');
worker_pulls();
$r = source_row($walled);
ok((int) $r['consecutive_failures'] === 2 && abs(strtotime($r['backoff_until']) - time() - 86400) < 120, 'blocked twice: backing off a day');
age_source($walled, '1441 minutes');
worker_pulls();
$r = source_row($walled);
ok((int) $r['consecutive_failures'] === 3 && $r['paused_at'] !== null && str_starts_with((string) $r['paused_reason'], '3 failures in a row (last: '), 'blocked three times: paused — "' . $r['paused_reason'] . '"');
$keys = array_column(q("SELECT dedupe_key FROM notification_outbox WHERE record_type = 'source' AND record_id = :s AND dedupe_key LIKE 'pull_failed:%' ORDER BY id", ['s' => $walled]), 'dedupe_key');
ok((int) one("SELECT count(*) FROM notifications WHERE record_type = 'source' AND record_id = :s", ['s' => $walled]) - $n0 === 3, 'the Buyer told once per rung: three notices');
$streak = array_values(array_filter($keys, static fn ($k) => preg_match('~^pull_failed:' . $walled . ':[123]:(\d+):email$~', $k) === 1));
ok(count($streak) >= 3 && count(array_unique(array_map(static fn ($k) => explode(':', $k)[3], array_slice($streak, -3)))) === 1, 'keyed pull_failed:<source>:1..3:<the streak> — the same streak, a key per rung');
ok(count(q("SELECT 1 FROM activity_log WHERE action = 'source.pull_blocked' AND source_id = :s AND id > :i", ['s' => $walled, 'i' => $since2])) === 3, 'source.pull_blocked logged three times');
age_source($walled, '3 days');
$rep = worker_pulls();
ok((int) one("SELECT count(*) FROM source_pulls WHERE source_id = :s AND kind = 'scheduled'", ['s' => $walled]) === 3, 'a paused source is never pulled by the worker');
[$c, $d] = screen($nora, '/sources/' . $walled);
ok($d['source']['health'] === 'paused' && str_starts_with($d['source']['health_sentence'], 'paused: 3 failures in a row'), 'the source page: paused, with the reason');
act($nora, '/sources/resume.php', ['source' => $walled]);
$r = source_row($walled);
ok($r['paused_at'] === null && (int) $r['consecutive_failures'] === 0 && $r['robots_state'] === 'unknown', 'resume: cleared, robots_state unknown');
act($nora, '/sources/pause.php', ['source' => $walled, 'reason' => 'a wall']);
echo "4. A credential that will not open\n";
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'shopify', 'name' => 'SMOKE Tampered', 'base_url' => FIX, 'schedule_minutes' => '0']);
$t = (int) $b['record_id'];
act($nora, '/sources/credential.php', ['source' => $t, 'kind' => 'bearer', 'label' => 'tampered', 'token' => 'shpat_secret_never_seen']);
psql_exec("UPDATE source_credentials SET ciphertext = convert_to('v1.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'UTF8') WHERE source_id = $t");
act($nora, '/sources/pull.php', ['source' => $t]);
worker_pulls();
$tp = last_pull($t);
ok($tp['status'] === 'failed' && $tp['error'] === 'the credential cannot be opened — set it again', 'the pull fails: "the credential cannot be opened — set it again"');
ok(!str_contains(json_encode(q('SELECT * FROM source_pulls WHERE source_id = :s', ['s' => $t])) . json_encode(q("SELECT after FROM activity_log WHERE source_id = :s", ['s' => $t])), 'shpat_secret_never_seen'), 'no secret in the pull, its error or the log');
act(as_member(1), '/sources/delete.php', ['source' => $t]);
psql_exec("UPDATE sources SET paused_at = NULL, paused_reason = NULL WHERE paused_reason = 'proof: elsewhere'");
finish();
