<?php
/** Sources (sources.md "Proof — Sources"): the six made through the handler, a template adopted, the CHECK and the trigger's rules in words, the user-agent rule, the settings filter, pause / resume, the cards, the log. */
require __DIR__ . '/lib.php';
$w = sources_world();
$nora = as_member(40);
$since = last_activity_id();
$mapping = ['supplier_sku' => 'Item Number', 'gtin' => 'UPC', 'name' => 'Description', 'size' => 'Size', 'cost' => 'Dealer Cost', 'map_price' => 'MAP', 'qty' => 'Qty Available', 'lead_time_days' => 'Lead Time (days)', 'brand' => 'Brand', 'product' => 'Model'];
echo "1. The six sources\n";
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'shopify', 'name' => 'SMOKE Shopify store', 'role' => 'reference', 'base_url' => FIX . '/', 'schedule_minutes' => '30',
    'settings_shopify' => ['_present' => '1', 'collections' => '', 'currency' => 'usd', 'api_version' => '2024-10']]);
ok($c === 200 && $b['ok'] === true && $b['location'] === '/sources/' . $b['record_id'] . '?notice=created' && $b['refresh'] === 'sourceChanged', 'Nora makes the Shopify store: {ok, record_id, location, refresh sourceChanged}');
$shop = (int) $b['record_id'];
ok(source_row($shop)['base_url'] === FIX && json_decode(source_row($shop)['settings'], true) == ['currency' => 'USD', 'api_version' => '2024-10'], 'the trailing slash stripped; the settings are the connector\'s keys only (currency upper-cased)');
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'feed', 'name' => 'SMOKE Dealer feed', 'role' => 'supplier', 'supplier' => $w['dealer'],
    'settings_feed' => ['_present' => '1', 'transport' => 'https', 'url' => FIX . '/feed.csv', 'format' => 'auto', 'delimiter' => 'auto', 'has_header' => 'yes', 'currency' => 'USD', 'mapping' => $mapping]]);
ok($c === 200, 'the dealer feed (supplier, the mapping by header, checked against the file on save)');
$feed = (int) $b['record_id'];
ok((int) source_row($feed)['schedule_minutes'] === 30, 'a blank schedule: 30 minutes for a supplier (the trigger)');
ok(json_decode(source_row($feed)['settings'], true)['mapping']['cost'] === 'Dealer Cost', 'the mapping stored as the header names');
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'jsonld', 'name' => 'SMOKE Marked-up site', 'base_url' => FIX, 'settings_jsonld' => ['_present' => '1', 'sitemap_url' => '/sitemap.xml']]);
$jl = (int) $b['record_id'];
ok($c === 200 && (int) source_row($jl)['schedule_minutes'] === 1440, 'the marked-up site: a blank schedule is daily (1440)');
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'woocommerce', 'name' => 'SMOKE Woo store', 'base_url' => FIX, 'rate_per_second' => '5']);
$woo = (int) $b['record_id'];
ok($c === 200 && (int) source_row($woo)['schedule_minutes'] === 360, 'the Woo store, a reference: every 6 hours (360)');
ok(source_row($woo)['rate_per_second'] === '1.00', 'a rate of 5 is capped to the policy\'s 1.00 (the trigger)');
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'manual', 'name' => 'SMOKE Price sheet', 'role' => 'supplier', 'supplier' => $w['dealer'], 'settings_manual' => ['_present' => '1', 'listings' => [
    ['title' => 'SMOKE Cloudrest Hybrid Twin XL — phone quote', 'brand' => 'Northwind Sleep', 'sku' => 'PQ-TXL', 'size' => 'Twin XL', 'price' => '749.00', 'cost' => '360.00', 'qty' => '4', 'availability' => 'in_stock', 'recorded_on' => date('Y-m-d')],
    ['title' => 'SMOKE Cloudrest Foundation Queen — phone quote', 'brand' => 'Northwind Sleep', 'sku' => 'PQ-FND-Q', 'size' => 'Queen', 'price' => '299.00', 'cost' => '118.00', 'availability' => 'back_order', 'lead_time_days' => '14'],
    ['title' => '', 'sku' => '']]]]);
$man = (int) $b['record_id'];
$ml = json_decode(source_row($man)['settings'], true)['listings'];
ok($c === 200 && (int) source_row($man)['schedule_minutes'] === 0 && count($ml) === 2, 'the price sheet: manual (schedule 0), two rows kept, the empty one dropped');
ok($ml[0]['recorded_by'] === 'SMOKE Nora' && $ml[1]['recorded_on'] === date('Y-m-d'), 'each row carries who typed it and the date (today by default)');
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'shopify', 'name' => 'SMOKE Walled store', 'base_url' => FIX . '/wall']);
$walled = (int) $b['record_id'];
ok($c === 200 && $walled > 0, 'the walled store (a Shopify source at the router\'s bot-wall path)');
$l = last_log('source.create', $since);
ok($l !== null && (int) $l['source_id'] === $walled && after_of($l)['connector'] === 'shopify' && isset(after_of($l)['settings_keys']), 'source.create logged with source_id, connector and settings_keys');
$feedLog = q("SELECT after FROM activity_log WHERE action = 'source.create' AND source_id = :s", ['s' => $feed])[0]['after'];
ok(!str_contains($feedLog, 'Dealer Cost') && !str_contains($feedLog, 'feed.csv') && str_contains($feedLog, 'mapping'), 'the feed\'s log row names the settings keys — never the mapping\'s columns or the URL');
echo "2. The refusals\n";
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'feed', 'name' => 'SMOKE Orphan feed', 'role' => 'supplier', 'settings_feed' => ['_present' => '1', 'url' => FIX . '/feed.csv']]);
ok($c === 422 && msg($b) === 'A supplier source names its supplier — choose the supplier, or make it a reference source.', 'a supplier source without a supplier: the CHECK, in words');
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'shopify', 'name' => 'smoke shopify STORE', 'base_url' => FIX]);
ok($c === 422 && msg($b) === 'That name is already taken.', 'a duplicate name (case aside)');
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'shopify', 'name' => 'SMOKE UA', 'base_url' => FIX, 'user_agent' => 'MyBot/1.0']);
ok($c === 422 && str_contains(fields($b)['user_agent'] ?? '', 'An honest user-agent names the business and a contact'), 'a user-agent with no contact: refused in words');
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'shopify', 'name' => 'SMOKE UA', 'base_url' => FIX, 'user_agent' => 'SMOKE Beds/1.0 (+mailto:buyer@example.invalid)']);
ok($c === 200, '…one naming a contact is kept');
$ua = (int) $b['record_id'];
[$c, $b] = act_token('/sources/save.php', ['connector' => 'shopify', 'name' => 'SMOKE Agent settings', 'base_url' => FIX, 'settings' => json_encode(['collections' => ['beds'], 'endpoint' => '/x'])], ['X-Action-Token: ' . person_token(40)]);
ok($c === 422 && str_contains(fields($b)['settings'] ?? $b['error']['message'] ?? '', 'does not read endpoint'), 'an unknown settings key from JSON is refused in words: ' . (fields($b)['settings'] ?? ''));
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'jsonld', 'name' => 'SMOKE Bad pattern', 'base_url' => FIX, 'settings_jsonld' => ['_present' => '1', 'url_pattern' => '(unclosed']]);
ok($c === 422 && isset(fields($b)['settings_jsonld.url_pattern']), 'a URL pattern that does not compile is a field error');
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'feed', 'name' => 'SMOKE Bad map', 'role' => 'supplier', 'supplier' => $w['dealer'], 'settings_feed' => ['_present' => '1', 'url' => FIX . '/feed.csv', 'mapping' => ['supplier_sku' => 'Item Number', 'cost' => 'Wholesale']]]);
ok($c === 422 && str_contains(fields($b)['feed-mapping-cost'] ?? '', 'Wholesale'), 'a mapping naming a column the file lacks: the field error on that select (' . (fields($b)['feed-mapping-cost'] ?? '') . ')');
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'feed', 'name' => 'SMOKE Plain http', 'role' => 'supplier', 'supplier' => $w['dealer'], 'settings_feed' => ['_present' => '1', 'url' => 'http://dealer.example/feed.csv']]);
ok($c === 422 && isset(fields($b)['settings_feed.url']), 'a feed URL that is not https is refused');
[$c, $b] = act($nora, '/sources/save.php', ['connector' => 'shopify', 'name' => 'SMOKE No base']);
ok($c === 422 && isset(fields($b)['base_url']), 'a store with no address is refused');
[$c, $b] = act(as_member(41), '/sources/save.php', ['connector' => 'shopify', 'name' => 'SMOKE Sam', 'base_url' => FIX]);
ok($c === 403, 'Sam (no sources.write) is refused: ' . msg($b));
echo "3. A template\n";
[$c, $d] = screen($nora, '/sources/new?template=maloufhome');
ok($c === 200 && $d['template']['key'] === 'maloufhome', 'the add form answers the template');
$brands0 = (int) one("SELECT count(*) FROM brands WHERE lower(name) = 'malouf'");
[$c, $b] = act($nora, '/sources/save.php', ['template' => 'maloufhome']);
$mal = (int) ($b['record_id'] ?? 0);
ok($c === 200 && source_row($mal)['name'] === 'Malouf Home (maloufhome.com)' && source_row($mal)['base_url'] === 'https://www.maloufhome.com', 'Nora adds a source from the maloufhome template: its name, connector, role, base_url');
ok($brands0 === 0 && (int) one("SELECT count(*) FROM brands WHERE lower(name) = 'malouf'") === 1 && $b['brand_id'] !== null, 'the brand "Malouf" is made from the hint');
ok(json_decode(source_row($mal)['settings'], true) === [], 'the seeded inert settings (endpoint, limit) are dropped');
act($nora, '/sources/pause.php', ['source' => $mal, 'reason' => 'a real site — never pulled by the proof']);
psql_exec("UPDATE source_templates SET survey_result = 'blocked' WHERE key = 'maloufhome'");
$html = page($nora, '/sources/new?template=maloufhome')['body'];
ok(str_contains($html, 'id="source-form-blocked-doors"') && str_contains($html, 'id="source-form-door-jsonld"') && str_contains($html, 'connector=jsonld'), 'a blocked template shows the two doors (the sitemap through jsonld, a Storefront token)');
psql_exec("UPDATE source_templates SET survey_result = 'unverified' WHERE key = 'maloufhome'");
echo "4. Change, pause, resume\n";
$since2 = last_activity_id();
act($nora, '/sources/pause.php', ['source' => $shop, 'reason' => 'checking prices by hand']);
$r = source_row($shop);
ok($r['paused_at'] !== null && $r['paused_reason'] === 'checking prices by hand' && last_log('source.pause', $since2) !== null, 'paused with a reason, logged');
[$c, $b] = act($nora, '/sources/save.php', ['source' => $shop, 'base_url' => FIX . '/', 'settings_shopify' => ['_present' => '1', 'currency' => 'USD', 'api_version' => '2024-10']]);
ok($c === 200 && $b['resumed'] === false, 'saving with nothing of the configuration changed does not resume (the same URL once the slash is stripped)');
[$c, $b] = act_token('/sources/save.php', ['source' => $shop, 'settings' => json_encode(['max_products' => 500]), '_partial' => '1'], ['X-Action-Token: ' . person_token(40)]);
$r = source_row($shop);
ok($c === 200 && $b['resumed'] === true && $r['paused_at'] === null, 'a settings change resumes the paused source (inv_source_resume)');
ok(json_decode($r['settings'], true) == ['currency' => 'USD', 'api_version' => '2024-10', 'max_products' => 500] && $r['name'] === 'SMOKE Shopify store', '_partial: the settings merged, the rest kept');
$l = last_log('source.update', $since2);
ok($l !== null && after_of($l)['settings_changed'] === ['max_products'] && after_of($l)['resumed'] === true, 'source.update logs the settings keys that changed');
act($nora, '/sources/pause.php', ['source' => $shop]);
ok(source_row($shop)['paused_reason'] === 'paused by SMOKE Nora', 'a pause with no reason says who paused it');
[$c, $b] = act($nora, '/sources/resume.php', ['source' => $shop]);
ok($c === 200 && source_row($shop)['paused_at'] === null && last_log('source.resume', $since2) !== null, 'resumed, logged');
echo "5. The cards\n";
[$c, $d] = screen(as_member(43), '/sources/');
$card = array_values(array_filter($d['sources'], static fn ($s) => $s['source_id'] === $shop))[0] ?? null;
ok($c === 200 && $card !== null && $card['health'] === 'never_pulled' && $card['connector_label'] === 'Shopify store', 'Vera reads the cards: the connector\'s label, never_pulled');
ok($card['settings'] === null && $card['user_agent'] === null, '…and no settings or user-agent below sources.write (the view)');
$html = page(as_member(43), '/sources/')['body'];
ok(str_contains($html, 'id="source-card-' . $shop . '"') && !str_contains($html, 'id="source-list-new-btn"'), 'the card is there; Vera has no Add a source');
[$c, $d] = screen($nora, '/sources/?connector=feed');
ok(array_column($d['sources'], 'source_id') === [$feed], 'the connector filter');
finish();
