<?php
/** The promise line and the pick list (find.md "Proof — ATP"; the pick list the order and purchase-order forms type into). */
require __DIR__ . '/lib.php';
$w = find_world();
$nora = as_member(40); $sam = as_member(41);
$q = $w['queen'];
echo "1. The promise\n";
[$c, $d] = screen($sam, '/find/atp?variant=' . $q . '&qty=1');
ok($c === 200 && $d['atp']['can_promise'] === true && $d['atp']['from'] === 'stock' && (int) $d['atp']['location_id'] === $w['wh'] && $d['atp']['by'] === gmdate('Y-m-d'), '1 Queen: from stock at the Warehouse, by today');
[$c, $h] = frag($sam, '/find/atp?variant=' . $q . '&qty=1');
ok(preg_match('~id="atp-' . $q . '" class="text-muted mt-1 fs-12"[^>]*>\s*3 available at SMOKE Warehouse — from SMOKE Warehouse, by ~', $h) === 1, '…the line: "3 available at SMOKE Warehouse — from SMOKE Warehouse, by …"');
[$c, $d] = screen($nora, '/find/atp?variant=' . $q . '&qty=5');
ok($d['atp']['can_promise'] === true && $d['atp']['from'] === 'source' && $d['atp']['supplier'] === 'SMOKE Malouf' && (int) $d['atp']['lead_time_days'] === 5 && $d['atp']['by'] === gmdate('Y-m-d', strtotime('+5 days')), '5 Queens: SMOKE Malouf in 5 days (no location holds 5)');
ok($d['atp']['cost'] === '999.00' || (float) $d['atp']['cost'] === 999.0, '…its cost for Nora');
[, $d] = screen($sam, '/find/atp?variant=' . $q . '&qty=5');
ok($d['atp']['cost'] === null && $d['atp']['cost_withheld'] === true, '…withheld from Sam (the tools say the word; the screen shows nothing)');
[, $h] = frag($sam, '/find/atp?variant=' . $q . '&qty=5');
ok(!str_contains($h, '999.00') && stripos($h, 'withheld') === false && str_contains($h, 'SMOKE Malouf can ship in 5 days'), '…the line for Sam: no cost, no "withheld"');
$tomorrow = gmdate('Y-m-d', strtotime('+1 day'));
[$c, $d] = screen($sam, '/find/atp?variant=' . $q . '&qty=5&by=' . $tomorrow);
ok($d['atp']['can_promise'] === false && $d['atp']['reason'] === 'a supplier has it, but not by ' . $tomorrow, '5 by tomorrow: "a supplier has it, but not by ' . $tomorrow . '"');
[$c, $h] = frag($sam, '/find/atp?variant=' . $q . '&qty=5&by=' . $tomorrow);
ok(str_contains($h, 'alert alert-warning') && str_contains($h, 'A supplier has it, but not by'), '…the warning box');
[$c, $d] = screen($sam, '/find/atp?variant=' . $w['fnd_king']);
ok($d['atp']['can_promise'] === false && $d['atp']['reason'] === 'not in stock and no supplier offers it', 'the Foundation King: "not in stock and no supplier offers it"');
[$c, , $r] = screen($sam, '/find/atp?variant=' . $q . '&qty=0');
ok($c === 422 && msg(json_decode($r['body'], true)) === 'A promise is for at least one', 'qty 0: the function\'s sentence as a 422');
[$c] = screen($sam, '/find/atp?variant=' . $q . '&qty=1000');
ok($c === 422, 'qty 1000: 422');
[$c, , $r] = screen($sam, '/find/atp?variant=' . $q . '&by=tomorrow');
ok($c === 422 && msg(json_decode($r['body'], true)) === 'That is not a date.', 'by=tomorrow: "That is not a date."');
[$c] = screen($sam, '/find/atp?variant=999999');
ok($c === 404, 'a variant that is not there: 404');
echo "2. The pick list\n";
[$c, $h] = frag($sam, '/find/pick?q=SMOKE-NW-CR-Q');
ok($c === 200 && str_contains($h, 'id="pick-results"') && preg_match('~<button type="button"[^>]*id="pick-' . $q . '" data-variant-id="' . $q . '"\s+data-sku="SMOKE-NW-CR-Q" data-label="SMOKE Cloudrest Hybrid, Queen" data-retail="999.00" data-state="in_stock">SMOKE-NW-CR-Q — SMOKE Cloudrest Hybrid, Queen · 999\.00 · in stock</button>~', $h) === 1, 'a button per variant with its data — "SMOKE-NW-CR-Q — SMOKE Cloudrest Hybrid, Queen · 999.00 · in stock"');
[$c, $h] = frag($sam, '/find/pick?q=b');
ok(str_contains($h, 'Type a SKU, GTIN or a name') && !str_contains($h, '<button'), 'under 2 characters: the hint, no list');
[$c, $h] = frag($sam, '/find/pick?q=bulkline&limit=50');
ok(substr_count($h, '<button') === 20, 'the limit is capped at 20');
[$c, $h] = frag($sam, '/find/pick?q=bulkline&limit=3');
ok(substr_count($h, '<button') === 3, '…and honoured below it');
[$c, $h] = frag($sam, '/find/pick?q=cloudrest&size=queen');
ok(substr_count($h, '<button') === 3, 'size narrows the list (three Queens)');
[$c, $d] = screen($sam, '/find/pick?q=850123450035');
ok(($d['results'][0]['variant_id'] ?? 0) === $q, 'JSON: by GTIN, the Queen');
finish();
