<?php
/** The availability partial (find.md "Proof — The availability partial"): the full shape, the ranking, stale and removed, the cost column, the bundle, the compact picker. */
require __DIR__ . '/lib.php';
$w = find_world();
$nora = as_member(40); $sam = as_member(41);
$q = $w['queen']; $twin = $w['twin']; $set = $w['set_q'];
$mq = lv_of($w['src_malouf'], 'NW-CR-Q'); $zq = (int) one("SELECT lv.id FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = :s AND lv.variant_id = :v", ['s' => $w['src_zinus_feed'], 'v' => $q]);
$mt = lv_of($w['src_malouf'], 'NW-CR-T'); $zt = (int) one("SELECT lv.id FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = :s AND lv.variant_id = :v", ['s' => $w['src_zinus_feed'], 'v' => $twin]);
$cq = (int) one("SELECT lv.id FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = :s AND lv.variant_id = :v", ['s' => $w['src_casper'], 'v' => $q]);
$pq = (int) one("SELECT lv.id FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = :s AND lv.variant_id = :v", ['s' => $w['src_paused'], 'v' => $q]);
$pos = static fn (string $h, string $needle): int => ($p = strpos($h, $needle)) === false ? -1 : $p;
echo "1. The full shape — the Queen\n";
psql_exec("UPDATE listing_variants SET availability = 'pre_order' WHERE id = $zq");
[$c, $h] = frag($nora, '/find/availability?variant=' . $q);
ok($c === 200 && str_contains($h, 'id="availability-' . $q . '"'), 'the partial answers availability-{id}');
ok(preg_match('~id="availability-' . $q . '-state"><span[^>]*>In stock — ships today</span> <span class="text-muted">· On order: 2</span>~', $h) === 1, 'the state line: "In stock — ships today" and "On order: 2" (the sent stock PO)');
ok(preg_match('~id="availability-' . $q . '-own-' . $w['wh'] . '"><td>SMOKE Warehouse</td><td class="text-end">4</td><td class="text-end">1</td><td class="text-end">0</td><td class="text-end">3</td>~', $h) === 1, 'own stock: Warehouse 4 on hand · 1 allocated · 0 floor · 3 available');
ok(!str_contains($h, 'id="availability-' . $q . '-own-' . $w['sr'] . '"'), '…the Showroom holds no Queen: no row');
$o1 = $pos($h, 'id="availability-' . $q . '-offer-' . $mq . '"'); $o2 = $pos($h, 'id="availability-' . $q . '-offer-' . $zq . '"');
ok($o1 > 0 && $o2 > $o1, 'offers ranked: Malouf in stock before Zinus\'s pre-order');
ok(str_contains($h, 'pre order'), '…the pre-order chip shows');
$r1 = $pos($h, 'id="availability-' . $q . '-reference-' . $cq . '"'); $r2 = $pos($h, 'id="availability-' . $q . '-reference-' . $pq . '"');
ok($r1 > 0 && $r2 > $r1, 'references by price: the Casper site (999.00) before the paused store (1,899.00)');
ok(str_contains($h, '<th class="text-end">Cost</th>'), 'Nora sees the Cost column');
ok(preg_match('~id="availability-' . $q . '-offer-' . $zq . '">.*?<td class="text-end">499\.00</td>~s', $h) === 1, '…with Zinus\'s cost 499.00');
psql_exec("UPDATE listing_variants SET availability = 'out_of_stock' WHERE id = $zq");
[$c, $h] = frag($sam, '/find/availability?variant=' . $q);
ok($c === 200 && !str_contains($h, '>Cost<') && !str_contains($h, '499.00') && stripos($h, 'withheld') === false, 'Sam: no Cost column, no cost anywhere, no "withheld" word');
psql_exec('UPDATE inv_settings SET sales_sees_cost = true');
[$c, $h] = frag($sam, '/find/availability?variant=' . $q);
ok(str_contains($h, '<th class="text-end">Cost</th>') && str_contains($h, '499.00'), '…the Cost column appears for Sam when sales_sees_cost is on');
psql_exec('UPDATE inv_settings SET sales_sees_cost = false');
echo "2. Ranking, stale and removed — the Twin\n";
[$c, $h] = frag($nora, '/find/availability?variant=' . $twin);
$a = $pos($h, 'id="availability-' . $twin . '-offer-' . $zt . '"'); $b = $pos($h, 'id="availability-' . $twin . '-offer-' . $mt . '"');
ok($a > 0 && $b > $a, 'Zinus in stock at 3 days (cost 349.50) ranks before Malouf in stock at 5 days (699.00) — the cheaper first');
ok(preg_match('~id="availability-' . $twin . '-state"><span[^>]*>From SMOKE Zinus in 3 days</span>~', $h) === 1, 'the state line names the best supplier and its days');
ok(preg_match('~id="availability-' . $twin . '-own-' . $w['ret'] . '" ?[^>]*>|class="text-muted" id="availability-' . $twin . '-own-' . $w['ret'] . '"~', $h) === 1 && str_contains($h, 'not sellable'), 'the Returns location is listed muted, "not sellable"');
psql_exec("UPDATE listing_variants SET last_seen_at = now() - interval '5 hours' WHERE id = $mt");
[$c, $h] = frag($nora, '/find/availability?variant=' . $twin);
ok(preg_match('~id="availability-' . $twin . '-offer-' . $mt . '">.*?stale</span>~s', $h) === 1, 'an offer not seen within twice its schedule wears the stale chip');
psql_exec("UPDATE listing_variants SET last_seen_at = now(), removed_at = now() WHERE id = $zt");
[$c, $h] = frag($nora, '/find/availability?variant=' . $twin);
$a = $pos($h, 'id="availability-' . $twin . '-offer-' . $zt . '"'); $b = $pos($h, 'id="availability-' . $twin . '-offer-' . $mt . '"');
ok($a > $b && $b > 0 && preg_match('~class="text-decoration-line-through text-muted" id="availability-' . $twin . '-offer-' . $zt . '"~', $h) === 1, 'a removed offer goes last, struck through');
ok(preg_match('~id="availability-' . $twin . '-offer-' . $zt . '">.*?removed</span>~s', $h) === 1, '…marked "removed"');
psql_exec("UPDATE listing_variants SET removed_at = NULL, last_seen_at = now() WHERE id IN ($zt, $mt)");
echo "3. The bundle\n";
[$c, $h] = frag($nora, '/find/availability?variant=' . $set);
ok($c === 200 && str_contains($h, 'id="availability-' . $set . '-components"'), 'a bundle answers its components table');
ok(preg_match('~SMOKE-NW-CR-Q</a>.*?<td class="text-end">1</td><td class="text-end">3</td><td class="text-end">3</td>~s', $h) === 1, '…the Queen: 1 per set, 3 available, 3 sets');
ok(preg_match('~SMOKE-FND-Q</a>.*?<td class="text-end">1</td><td class="text-end">0</td><td class="text-end">0</td><td class="text-end">—</td>~s', $h) === 1, '…the foundation: 0 available, no supplier (—)');
ok(str_contains($h, '>Unavailable<'), '…so the set is unavailable');
[$c, $h] = frag($nora, '/find/availability?variant=' . $set . '&compact=1&qty=1&field=lines[0]');
ok(str_contains($h, 'Sold as its components — add them as lines') && !str_contains($h, 'type="radio"'), 'compact: "Sold as its components — add them as lines", no radios');
[$c] = frag($nora, '/find/availability?variant=999999');
ok($c === 404, 'a variant that is not there: 404');
[$c, $h, $r] = frag(sign_on(46)[0], '/find/availability?variant=' . $q);
ok(!str_contains($h, 'availability-') && (header_of($r, 'HX-Redirect') !== null || $c === 302), 'Omar (no grant, his sign-on refused): no partial — sent to the launcher');
echo "4. The compact picker\n";
[$c, $h] = frag($sam, '/find/availability?variant=' . $q . '&compact=1&qty=1&field=line');
ok(preg_match('~name="line\[fulfilment\]" id="line-choice-stock-' . $w['wh'] . '" value="stock:' . $w['wh'] . '" checked~', $h) === 1, 'qty 1: stock at the Warehouse, checked (the recommendation)');
ok(str_contains($h, 'id="line-choice-pickup-' . $w['wh'] . '" value="pickup:' . $w['wh'] . '"') && str_contains($h, 'Pickup at SMOKE Warehouse'), '…pickup at the Warehouse');
ok(!str_contains($h, 'choice-stock-' . $w['sr']) && !str_contains($h, 'choice-pickup-' . $w['sr']), '…nothing at the Showroom (no Queen there)');
ok(str_contains($h, 'id="line-choice-dropship-' . $mq . '" value="dropship:' . $mq . '"') && !str_contains($h, 'choice-dropship-' . $zq), '…drop-ship from Malouf (in stock); not Zinus (out of stock)');
preg_match_all('~type="radio" name="line\[fulfilment\]" id="line-choice-([a-z0-9-]+)"~', $h, $rm);
ok(end($rm[1]) === 'backorder' && count($rm[1]) === 4, 'four radios, backorder the last (' . implode(', ', $rm[1]) . ')');
ok(preg_match('~<select class="form-select form-select-sm w-auto" name="line\[backorder_location\]" id="line-backorder-location"[^>]*>.*?<option value="' . $w['wh'] . '" selected>~s', $h) === 1, '…with its location select, the first warehouse by default');
ok(!str_contains($h, 'cost '), 'Sam: no cost on the drop-ship radio');
ok(preg_match('~id="atp-' . $q . '"[^>]*>\s*3 available at SMOKE Warehouse~', $h) === 1, 'the promise line beneath: "3 available at SMOKE Warehouse"');
[$c, $h] = frag($nora, '/find/availability?variant=' . $q . '&compact=1&qty=5&field=line&store=' . $w['sr']);
ok(!str_contains($h, 'choice-stock-') && !str_contains($h, 'choice-pickup-'), 'qty 5: the Warehouse radio is gone (3 available)');
ok(preg_match('~id="line-choice-dropship-' . $mq . '" value="dropship:' . $mq . '" checked~', $h) === 1, '…the recommended radio is the rank-1 supplier offer (Malouf)');
ok(str_contains($h, '· cost 999.00'), '…Nora sees its cost on the radio');
ok(preg_match('~<option value="' . $w['sr'] . '" selected>~', $h) === 1, '…the back order\'s location defaults to the form\'s store (store=)');
ok(preg_match('~id="atp-' . $q . '"[^>]*>\s*SMOKE Malouf can ship in 5 days~', $h) === 1, '…and the promise: "SMOKE Malouf can ship in 5 days"');
[$c, $h] = frag($nora, '/find/availability?variant=' . $q . '&compact=1&qty=1&field=lines[2]');
ok(str_contains($h, 'name="lines[2][fulfilment]"') && str_contains($h, 'id="lines-2-choice-stock-' . $w['wh'] . '"') && str_contains($h, 'name="lines[2][backorder_location]"'), 'field=lines[2]: lines[2][fulfilment], ids lines-2-choice-…');
[$c] = frag($nora, '/find/availability?variant=' . $q . '&compact=1&field=' . rawurlencode('x"><script>'));
ok($c === 422, 'a field prefix no form uses is refused');
[$c, $d] = screen($sam, '/find/availability?variant=' . $q);
ok($c === 200 && ($d['availability']['state'] ?? '') === 'in_stock' && array_key_exists('cost', $d['availability']['prices'] ?? []) && $d['availability']['prices']['cost'] === null, 'JSON: inv_availability() as the function answers it — cost null for Sam');
finish();
