<?php
/** The bridge (find.md "Proof — The bridge"): the gate (loopback, HMAC, ±30 s), the op, the caller, the right, the run, skipped and too many, the wall, the rows' source, and an eval run that writes nothing. */
require __DIR__ . '/lib.php';
$w = find_world();
$m = $w['src_malouf']; $cs = $w['src_casper']; $z = $w['src_zinus_feed'];
$body = static fn (int $member, array $args = ['q' => 'cloudrest'], array $more = []): array => array_merge(['op' => 'source_search', 'caller' => ['kind' => 'member', 'member_id' => $member], 'door' => 'mcp', 'run_id' => null, 'request_id' => 'smoke-bridge-' . bin2hex(random_bytes(4)), 'is_eval' => false, 'args' => $args], $more);
echo "1. The gate\n";
[$c, $b] = bridge($body(41), ['sign' => false]);
ok($c === 401 && ($b['error']['code'] ?? '') === 'unauthorized', 'no X-INV-Bridge header: 401');
[$c, $b] = bridge($body(41), ['key' => str_repeat('0', 64)]);
ok($c === 401, 'a wrong HMAC: 401');
[$c, $b] = bridge($body(41), ['skew' => -31]);
ok($c === 401, 'a timestamp 31 seconds old: 401');
[$c, $b] = bridge($body(41), ['skew' => 25]);
ok($c === 200, '…25 seconds ahead is inside the window');
$unit = trim((string) shell_exec('php -r ' . escapeshellarg('require "' . dirname(__DIR__, 3) . '/app/bootstrap.php"; require "' . dirname(__DIR__, 3) . '/app/features/find/bridge.php";'
    . ' $raw = "{}"; $ts = time(); $sig = $ts . "." . hash_hmac("sha256", "inv-bridge:" . $ts . "." . hash("sha256", $raw), env("ACTIONS_RELAY_KEY"));'
    . ' echo json_encode([bridge_verify($raw, $sig, "10.0.0.7", $ts), bridge_verify($raw, $sig, "127.0.0.1", $ts), bridge_verify($raw, $sig, "::1", $ts), bridge_verify($raw . " ", $sig, "127.0.0.1", $ts), bridge_verify($raw, "garbage", "127.0.0.1", $ts)]);') . ' 2>&1'));
ok($unit === '["not_loopback",null,null,"bad_signature","bad_signature"]', 'bridge_verify(): a forged non-loopback address refused; 127.0.0.1 and ::1 pass; a changed body or a garbled header refused (' . $unit . ')');
[$c] = bridge($body(41), ['method' => 'GET']);
ok($c === 405, 'a GET: 405');
[$c, $b] = bridge(['op' => 'foo'] + $body(41));
ok($c === 404 && ($b['error']['code'] ?? '') === 'no_such_op', 'op "foo": 404 no_such_op');
[$c, $b] = bridge($body(99999));
ok($c === 403 && ($b['error']['code'] ?? '') === 'unknown_member', 'a member the mirror does not know: 403 unknown_member');
[$c, $b] = bridge(['caller' => ['kind' => 'agent', 'member_id' => 45]] + $body(45));
ok($c === 403 && ($b['error']['code'] ?? '') === 'unknown_member', 'a caller that is not of kind member: 403 unknown_member');
[$c, $b] = bridge($body(46));
ok($c === 403 && ($b['error']['code'] ?? '') === 'unknown_member', 'Omar (no grant — not admitted): 403');
[$c, $b] = bridge($body(43));
ok($c === 403 && ($b['error']['code'] ?? '') === 'insufficient_right' && str_contains($b['error']['message'], 'quote or take orders'), 'Vera: 403 insufficient_right, in words');
echo "2. A live ask\n";
$since = last_activity_id();
$before = written_counts();
[$c, $b] = bridge($body(41));
$asked = array_column($b['asked'] ?? [], 'status', 'source_id');
ok($c === 200 && $b['ok'] === true && $b['query'] === 'cloudrest' && $b['eval'] === false, 'Sam asks "cloudrest": ok');
ok(($asked[$m] ?? '') === 'ok' && ($asked[$cs] ?? '') === 'ok' && count($asked) === 2, '…asked Malouf and the Casper site, both ok (every searchable source by default)');
$a0 = array_values(array_filter($b['asked'], static fn ($x) => $x['source_id'] === $m))[0];
ok($a0['pull_id'] > 0 && $a0['listings_seen'] >= 1 && isset($a0['ms']) && $a0['error'] === null, '…each with its pull, what it saw and how long it took');
$matched = array_values(array_filter($b['rows'], static fn ($r) => $r['matched']));
ok(count($matched) >= 6 && in_array('SMOKE-NW-CR-Q', array_column($matched, 'our_sku'), true), 'rows with matched and our SKU (' . count($b['rows']) . ' rows, ' . count($matched) . ' matched)');
ok(count(array_filter($b['rows'], static fn ($r) => $r['cost_withheld'] !== true || $r['cost_price'] !== null)) === 0, 'the wall for Sam: every row cost_withheld, no cost');
ok(written_counts()['pulls'] === $before['pulls'] + 2, 'two search pulls written');
$logs = q("SELECT * FROM activity_log WHERE action = 'source.search' AND id > :s ORDER BY id", ['s' => $since]);
ok(count($logs) === 2 && count(array_filter($logs, static fn ($l) => $l['source'] === 'mcp' && (int) $l['actor_member_id'] === 41 && $l['agent_run_id'] === null)) === 2, 'source.search rows say source mcp and the member');
ok(count(array_filter($logs, static fn ($l) => str_starts_with((string) $l['request_id'], 'smoke-bridge-'))) === 2, '…and carry the call\'s request id');
[$c, $b] = bridge($body(40, ['q' => 'cloudrest', 'sources' => [$m]]));
ok($c === 200 && count($b['asked']) === 1 && count(array_filter($b['rows'], static fn ($r) => $r['cost_withheld'] === false)) === count($b['rows']) && $b['rows'] !== [], 'Nora asks Malouf alone: her rows are not withheld (the wall opens for her)');
[$c, $b] = bridge($body(41, ['q' => 'cloudrest', 'sources' => [$z]]));
ok($c === 200 && ($b['asked'][0]['status'] ?? '') === 'skipped' && $b['rows'] === [], 'sources: [Zinus feed] — skipped (no live search), never a refusal');
[$c, $b] = bridge($body(41, ['q' => 'cloudrest', 'sources' => [$m, $cs, $z, $w['src_paused'], $w['src_blocked'], 999]]));
ok($c === 422 && ($b['error']['code'] ?? '') === 'invalid_argument', 'six sources: 422 invalid_argument');
[$c, $b] = bridge($body(41, ['q' => 'c']));
ok($c === 422 && ($b['error']['code'] ?? '') === 'invalid_argument', 'a one-character question: 422');
[$c, $b] = bridge($body(41, ['q' => 'cloudrest', 'limit' => 21]));
ok($c === 422, 'a limit of 21: 422');
[$c, $b] = bridge($body(41, ['q' => 'cloudrest', 'sources' => [$m, $w['src_blocked']]]));
$st = array_column($b['asked'], 'status', 'source_id');
ok(($st[$m] ?? '') === 'ok' && ($st[$w['src_blocked']] ?? '') === 'skipped', 'the blocked source is not searchable: skipped beside an ok');
echo "3. An agent's run\n";
$since = last_activity_id();
[$c, $b] = bridge($body(45, ['q' => 'cloudrest', 'sources' => [$cs]], ['door' => 'agent', 'run_id' => 4242]));
$l = q("SELECT * FROM activity_log WHERE action = 'source.search' AND id > :s", ['s' => $since]);
ok($c === 200 && count($l) === 1 && $l[0]['source'] === 'agent' && (int) $l[0]['agent_run_id'] === 4242 && (int) $l[0]['actor_member_id'] === 45, 'door "agent" with run_id: the row says agent, the run and the expert');
echo "4. Under an eval run nothing persists\n";
$before = written_counts();
$since = last_activity_id();
[$c, $b] = bridge($body(41, ['q' => 'cloudrest'], ['is_eval' => true]));
ok($c === 200 && $b['eval'] === true && $b['rows'] !== [] && isset($b['rows'][0]['title'], $b['rows'][0]['price']) && $b['rows'][0]['matched'] === false, 'is_eval: eval true, rows from the connector (title, size, sku, price, availability), matched false');
ok(count(array_filter($b['asked'], static fn ($a) => $a['status'] === 'ok' && $a['pull_id'] === null)) === 2, '…each source ok with no pull');
ok(written_counts() === $before, '…no new pulls, listings, listing variants or snapshots (' . json_encode(written_counts()) . ')');
$l = q("SELECT * FROM activity_log WHERE action = 'source.search' AND id > :s", ['s' => $since]);
ok(count($l) === 2 && count(array_filter($l, static fn ($x) => after_of($x)['eval'] === true)) === 2, '…one source.search row per source, after.eval true');
echo "5. Not on the public name\n";
ok(str_contains((string) file_get_contents(dirname(__DIR__, 3) . '/deploy/apache-inventory.conf'), "RewriteRule ^/internal/ - [R=404,L]"), 'the public vhost answers 404 under /internal/ (deploy/apache-inventory.conf)');
if (getenv('INV_APP') === 'apache') {
    $r = req('POST', '/internal/bridge.php', ['raw' => '{}']);
    ok($r['code'] === 404, 'under Apache the public name answers 404 for the bridge (the call reached it only on the internal vhost)');
}
finish();
