<?php
/** Find (find.md "Proof — Find"): the query, the chips, the cap, the push URL, the cards, cost behind the wall, "Sell this", Watch, the log. */
require __DIR__ . '/lib.php';
$w = find_world();
$nora = as_member(40); $sam = as_member(41); $vera = as_member(43); $ann = as_member(44);
$skus = static fn (array $d): array => array_column($d['results'] ?? [], 'sku');
echo "1. The query\n";
[$c, $d] = screen($sam, '/find?q=' . rawurlencode('cloudrest hybrid'));
$s = $skus($d);
$hy = array_values(array_filter($s, static fn ($x) => str_starts_with($x, 'SMOKE-NW-CR-')));
ok($c === 200 && count($hy) === 6, '"cloudrest hybrid": the six sizes of the hybrid (' . implode(' ', $hy) . ')');
$firstFnd = null; foreach ($s as $i => $x) { if (str_starts_with($x, 'SMOKE-FND-')) { $firstFnd = $i; break; } }
$lastHy = max(array_keys(array_filter($s, static fn ($x) => str_starts_with($x, 'SMOKE-NW-CR-'))));
ok($firstFnd === null || $firstFnd > $lastHy, 'the foundations (if any) after the hybrids — ranked by match');
[, $d] = screen($sam, '/find?q=SMOKE-NW-CR-Q');
ok(($d['results'][0]['sku'] ?? '') === 'SMOKE-NW-CR-Q' && abs($d['results'][0]['score'] - 9.0) < 0.01, 'by SKU exact: the Queen first, score 9');
[, $d] = screen($sam, '/find?q=850123450035');
ok(($d['results'][0]['sku'] ?? '') === 'SMOKE-NW-CR-Q' && abs($d['results'][0]['score'] - 10.0) < 0.01, 'by GTIN (12 digits): the Queen, score 10');
[, $d] = screen($sam, '/find?q=00850123450035');
ok(($d['results'][0]['sku'] ?? '') === 'SMOKE-NW-CR-Q' && abs($d['results'][0]['score'] - 10.0) < 0.01, 'by GTIN-14 (normalised): the Queen, score 10');
[, $d] = screen($sam, '/find?q=' . rawurlencode($w['king_mpn']));
ok(($d['results'][0]['sku'] ?? '') === 'SMOKE-NW-CR-K', 'by MPN (' . $w['king_mpn'] . '): the King');
[, $d] = screen($sam, '/find?q=Cloudrest');
ok(count(array_filter($skus($d), static fn ($x) => str_starts_with($x, 'SMOKE-NW-CR-'))) === 6 && in_array('SMOKE-SET-Q', $skus($d), true), 'by the brand\'s word: the hybrid\'s sizes and the set');
[, $d] = screen($sam, '/find?q=cloudrest&size=queen');
ok($skus($d) !== [] && array_unique(array_column($d['results'], 'size_key')) === ['queen'], 'size=queen: only Queens (' . implode(' ', $skus($d)) . ')');
ok(count($skus($d)) === 3, '…three of them — the hybrid, the foundation and the set');
echo "2. The chips\n";
[, $d] = screen($sam, '/find?type=foundation');
ok($skus($d) !== [] && count(array_filter($skus($d), static fn ($x) => !str_starts_with($x, 'SMOKE-FND-'))) === 0, 'the type chip alone runs a query: foundations only (' . count($skus($d)) . ')');
[, $d] = screen($sam, '/find?firmness=medium');
ok(count($skus($d)) === 6 && count(array_filter($skus($d), static fn ($x) => str_starts_with($x, 'SMOKE-NW-CR-'))) === 6, 'the firmness chip (medium): the hybrid\'s six sizes');
$band = static function (int $n) use ($sam): array { $b = FIND_BANDS_PROOF[$n]; return screen($sam, '/find?q=smoke&' . http_build_query(array_filter(['price_min' => $b[0], 'price_max' => $b[1]], static fn ($v) => $v !== null)))[1]['results'] ?? []; };
const FIND_BANDS_PROOF = [1 => [null, '499.99'], 2 => ['500', '999.99'], 3 => ['1000', '1999.99'], 4 => ['2000', null]];
$r1 = $band(1); ok($r1 !== [] && max(array_map('floatval', array_column($r1, 'retail_price'))) < 500, 'price band 1: everything under 500 (' . count($r1) . ')');
$r2 = $band(2); $p2 = array_map('floatval', array_column($r2, 'retail_price')); ok($r2 !== [] && min($p2) >= 500 && max($p2) <= 999.99, 'price band 2: 500–999.99 (' . implode(' ', array_column($r2, 'sku')) . ')');
$r3 = $band(3); $p3 = array_map('floatval', array_column($r3, 'retail_price')); ok($r3 !== [] && min($p3) >= 1000 && max($p3) <= 1999.99, 'price band 3: 1,000–1,999.99 (' . implode(' ', array_column($r3, 'sku')) . ')');
$r4 = $band(4); ok($r4 === [], 'price band 4: nothing at 2,000 and over');
[, $d] = screen($sam, '/find?q=cloudrest+hybrid&in_stock=1');
$st = array_column($d['results'], 'state', 'sku');
ok(isset($st['SMOKE-NW-CR-Q']) && $st['SMOKE-NW-CR-Q'] === 'in_stock', '"in stock only": the Queen stays (our own 3)');
ok(isset($st['SMOKE-NW-CR-K']) && $st['SMOKE-NW-CR-K'] === 'from_supplier', '…the King stays on a supplier\'s offer (Zinus in stock; ours is a floor model)');
[, $d] = screen($sam, '/find?q=cloudrest&in_stock=1');
ok(!in_array('SMOKE-FND-K', $skus($d), true) && in_array('SMOKE-FND-K', $skus(screen($sam, '/find?q=cloudrest')[1]), true), '…the Foundation King, which nobody holds or offers, goes');
[, $d] = screen($sam, '/find?q=cloudrest+hybrid&ships_within=3');
$s3 = $skus($d);
ok(in_array('SMOKE-NW-CR-K', $s3, true) && in_array('SMOKE-NW-CR-T', $s3, true), 'ships within 3: the King and the Twin stay (Zinus, 3 days)');
ok(!in_array('SMOKE-NW-CR-CK', $s3, true), '…the Cal King goes (Malouf, 5 days)');
ok(in_array('SMOKE-NW-CR-Q', $s3, true), '…the Queen stays (our own stock: 0 days)');
[, $d] = screen($sam, '/find?q=cloudrest&type=nonsense&firmness=wobbly&ships_within=5&price_min=-3');
ok(count($skus($d)) === count($skus(screen($sam, '/find?q=cloudrest')[1])), 'unknown chip values are ignored, never refused');
echo "3. The empty Find, the limit, the push URL\n";
$before = (int) one("SELECT count(*) FROM activity_log WHERE action = 'screen.view' AND screen = 'find'");
[$c, $h] = html($sam, '/find');
ok($c === 200 && str_contains($h, 'id="find-hint"') && str_contains($h, 'Type a product, brand, SKU, GTIN or MPN — or pick a size') && !str_contains($h, 'id="find-results"'), 'an empty Find: the box, the chips, the hint — no results region');
$row = q("SELECT * FROM activity_log WHERE action = 'screen.view' AND screen = 'find' ORDER BY id DESC LIMIT 1")[0];
ok(after_of($row)['results'] === null, '…and no query ran (results null on the log row)');
[$c, $h] = html($sam, '/find?q=' . str_repeat('x', 121));
ok($c === 422 && str_contains($h, 'Keep it under 120 characters.'), 'a 121-character q: 422 "Keep it under 120 characters."');
[$c, $d] = screen($sam, '/find?q=bulkline');
ok(count($d['results']) === 50, 'fifty-five Bulkline variants: the first 50');
[$c, $h] = html($sam, '/find?q=bulkline');
ok(preg_match('~id="find-count">the first 50 — narrow it<~', $h) === 1, '…and the count line says "the first 50 — narrow it"');
[$c, $h, $r] = frag($sam, '/find?q=cloudrest&size=queen&in_stock=1');
ok(header_of($r, 'HX-Push-Url') === '/find?q=cloudrest&size=queen&in_stock=1', 'HX-Push-Url carries the query as sent (' . header_of($r, 'HX-Push-Url') . ')');
ok(preg_match('~<form [^>]*id="find-form"[^>]*>~', $h, $fm) === 1 && !str_contains($fm[0], 'hx-push-url') && str_contains($fm[0], 'hx-get="/find"'), 'the form is hx-get="/find" with no hx-push-url attribute');
[, $h] = html($sam, '/find?q=cloudrest&size=queen');
ok(preg_match('~class="btn btn-sm text-nowrap btn-touch btn-primary" id="find-chip-size-queen"~', $h) === 1, 'the active chip is btn-primary');
ok(preg_match('~href="/find\?q=cloudrest" hx-get="/find\?q=cloudrest" hx-target="\#page-content" class="[^"]*" id="find-chip-size-queen"~', $h) === 1, '…and its link toggles it off');
ok(preg_match('~href="/find\?q=cloudrest&amp;size=queen&amp;in_stock=1"[^>]*id="find-chip-in-stock"~', $h) === 1, 'the in-stock chip adds itself to the query');
echo "4. The cards\n";
$q = $w['queen']; $ck = $w['calking']; $fk = $w['fnd_king'];
[, $h] = html($nora, '/find?q=cloudrest');
ok(str_contains($h, 'id="find-card-' . $q . '"') && str_contains($h, 'data-variant-id="' . $q . '"'), 'a card per variant, data-variant-id on it');
ok(preg_match('~id="find-card-' . $q . '-state">In stock<~', $h) === 1, 'the Queen\'s state chip: In stock');
ok(preg_match('~id="find-card-' . $ck . '-state">From supplier<~', $h) === 1, 'the Cal King\'s: From supplier');
ok(preg_match('~id="find-card-' . $fk . '-state">Unavailable<~', $h) === 1, 'the Foundation King\'s: Unavailable');
ok(preg_match('~id="find-card-' . $q . '-prices">Retail 999\.00 · MAP 999\.00 · Cost 499\.50<~', $h) === 1, 'Nora\'s Queen card: retail, MAP and cost');
ok(preg_match('~id="find-card-' . $q . '-facts">3 available · best lead 0 days~', $h) === 1, 'the compact facts: "3 available · best lead 0 days"');
ok(preg_match('~id="find-card-' . $ck . '-facts">from SMOKE Malouf in 5 days · in stock~', $h) === 1, '…the Cal King: "from SMOKE Malouf in 5 days · in stock"');
ok(preg_match('~id="find-card-' . $q . '-availability" hx-get="/find/availability\?variant=' . $q . '" hx-trigger="intersect once, offerChanged from:body"~', $h) === 1, 'the availability region loads as it comes into view (intersect once) and on offerChanged');
ok(preg_match('~href="/orders/new\?variant=' . $q . '&amp;qty=1&amp;fulfilment=stock&amp;location=' . $w['wh'] . '"[^>]*id="find-card-' . $q . '-sell"~', $h) === 1, '"Sell this" on the Queen: stock at the Warehouse');
$ckLv = lv_of($w['src_malouf'], 'NW-CR-CK');
ok(preg_match('~href="/orders/new\?variant=' . $ck . '&amp;qty=1&amp;fulfilment=dropship&amp;listing_variant=' . $ckLv . '"[^>]*id="find-card-' . $ck . '-sell"~', $h) === 1, '…on the Cal King: drop-ship from Malouf\'s offer');
ok(preg_match('~href="/orders/new\?variant=' . $fk . '&amp;qty=1&amp;fulfilment=backorder"[^>]*id="find-card-' . $fk . '-sell"~', $h) === 1, '…on the Foundation King: a back order, no location');
ok(str_contains($h, 'id="find-card-' . $q . '-watch"') && str_contains($h, 'hx-target="#find-card-' . $q . '-watch-form"'), 'Watch opens the inline form under the card');
[, $hs] = html($sam, '/find?q=cloudrest');
ok(preg_match('~id="find-card-' . $q . '-prices">Retail 999\.00 · MAP 999\.00<~', $hs) === 1, 'Sam\'s Queen card: no cost');
[, $hv] = html($vera, '/find?q=cloudrest');
ok(preg_match('~id="find-card-' . $q . '-prices">Retail 999\.00 · MAP 999\.00<~', $hv) === 1, 'Vera\'s: no cost');
ok(stripos($hs . $hv, 'withheld') === false, 'no "withheld" word anywhere on Sam\'s or Vera\'s Find');
ok(!str_contains($hv, '-sell"') && !str_contains($hv, '-watch"'), 'Vera: no Sell this, no Watch (she holds neither right)');
[, $ha] = html($ann, '/find?q=cloudrest');
ok(!str_contains($ha, '-sell"'), 'Ann (external viewer): no Sell this');
ok(str_contains($hs, 'id="find-ask-sources"') && !str_contains($hv, 'id="find-ask-sources"'), '"Ask the sources now" for Sam (orders.write), not for Vera');
ok(!str_contains(html($sam, '/find?type=foundation')[1], 'id="find-ask-sources"'), '…and not without a query');
ok(preg_match('~data-screen="find" data-entity="variant" data-record-id=""~', $hs) === 1, 'the page is stamped data-screen="find" data-entity="variant"');
echo "5. The log\n";
$long = str_repeat('é', 119) . 'Z';
html($sam, '/find?q=' . rawurlencode($long) . '&size=queen&type=mattress&in_stock=1&ships_within=7');
$row = q("SELECT * FROM activity_log WHERE action = 'screen.view' AND screen = 'find' ORDER BY id DESC LIMIT 1")[0];
$a = after_of($row);
ok(mb_strlen($a['q']) === 120 && $a['size'] === 'queen' && $a['type'] === 'mattress' && $a['in_stock'] === true && $a['ships_within'] === '7' && is_int($a['results']), 'screen.view logged with q (≤ 120), the chips and the count');
ok((int) $row['actor_member_id'] === 41 && $row['source'] === 'web', '…as Sam, from the web');
finish();
