<?php
/** Ask the sources now (find.md "Proof — Live"): the fan-out shell, one source asked, the rows through the wall, the pull row, the log, paused / blocked / not searchable, the host's spacing. */
require __DIR__ . '/lib.php';
$w = find_world();
$nora = as_member(40); $sam = as_member(41); $vera = as_member(43);
$m = $w['src_malouf']; $cs = $w['src_casper']; $p = $w['src_paused']; $bl = $w['src_blocked']; $z = $w['src_zinus_feed'];
echo "1. The fan-out\n";
[$c, $h] = frag($sam, '/find/sources?q=cloudrest');
ok($c === 200 && str_contains($h, 'id="find-live-' . $m . '"') && str_contains($h, 'id="find-live-' . $cs . '"'), 'a placeholder card for Malouf and for the Casper site (Shopify: search)');
ok(!str_contains($h, 'id="find-live-' . $z . '"'), '…none for the Zinus feed (a feed has no live search)');
ok(!str_contains($h, 'id="find-live-' . $p . '"') && !str_contains($h, 'id="find-live-' . $bl . '"'), '…none for the paused source nor the blocked one');
ok(str_contains($h, 'hx-get="/find/source-search?source=' . $m . '&amp;q=cloudrest" hx-trigger="load" hx-swap="outerHTML"'), 'each card asks its own source on load (the browser fans out)');
ok(str_contains($h, 'htmx-indicator') && str_contains($h, '<noscript><a href="/find/source-search?source=' . $m . '&amp;q=cloudrest"'), '…with a spinner, and an "Ask" link without JavaScript');
[$c, $h] = frag($sam, '/find/sources?q=cloudrest&size=queen');
ok(str_contains($h, 'source=' . $m . '&amp;q=cloudrest&amp;size=queen'), 'the size travels to each ask');
[$c] = frag($vera, '/find/sources?q=cloudrest');
ok($c === 403, 'Vera (no orders.write): 403');
[$c] = frag($sam, '/find/sources?q=c');
ok($c === 422, 'a one-character question: 422');
[$c, $h] = html($sam, '/find/sources?q=cloudrest');
ok($c === 200 && str_contains($h, 'id="find-live"') && str_contains($h, 'Ask the sources'), 'without HTMX: a page holding the cards');
echo "2. One source asked — Malouf\n";
$before = written_counts();
$since = last_activity_id();
[$c, $h, $r] = frag($nora, '/find/source-search?source=' . $m . '&q=cloudrest');
ok($c === 200 && preg_match('~id="find-live-' . $m . '-status">(\d+) listings · (\d+) matched to ours<~', $h, $sm) === 1 && (int) $sm[2] >= 6, 'Malouf answers ok: "' . ($sm[1] ?? '?') . ' listings · ' . ($sm[2] ?? '?') . ' matched to ours"');
ok(header_of($r, 'HX-Trigger') === 'offerChanged', 'the answer carries HX-Trigger: offerChanged (every revealed card reloads)');
$qLv = lv_of($m, 'NW-CR-Q');
ok(str_contains($h, 'id="find-live-' . $m . '-row-' . $qLv . '"') && preg_match('~id="find-live-' . $m . '-row-' . $qLv . '-sku"[^>]*><code>SMOKE-NW-CR-Q</code>~', $h) === 1, 'the matched Queen row links our SKU');
$fnd = q("SELECT lv.id FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = :s AND l.title = 'CloudRest Foundation'", ['s' => $m]);
$fid = (int) ($fnd[0]['id'] ?? 0);
ok($fid > 0 && str_contains($h, 'id="find-live-' . $m . '-row-' . $fid . '"') && str_contains($h, 'not in our catalog'), 'a listing the search found and the pulls never had: written, "not in our catalog"');
ok(str_contains($h, 'id="find-live-' . $m . '-row-' . $fid . '-match"') && str_contains($h, 'href="/matching/?source=' . $m . '&amp;q=CloudRest+Foundation"'), '…with the match-queue link for Nora (listings.match)');
$after = written_counts();
ok($after['pulls'] === $before['pulls'] + 1, 'Nora\'s ask wrote one pull row');
$pull = last_pull($m, 'search');
ok($pull !== null && $pull['kind'] === 'search' && in_array($pull['status'], ['ok', 'partial'], true) && $pull['query'] === 'cloudrest' && (int) $pull['started_by'] === 40, 'a source_pulls row of kind search, with the query and who asked');
ok($after['listings'] >= $before['listings'] + 1 && $after['lvs'] >= $before['lvs'] + 1, 'the listings written: a new listing and listing variant (' . ($after['lvs'] - $before['lvs']) . ')');
ok($after['snapshots'] >= $before['snapshots'] + 1, '…and a snapshot for the new one');
$log = last_log('source.search', $since);
$a = after_of($log);
ok($log !== null && (int) $log['source_id'] === $m && $a['query'] === 'cloudrest' && $a['listings_seen'] >= 1 && (int) $log['actor_member_id'] === 40 && $log['source'] === 'web', 'source.search logged by the function: source_id, the query, listings_seen, Nora, web');
ok(isset($a['pull_id']) && (int) $a['pull_id'] > 0 && isset($a['ms']), '…with the pull and the time it took');
[$c, $hs] = frag($sam, '/find/source-search?source=' . $m . '&q=cloudrest');
ok($c === 200 && str_contains($hs, 'not in our catalog') && !str_contains($hs, '-match"'), '…the unmatched row without the match link for Sam');
echo "3. The reference source — no cost\n";
[$c, $h] = frag($nora, '/find/source-search?source=' . $cs . '&q=cloudrest');
ok($c === 200 && str_contains($h, 'id="find-live-' . $cs . '-status"') && str_contains($h, 'reference'), 'the Casper site answers (a reference)');
preg_match('~<tr id="find-live-' . $cs . '-row-\d+">(.*?)</tr>~s', $h, $row);
ok(isset($row[1]) && substr_count($row[1], '<td') === 6, '…its rows have no cost cell even for Nora (6 cells; a supplier\'s have 7)');
preg_match('~<tr id="find-live-' . $m . '-row-\d+">(.*?)</tr>~s', frag($nora, '/find/source-search?source=' . $m . '&q=cloudrest')[1], $row2);
ok(isset($row2[1]) && substr_count($row2[1], '<td') === 7, '…a supplier\'s row has the cost cell for Nora');
preg_match('~<tr id="find-live-' . $m . '-row-\d+">(.*?)</tr>~s', $hs, $row3);
ok(isset($row3[1]) && substr_count($row3[1], '<td') === 6, '…and not for Sam');
echo "4. Paused, blocked, not searchable\n";
[$c, $h] = frag($sam, '/find/source-search?source=' . $p . '&q=meadowlark');
ok($c === 200 && preg_match('~id="find-live-' . $p . '-status">paused<~', $h) === 1 && str_contains($h, 'from the last pull:'), 'the paused source asked directly: "paused", from the last pull');
ok(preg_match_all('~id="find-live-' . $p . '-row-\d+"~', $h) >= 1, '…with the last pull\'s rows');
[$c, $h] = frag($sam, '/find/source-search?source=' . $bl . '&q=cloudrest');
ok($c === 200 && str_contains($h, 'blocked — the source is backing off') && str_contains($h, 'bg-soft-danger'), 'the blocked source: "blocked — the source is backing off" (danger)');
[$c] = frag($sam, '/find/source-search?source=' . $z . '&q=cloudrest');
ok($c === 404, 'the feed (no search): 404 "Source not found."');
[$c] = frag($sam, '/find/source-search?source=999999&q=cloudrest');
ok($c === 404, 'a source that is not there: 404');
[$c, $h] = frag($vera, '/find/source-search?source=' . $m . '&q=cloudrest');
ok($c === 403 && str_contains($h, 'quote or take orders'), 'Vera: 403 in words');
[$c] = frag($sam, '/find/source-search?source=' . $m . '&q=' . str_repeat('y', 121));
ok($c === 422, 'a 121-character question: 422');
echo "5. The host's spacing\n";
$t0 = microtime(true);
$from = count(fix_log());
frag($sam, '/find/source-search?source=' . $m . '&q=cloudrest');
frag($sam, '/find/source-search?source=' . $cs . '&q=cloudrest');
$reqs = array_values(array_filter(array_slice(fix_log(), $from), static fn ($l) => $l !== null));
$ts = array_column($reqs, 't');
$gaps = [];
for ($i = 1; $i < count($ts); $i++) { $gaps[] = $ts[$i] - $ts[$i - 1]; }
ok(count($ts) >= 2 && min($gaps) >= 0.95, 'two asks to one host: every request spaced ≥ 1 s by the host lock (' . count($ts) . ' requests, the closest ' . round(min($gaps ?: [0]), 2) . ' s)');
finish();
