<?php
/** Watches (find.md "Proof — Watches"): the form, set and its refusals, the list, clear, and firing — once per state change — with the notice, the email, the text and the agent's dispatch. */
require __DIR__ . '/lib.php';
$w = find_world();
$nora = as_member(40); $sam = as_member(41); $vera = as_member(43);
$fk = $w['fnd_king']; $q = $w['queen'];
$mq = lv_of($w['src_malouf'], 'NW-CR-Q');
$wid = static fn (array $b): int => (int) ($b['record_id'] ?? 0);
$watch = static fn (int $id): array => q('SELECT * FROM watches WHERE id = :i', ['i' => $id])[0] ?? [];
echo "1. The inline form\n";
[$c, $h] = frag($sam, '/watches/form?variant=' . $fk . '&return_to=' . rawurlencode('/find?q=cloudrest'));
ok($c === 200 && str_contains($h, 'id="watch-form"') && str_contains($h, 'name="variant" value="' . $fk . '"') && str_contains($h, 'name="return_to" value="/find?q=cloudrest"'), 'the form for a variant: its target and where to land');
ok(preg_match('~<option value="back_in_stock" selected~', $h) === 1, '…back_in_stock chosen by default (the Foundation King is not in stock)');
ok(!str_contains($h, 'value="cost_below"') && !str_contains($h, 'watch-form-field-agent'), '…Sam is offered no cost_below and no agent');
foreach (['kind', 'threshold', 'text_me', 'note'] as $f) { ok(str_contains($h, 'id="watch-form-field-' . $f . '"'), "…the field watch-form-field-$f"); }
[$c, $h] = frag($nora, '/watches/form?variant=' . $q);
ok(preg_match('~<option value="price_below" selected~', $h) === 1 && str_contains($h, 'value="cost_below"') && str_contains($h, 'id="watch-form-field-agent"') && str_contains($h, 'SMOKE Inventory expert'), 'Nora on the Queen (in stock): price_below by default, cost_below and the agent offered');
ok(preg_match('~id="watch-form-field-threshold"[^>]*data-prefill="999.00"[^>]*value="999.00"~', $h) === 1, '…the threshold prefilled with the best offer\'s price (999.00)');
[$c] = frag($vera, '/watches/form?variant=' . $q);
ok($c === 403, 'Vera (no watches.own): 403');
[$c] = frag($sam, '/watches/form?variant=999999');
ok($c === 404, 'a variant that is not there: 404');
[$c, $h] = html($sam, '/watches/form?variant=' . $fk);
ok($c === 200 && str_contains($h, 'id="watch-form-page-header"') && str_contains($h, 'id="watch-form"'), 'without HTMX: the form as a page');
echo "2. Setting\n";
$since = last_activity_id();
[$c, $b] = act($sam, '/watches/save.php', ['kind' => 'back_in_stock', 'variant' => $fk, 'text_me' => '1', 'note' => 'SMOKE tell me', 'return_to' => '/find?q=cloudrest']);
$s1 = $wid($b);
ok($c === 200 && $b['ok'] === true && $s1 > 0 && $b['location'] === '/find?q=cloudrest&notice=watched#watch-row-' . $s1 && $b['refresh'] === 'watchChanged', 'Sam watches the Foundation King back in stock — landing back on Find, the location ending in the id');
ok($watch($s1)['last_state'] === false && (int) $watch($s1)['member_id'] === 41 && $watch($s1)['text_me'] === true, '…evaluated at once: last_state false; his, text_me on');
ok(($b['current'] ?? null) === false && str_starts_with((string) ($b['title'] ?? ''), 'Back in stock: '), '…the answer carries the title and the state now');
$l = last_log('watch.set', $since);
ok($l !== null && after_of($l)['watch_id'] === $s1 && after_of($l)['kind'] === 'back_in_stock' && after_of($l)['variant_id'] === $fk && after_of($l)['text_me'] === true && $l['source_id'] === null, 'watch.set logged (watch_id, kind, variant_id, text_me), no source_id for a variant');
[$c, $b] = act($sam, '/watches/save.php', ['kind' => 'price_below', 'listing_variant' => $mq, 'threshold' => '950']);
$s2 = $wid($b);
ok($c === 200 && $s2 > 0 && $b['location'] === '/watches/?notice=watched#watch-row-' . $s2, 'Sam watches Malouf\'s Queen offer under 950 (a listing variant) — landing on the list');
$l = last_log('watch.set', $since);
ok((int) $l['source_id'] === $w['src_malouf'] && after_of($l)['listing_variant_id'] === $mq && after_of($l)['threshold'] === '950', '…source_id on the log row: Malouf');
ok($watch($s2)['last_state'] === false, '…999.00 is not under 950: false');
[$c, $b] = act($sam, '/watches/save.php', ['kind' => 'back_in_stock', 'product' => $w['mattress']]);
$s3 = $wid($b);
ok($c === 200 && $s3 > 0 && $watch($s3)['last_state'] === true, 'a product watch, already true (a Queen on the shelf): last_state true at once');
[$c, $b] = act($sam, '/watches/save.php', ['kind' => 'back_in_stock', 'variant' => $q, 'threshold' => '5']);
ok($c === 422 && (fields($b)['threshold'] ?? '') === 'A threshold means nothing for back_in_stock.', 'a threshold on back_in_stock: "A threshold means nothing for back_in_stock."');
[$c, $b] = act($sam, '/watches/save.php', ['kind' => 'price_below', 'variant' => $q]);
ok($c === 422 && isset(fields($b)['threshold']), 'price_below without a threshold: 422 on the field');
[$c, $b] = act($sam, '/watches/save.php', ['kind' => 'lead_time_over', 'variant' => $q, 'threshold' => '2.5']);
ok($c === 422 && (fields($b)['threshold'] ?? '') === 'Whole days, 0 to 365.', 'lead_time_over in half days: "Whole days, 0 to 365."');
[$c, $b] = act($sam, '/watches/save.php', ['kind' => 'sideways', 'variant' => $q]);
ok($c === 422 && isset(fields($b)['kind']), 'an unknown kind: 422 on the field');
[$c, $b] = act($sam, '/watches/save.php', ['kind' => 'removed', 'variant' => $q, 'product' => $w['mattress']]);
ok($c === 422 && isset(fields($b)['target']), 'two targets: 422');
[$c, $b] = act($sam, '/watches/save.php', ['kind' => 'cost_below', 'variant' => $q, 'threshold' => '400']);
ok($c === 403 && msg($b) === 'You may not see cost or margin.', 'cost_below by Sam: 403 "You may not see cost or margin."');
[$c, $b] = act($nora, '/watches/save.php', ['kind' => 'cost_below', 'variant' => $q, 'threshold' => '400']);
$n1 = $wid($b);
ok($c === 200 && $n1 > 0, '…by Nora: set');
[$c, $b] = act($sam, '/watches/save.php', ['kind' => 'back_in_stock', 'variant' => $fk, 'agent' => '45']);
ok($c === 403 && str_contains(msg($b), 'Naming an agent'), 'naming the expert by Sam: 403 in words');
[$c, $b] = act($nora, '/watches/save.php', ['kind' => 'back_in_stock', 'variant' => $fk, 'agent' => '45']);
$n2 = $wid($b);
ok($c === 200 && $n2 > 0 && (int) $watch($n2)['agent_member_id'] === 45, '…by Nora: set, naming the expert');
[$c, $b] = act($nora, '/watches/save.php', ['kind' => 'removed', 'variant' => $q, 'agent' => '41']);
ok($c === 422 && (fields($b)['agent'] ?? '') === 'That agent is not here.', 'naming a person as the agent: "That agent is not here."');
[$c, $b] = act($sam, '/watches/save.php', ['kind' => 'back_in_stock', 'variant' => $fk]);
ok($c === 422 && msg($b) === 'You already watch that.', 'the same watch twice: 422 "You already watch that."');
ok((int) ($b['error']['record_id'] ?? 0) === $s1, '…naming the existing watch (record_id ' . $s1 . ')');
[$c, $b] = act($sam, '/watches/save.php', ['kind' => 'back_in_stock', 'variant' => '999999']);
ok($c === 404 && msg($b) === 'Variant not found.', 'a variant that is not there: 404 "Variant not found."');
[$c, $b] = act($vera, '/watches/save.php', ['kind' => 'back_in_stock', 'variant' => $fk]);
ok($c === 403, 'Vera: 403');
echo "3. The list\n";
[$c, $h] = html($sam, '/watches/');
ok($c === 200 && str_contains($h, 'id="watch-list-table"') && str_contains($h, 'id="watch-row-' . $s1 . '"') && str_contains($h, 'id="watch-row-' . $s2 . '"') && str_contains($h, 'id="watch-row-' . $s3 . '"'), 'Sam\'s list: his three');
ok(!str_contains($h, 'id="watch-row-' . $n1 . '"') && !str_contains($h, 'Set by'), '…not Nora\'s; no "Set by" column');
ok(preg_match('~id="watch-row-' . $s3 . '-now"[^>]*>.*?holds~', $h) === 1 && preg_match('~id="watch-row-' . $s1 . '-now"[^>]*>.*?not now~', $h) === 1, 'the Now column: the product watch holds, the Foundation King\'s does not');
ok(preg_match('~id="watch-row-' . $s1 . '".*?feather-message-square~s', $h) === 1, 'the text mark on the watch that texts');
ok(preg_match('~id="watch-row-' . $s2 . '".*?950\.00~s', $h) === 1, 'the threshold shown (950.00)');
ok(str_contains($h, 'id="watch-row-' . $s1 . '-clear"') && str_contains($h, 'hx-confirm="Clear this watch?"'), 'Clear on each, confirmed');
ok(!str_contains($h, 'id="watch-filter-member"'), 'no member filter for Sam');
[$c, $h] = html($vera, '/watches/');
ok($c === 403 && str_contains($h, 'set watches'), 'Vera has no list: 403 in words');
[$c, $h] = html($nora, '/watches/');
ok(str_contains($h, 'id="watch-row-' . $s1 . '"') && str_contains($h, 'id="watch-row-' . $n1 . '"') && str_contains($h, 'Set by') && str_contains($h, 'id="watch-filter-member"'), 'Nora (watches.all): everyone\'s, with "Set by" and the member filter');
ok(preg_match('~id="watch-row-' . $n2 . '".*?SMOKE Inventory expert~s', $h) === 1, '…the agent named on her watch');
[$c, $d] = screen($nora, '/watches/?member=41');
ok(count($d['watches']) === 3 && count(array_filter($d['watches'], static fn ($x) => $x['member_id'] === 41)) === 3, 'the member filter: Sam\'s three');
[$c, $d] = screen($nora, '/watches/?kind=cost_below');
ok(count($d['watches']) === 1 && $d['watches'][0]['watch_id'] === $n1, 'the kind filter');
echo "4. Clearing\n";
[$c, $b] = act($sam, '/watches/clear.php', ['watch' => $n1]);
ok($c === 404, 'Sam cannot clear Nora\'s watch: 404');
$since = last_activity_id();
[$c, $b] = act($sam, '/watches/clear.php', ['watch' => $s3]);
ok($c === 200 && $b['location'] === '/watches/?notice=cleared#watch-row-' . $s3 && $watch($s3)['active'] === false, 'Sam clears his product watch: active false, landing on its row');
ok(last_log('watch.clear', $since) !== null && after_of(last_log('watch.clear', $since))['watch_id'] === $s3, 'watch.clear logged');
[$c, $b] = act($sam, '/watches/clear.php', ['watch' => $s3]);
ok($c === 422 && msg($b) === 'That watch is already cleared.', 'clearing twice: "That watch is already cleared."');
[$c, $h] = html($sam, '/watches/');
ok(!str_contains($h, 'id="watch-row-' . $s3 . '"'), 'the cleared watch is off the list…');
[$c, $h] = html($sam, '/watches/?cleared=1');
ok(str_contains($h, 'id="watch-row-' . $s3 . '"') && str_contains($h, 'cleared</span>'), '…and on it with "show cleared"');
ok((int) one('SELECT count(*) FROM watches WHERE id = :i', ['i' => $s3]) === 1, 'cleared, never deleted');
echo "5. Firing\n";
$r = worker('watches');
ok(($r['watches']['fired'] ?? -1) === 0, 'a pass with nothing changed fires nothing (the set-time evaluation means a true condition is not news)');
$since = last_activity_id();
psql_exec("SELECT inv_post_txn('receipt', $fk, {$w['wh']}, 1, 120.00, 'opening', 90, 'smoke-s4-fk1', 'none', NULL, NULL, NULL, 1)");
$r = worker('watches');
ok(($r['watches']['fired'] ?? 0) === 2, 'a Foundation King arrives: the pass fires two watches (Sam\'s and Nora\'s agent watch)');
$n = q("SELECT * FROM notifications WHERE record_type = 'watch' AND record_id = :i", ['i' => $s1]);
ok(count($n) === 1 && (int) $n[0]['member_id'] === 41 && $n[0]['kind'] === 'watch' && $n[0]['title'] === 'Back in stock: SMOKE Cloudrest Foundation King', 'Sam is told in-app: "Back in stock: SMOKE Cloudrest Foundation King"');
$em = q("SELECT * FROM notification_outbox WHERE dedupe_key = :k", ['k' => 'watch:' . $s1 . ':1:email']);
ok(count($em) === 1 && $em[0]['channel'] === 'email' && $em[0]['to_email'] === 'sam@example.invalid' && $em[0]['status'] === 'queued', '…an email queued (his default kinds)');
$tx = q("SELECT * FROM notification_outbox WHERE dedupe_key = :k", ['k' => 'watch:' . $s1 . ':1:text']);
ok(count($tx) === 1 && $tx[0]['channel'] === 'text' && mb_strlen($tx[0]['body']) <= 300 && $tx[0]['status'] === 'queued', '…and a text queued because he chose text_me (≤ 300; slice 8 sends it through K6)');
$lf = q("SELECT * FROM activity_log WHERE action = 'watch.fire' AND entity_id = :i AND id > :s", ['i' => $s1, 's' => $since]);
$fa = after_of($lf[0] ?? null);
ok(count($lf) === 1 && $lf[0]['source'] === 'cron' && $lf[0]['actor_member_id'] === null && $fa['notified'] === (int) $n[0]['id'] && $fa['texted'] === true && $fa['dispatched'] === null && $fa['target'] === 'SMOKE-FND-K' && $fa['state'] === true, 'watch.fire logged (cron, no actor): notified, texted true, dispatched null, the target');
$dp = q('SELECT * FROM agent_dispatches WHERE watch_id = :i', ['i' => $n2]);
ok(count($dp) === 1 && $dp[0]['kind'] === 'watch' && $dp[0]['via'] === 'chat' && (int) $dp[0]['agent_member_id'] === 45 && (int) $dp[0]['acting_member_id'] === 40 && str_starts_with($dp[0]['detail'], 'Back in stock'), 'Nora\'s agent watch: an agent_dispatches row (watch, chat, the expert, acting for Nora, the title)');
$ln = after_of(q("SELECT * FROM activity_log WHERE action = 'watch.fire' AND entity_id = :i AND id > :s", ['i' => $n2, 's' => $since])[0] ?? null);
ok(($ln['dispatched'] ?? null) === (int) $dp[0]['id'] && $ln['texted'] === false, '…dispatched on its log row; no text (she did not ask)');
ok($watch($s1)['fire_count'] === 1 && $watch($s1)['last_state'] === true && $watch($s1)['fired_at'] !== null, 'the watch remembers: fire_count 1, last_state true');
$r = worker('watches');
ok(($r['watches']['fired'] ?? -1) === 0, 'the pass again: nothing fires (the state held)');
psql_exec("SELECT inv_post_txn('issue', $fk, {$w['wh']}, -1, NULL, 'adjustment', 91, 'smoke-s4-fk-out', 'none', NULL, NULL, NULL, 1)");
$r = worker('watches');
ok(($r['watches']['fired'] ?? -1) === 0 && $watch($s1)['last_state'] === false, 'it sells out: nothing fires, last_state false (it may fire again)');
psql_exec("SELECT inv_post_txn('receipt', $fk, {$w['wh']}, 1, 120.00, 'opening', 92, 'smoke-s4-fk2', 'none', NULL, NULL, NULL, 1)");
$r = worker('watches');
ok(($r['watches']['fired'] ?? 0) === 2 && $watch($s1)['fire_count'] === 2, 'and back: it fires a second time (fire_count 2)');
ok(count(q("SELECT 1 FROM notification_outbox WHERE dedupe_key = :k", ['k' => 'watch:' . $s1 . ':2:text'])) === 1, '…under a new dedupe key (watch:' . $s1 . ':2)');
ok(count(q("SELECT 1 FROM notifications WHERE record_type = 'watch' AND record_id = :i", ['i' => $s1])) === 2, '…a second notice');
echo "6. A price drop fires the price watch\n";
fix_variant('v2');
age_source($w['src_malouf'], '2 hours');
worker('pulls');
$p = (string) one('SELECT price FROM listing_variants WHERE id = :i', ['i' => $mq]);
ok($p === '949.00', 'Malouf\'s next pull reads the Queen at 949.00 (the fixture\'s second version)');
$r = worker('watches');
ok($watch($s2)['fire_count'] === 1, 'the pass fires the price watch (under 950)');
ok(count(q("SELECT 1 FROM notifications WHERE record_type = 'watch' AND record_id = :i AND title LIKE 'Price below 950.00:%'", ['i' => $s2])) === 1, '…"Price below 950.00: …"');
$lp = q("SELECT * FROM activity_log WHERE action = 'watch.fire' AND entity_id = :i ORDER BY id DESC LIMIT 1", ['i' => $s2])[0] ?? null;
ok($lp !== null && (int) $lp['source_id'] === $w['src_malouf'] && after_of($lp)['texted'] === false, '…logged with source_id (Malouf), no text');
fix_variant('');
echo "7. The heartbeat\n";
psql_exec("UPDATE offer_snapshots SET observed_at = observed_at - interval '3 days' WHERE listing_variant_id IN (SELECT lv.id FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = {$w['src_casper']})");
$stale = (int) one("SELECT count(*) FROM listing_variants lv WHERE lv.removed_at IS NULL AND NOT EXISTS (SELECT 1 FROM offer_snapshots s WHERE s.listing_variant_id = lv.id AND s.observed_at > now() - interval '1 day')");
$casperLvs = (int) one("SELECT count(*) FROM listing_variants lv JOIN listings l ON l.id = lv.listing_id WHERE l.source_id = :s AND lv.removed_at IS NULL", ['s' => $w['src_casper']]);
$b0 = (int) one('SELECT count(*) FROM offer_snapshots');
$r = worker('snapshots_heartbeat');
ok(($r['snapshots_heartbeat']['snapshots'] ?? -1) === $stale && $stale >= $casperLvs && $casperLvs > 0, 'the heartbeat pass answers its count (' . $stale . ' variants unconfirmed for a day)');
ok((int) one('SELECT count(*) FROM offer_snapshots') === $b0 + $stale && (int) one("SELECT count(*) FROM offer_snapshots WHERE is_heartbeat AND observed_at > now() - interval '1 minute'") === $stale, '…writes one heartbeat snapshot each, only for those');
$r = worker('snapshots_heartbeat');
ok(($r['snapshots_heartbeat']['snapshots'] ?? -1) === 0, '…and none on the next pass');
finish();
