<?php
/** Brands and types: creates, a duplicate name, Vera's POST refused, the list with product counts, a type added, renamed inline, deactivated; the logs. */
require __DIR__ . '/lib.php';
$w = catalog_world();
$nora = as_member(40); $vera = as_member(43); $sam = as_member(41);
echo "1. Brands\n";
$since = last_activity_id();
[$c, $b] = act($nora, '/brands/save.php', ['name' => 'SMOKE Purple', 'website' => 'purple.example']);
ok($c === 200 && $b['ok'] === true && $b['record_id'] > 0 && str_ends_with((string) $b['location'], '#brand-row-' . $b['record_id']) && $b['refresh'] === 'brandChanged', 'Nora creates a brand: {ok, did, record_id, location ending in the id, refresh brandChanged}');
$pid = (int) $b['record_id'];
ok(one('SELECT website FROM brands WHERE id = :id', ['id' => $pid]) === 'https://purple.example', 'the website is stored with its scheme');
[$c, $b] = act($nora, '/brands/save.php', ['name' => 'smoke purple']);
ok($c === 422 && msg($b) === 'That name is already taken.', 'a duplicate name (whatever its case): 422 "That name is already taken."');
[$c, $b] = act($nora, '/brands/save.php', ['name' => '']);
ok($c === 422 && isset(fields($b)['name']), 'an empty name: 422 naming the field');
[$c, $b] = act($vera, '/brands/save.php', ['name' => 'SMOKE Vera brand']);
ok($c === 403 && str_contains(msg($b), 'You may not change the catalog'), 'Vera\'s POST: 403 in the right\'s words');
ok(act($sam, '/brands/save.php', ['name' => 'SMOKE Sam brand'])[0] === 403, 'Sam (Sales) may not either');
[$c, $b] = act($nora, '/brands/save.php', ['brand' => $pid, 'website' => 'https://purple.example/dealers', 'active' => 'no']);
ok($c === 200 && one('SELECT active FROM brands WHERE id = :id', ['id' => $pid]) === false && one('SELECT name FROM brands WHERE id = :id', ['id' => $pid]) === 'SMOKE Purple', 'an update changes what was sent (website, active) and keeps the name');
[$c, $b] = act($nora, '/brands/save.php', ['brand' => $pid, 'supplier' => '999999']);
ok($c === 422 && isset(fields($b)['supplier']), 'a supplier that is not here: 422 naming the field');
ok(act($nora, '/brands/save.php', ['brand' => 999999, 'name' => 'x'])[0] === 404, 'a brand that does not exist: 404');
$log = activity('brand.save', $since);
ok(count($log) === 2 && str_contains((string) $log[0]['after'], 'SMOKE Purple') && str_contains((string) $log[1]['before'], 'active'), 'brand.save logged twice: the create with its fields, the update with before/after');
[$c, $d] = screen($nora, '/brands/');
ok($c === 200 && count($d['brands']) >= 3 && ($d['brands'][0]['product_count'] ?? null) !== null, 'the list carries product counts');
$cloud = array_values(array_filter($d['brands'], static fn ($x) => $x['name'] === 'SMOKE Cloudrest'))[0] ?? null;
ok($cloud !== null && $cloud['product_count'] === 3, 'SMOKE Cloudrest counts its three products');
[$c, $d] = screen($nora, '/brands/?q=zinus');
ok($c === 200 && count($d['brands']) === 1 && $d['brands'][0]['name'] === 'SMOKE Zinus', '?q= filters the list');
$h = page($nora, '/brands/')['body'];
ok(str_contains($h, 'id="brand-table"') && str_contains($h, 'id="brand-row-' . $pid . '"') && str_contains($h, 'id="brand-list-new-btn"') && str_contains($h, 'id="brand-row-' . $pid . '-edit-btn"'), 'the screen: the table, the row, New brand, Edit');
ok(!str_contains(page($vera, '/brands/')['body'], 'id="brand-list-new-btn"') && page($vera, '/brands/')['code'] === 200, 'Vera reads the brands without New brand');
ok(page($vera, '/brands/new')['code'] === 403 && page($nora, '/brands/new')['code'] === 200 && page($nora, '/brands/' . $pid . '/edit')['code'] === 200, 'the form: 403 for Vera, 200 for Nora (new and edit)');
echo "2. Product types\n";
$since = last_activity_id();
[$c, $b] = act($nora, '/product-types/save.php', ['name' => 'SMOKE Bunk']);
ok($c === 200 && $b['key'] === 'smoke_bunk' && $b['record_id'] > 0, 'a type added: the key from the name (smoke_bunk)');
$tid = (int) $b['record_id'];
[$c, $b] = act($nora, '/product-types/save.php', ['name' => 'SMOKE Bunk two', 'key' => 'smoke_bunk']);
ok($c === 422 && msg($b) === 'That key is already taken.', 'a duplicate key: 422');
[$c, $b] = act($nora, '/product-types/save.php', ['product_type' => $tid, 'name' => 'SMOKE Bunk bed', 'sort_order' => 42]);
ok($c === 200 && one('SELECT name FROM product_types WHERE id = :id', ['id' => $tid]) === 'SMOKE Bunk bed' && (int) one('SELECT sort_order FROM product_types WHERE id = :id', ['id' => $tid]) === 42, 'renamed and reordered inline');
$r = req('POST', '/product-types/save.php', ['jar' => $nora, 'headers' => ['HX-Request: true', 'HX-Target: product-type-row-' . $tid], 'form' => ['product_type' => $tid, 'name' => 'SMOKE Bunk bed', 'active' => 'no', 'csrf_token' => csrf_of(page($nora, '/')['body'])]]);
ok($r['code'] === 200 && str_starts_with(trim($r['body']), '<tr id="product-type-row-' . $tid . '"') && str_contains($r['headers'], 'settingsChanged'), 'a Pattern C request answers the row partial with the settingsChanged trigger; deactivated');
ok(one('SELECT active FROM product_types WHERE id = :id', ['id' => $tid]) === false, 'and the row is inactive');
ok(count(activity('product_type.save', $since)) === 3, 'product_type.save logged three times');
ok(act($vera, '/product-types/save.php', ['name' => 'x'])[0] === 403, 'Vera may not add a type');
[$c, $d] = screen($vera, '/product-types/');
ok($c === 200 && count($d['product_types']) >= 10, 'Vera reads the types');
ok(str_contains(page($nora, '/product-types/')['body'], 'id="product-type-row-' . $tid . '-form"') && !str_contains(page($vera, '/product-types/')['body'], 'id="product-type-row-' . $tid . '-form"'), 'Nora sees the inline forms, Vera does not');
finish();
