<?php
/** Bundles: replace semantics, a bundle inside a bundle, components on a single product, inv_bundle_availability(), the picker's rows. */
require __DIR__ . '/lib.php';
$w = catalog_world();
$nora = as_member(40); $vera = as_member(43);
echo "Bundles\n";
$since = last_activity_id();
$set = $w['set_q'];
[$c, $d] = screen($nora, '/variants/' . $set . '/bundle');
ok($c === 200 && count($d['components']) === 2 && $d['availability']['sets_available'] === 0 && $d['availability']['state'] === 'unavailable', 'the set has two components; inv_bundle_availability() says 0 sets, unavailable (no stock yet)');
[$c, $b] = act($nora, '/variants/bundle.php', ['bundle' => $set, 'components' => json_encode([['variant' => 'SMOKE-NW-CR-Q', 'qty' => 1]])]);
ok($c === 200 && count($b['components']) === 1 && (int) one('SELECT count(*) FROM bundle_components WHERE bundle_variant_id = :b', ['b' => $set]) === 1, 'a second save with one row leaves one (replace semantics)');
[$c, $b] = act($nora, '/variants/bundle.php', ['bundle' => $set, 'components' => json_encode([['variant' => $w['queen'], 'qty' => 1], ['variant' => $w['fnd_queen'], 'qty' => 2]])]);
ok($c === 200 && (int) one('SELECT qty FROM bundle_components WHERE bundle_variant_id = :b AND component_variant_id = :c', ['b' => $set, 'c' => $w['fnd_queen']]) === 2, 'the whole list again, by id, with a quantity of 2');
// the form's shape
$r = req('POST', '/variants/bundle.php', ['jar' => $nora, 'headers' => JSONH, 'form' => ['bundle' => $set, 'components' => [['variant' => $w['queen'], 'qty' => 1], ['variant' => $w['fnd_queen'], 'qty' => 1]], 'csrf_token' => csrf_of(page($nora, '/')['body'])]]);
ok($r['code'] === 200 && (int) one('SELECT qty FROM bundle_components WHERE bundle_variant_id = :b AND component_variant_id = :c', ['b' => $set, 'c' => $w['fnd_queen']]) === 1, 'the form\'s components[n][variant] / [qty] shape works too');
[$c, $b] = act($nora, '/products/save.php', ['name' => 'SMOKE Big set', 'type' => 'mattress', 'kind' => 'bundle', 'status' => 'active']);
[$c, $b] = act($nora, '/variants/save.php', ['product' => (int) $b['record_id'], 'sku' => 'SMOKE-BIG-Q', 'option_values' => json_encode(['Size' => 'Queen'])]);
$big = (int) $b['record_id'];
[$c, $b] = act($nora, '/variants/bundle.php', ['bundle' => $big, 'components' => json_encode([['variant' => 'SMOKE-SET-Q', 'qty' => 1]])]);
ok($c === 422 && msg($b) === 'A bundle does not contain a bundle', 'a bundle inside a bundle: the trigger\'s sentence');
[$c, $b] = act($nora, '/variants/bundle.php', ['bundle' => $w['queen'], 'components' => json_encode([['variant' => $w['fnd_queen'], 'qty' => 1]])]);
ok($c === 422 && str_contains(msg($b), 'not a variant of a bundle product'), 'components on a single product\'s variant: refused');
[$c, $b] = act($nora, '/variants/bundle.php', ['bundle' => $set, 'components' => json_encode([['variant' => 'SMOKE-SET-Q', 'qty' => 1]])]);
ok($c === 422 && str_contains(msg($b), 'contain itself'), 'a bundle containing itself: refused');
[$c, $b] = act($nora, '/variants/bundle.php', ['bundle' => $set, 'components' => json_encode([['variant' => 'NOPE', 'qty' => 1]])]);
ok($c === 422 && str_contains(msg($b), 'No variant "NOPE"'), 'a component that does not exist: 422 in words');
[$c, $b] = act($nora, '/variants/bundle.php', ['bundle' => $set, 'components' => json_encode([['variant' => $w['queen'], 'qty' => 0]])]);
ok($c === 422 && str_contains(msg($b), 'from 1 to 1000'), 'a quantity of 0: 422');
ok(act($vera, '/variants/bundle.php', ['bundle' => $set, 'components' => '[]'])[0] === 403, 'Vera may not set a bundle');
ok(page($nora, '/variants/' . $w['queen'] . '/bundle')['code'] === 404 && str_contains(page($nora, '/variants/' . $w['queen'] . '/bundle')['body'], 'only a bundle has components'), 'the editor on a single variant: 404 in words');
$h = page($nora, '/variants/' . $set . '/bundle')['body'];
ok(str_contains($h, 'id="bundle-editor"') && str_contains($h, 'id="bundle-row-0"') && str_contains($h, 'id="bundle-row-1"') && str_contains($h, 'data-picker-source="variant"') && str_contains($h, 'id="bundle-add-row-btn"'), 'the editor: two rows with the variant picker, Add a component');
$r = req('GET', '/pick/?source=variant&single=1&q=SMOKE-NW-CR', ['jar' => $nora, 'headers' => ['HX-Request: true']]);
ok($r['code'] === 200 && str_contains($r['body'], 'data-label="SMOKE-NW-CR-Q — SMOKE Cloudrest Hybrid, Queen"') && !str_contains($r['body'], 'SMOKE-SET-Q'), 'the picker answers "SKU — product, size"; single=1 keeps the bundles out');
$r = req('GET', '/pick/?source=variant&q=SMOKE-SET', ['jar' => $nora, 'headers' => ['HX-Request: true']]);
ok($r['code'] === 200 && str_contains($r['body'], 'SMOKE-SET-Q'), 'without single=1 the set is offered');
ok(req('GET', '/pick/?source=variant', ['headers' => ['HX-Request: true']])['code'] === 401 && req('GET', '/pick/?source=nope', ['jar' => $nora])['code'] === 404, 'the picker: 401 anonymous, 404 an unknown source');
$r = req('GET', '/variants/pick?q=SMOKE-FND&single=1', ['jar' => $nora]);
ok($r['code'] === 200 && count(json_decode($r['body'], true)['rows']) === 6, '/variants/pick answers JSON rows (the six foundations)');
pdo()->exec("SELECT set_config('app.member_id', '40', false)");
$a = json_decode((string) one('SELECT inv_bundle_availability(:v)::text', ['v' => $set]), true);
ok(count($a['components']) === 2 && $a['sets_available'] === 0 && $a['best_lead_time_days'] === null, 'inv_bundle_availability(): two components, 0 sets, no lead time (no offers yet)');
[$c, $d] = screen($nora, '/products/' . $w['set']);
ok($d['variants'][0]['sets_available'] === 0 && count($d['bundle_components']) === 2, 'the product answers sets_available and the components');
ok(str_contains(page($nora, '/products/' . $w['set'] . '?tab=bundle')['body'], 'Sets available: <strong>0</strong>'), 'the Bundle tab says 0 sets');
ok(str_contains(page($nora, '/variants/' . $w['queen'])['body'], 'Part of:') && str_contains(page($nora, '/variants/' . $w['queen'])['body'], 'SMOKE-SET-Q'), 'the component\'s page says which bundle it is part of');
ok(count(activity('variant.bundle_set', $since)) === 3 && str_contains((string) activity('variant.bundle_set', $since)[0]['after'], '"components"'), 'variant.bundle_set logged with the components');
finish();
