<?php
/** Identifiers: a UPC as GTIN-14, an MPN, an ASIN; a supplier SKU without a source; a duplicate; removed; variant_by_identifier(). */
require __DIR__ . '/lib.php';
$w = catalog_world();
$nora = as_member(40); $vera = as_member(43);
echo "Identifiers\n";
$since = last_activity_id();
$vid = $w['queen'];
[$c, $b] = act($nora, '/variants/identifiers/add.php', ['variant' => $vid, 'kind' => 'upc', 'value' => '85012345-0035']);
ok($c === 200 && $b['record_id'] > 0 && str_ends_with((string) $b['location'], '#identifier-row-' . $b['record_id']) && one('SELECT value FROM variant_identifiers WHERE id = :id', ['id' => $b['record_id']]) === '00850123450035', 'a UPC added, normalized to GTIN-14');
$upc = (int) $b['record_id'];
[$c, $b] = act($nora, '/variants/identifiers/add.php', ['variant' => $vid, 'kind' => 'mpn', 'value' => 'NWCR-Q']);
ok($c === 200, 'an MPN added');
[$c, $b] = act($nora, '/variants/identifiers/add.php', ['variant' => $vid, 'kind' => 'asin', 'value' => 'B0SMOKE001']);
ok($c === 200, 'an ASIN added');
[$c, $b] = act($nora, '/variants/identifiers/add.php', ['variant' => $vid, 'kind' => 'supplier_sku', 'value' => 'DL-1001']);
ok($c === 422 && msg($b) === 'A supplier SKU belongs to a source', 'a supplier SKU without a source: the trigger\'s sentence');
$src = (int) one("SELECT id FROM sources WHERE name = 'SMOKE Dreamland feed'");
[$c, $b] = act($nora, '/variants/identifiers/add.php', ['variant' => $vid, 'kind' => 'supplier_sku', 'value' => 'DL-1001', 'source' => $src]);
ok($c === 200, 'with a supplier source: added');
[$c, $b] = act($nora, '/variants/identifiers/add.php', ['variant' => $w['calking'], 'kind' => 'upc', 'value' => '850123450035']);
ok($c === 422 && str_contains(msg($b), 'already on a variant'), 'a duplicate (kind, value, source): 422');
[$c, $b] = act($nora, '/variants/identifiers/add.php', ['variant' => $vid, 'kind' => 'ean', 'value' => '12345']);
ok($c === 422 && str_contains(msg($b), 'not a valid GTIN'), 'an EAN that is not a GTIN: the trigger\'s sentence');
[$c, $b] = act($nora, '/variants/identifiers/add.php', ['variant' => $vid, 'kind' => 'nope', 'value' => 'x']);
ok($c === 422 && isset(fields($b)['kind']), 'an unknown kind: 422 naming the field');
ok(act($vera, '/variants/identifiers/add.php', ['variant' => $vid, 'kind' => 'mpn', 'value' => 'x'])[0] === 403, 'Vera may not add one');
[$c, $d] = screen($nora, '/variants/' . $vid . '/identifiers');
ok($c === 200 && count($d['identifiers']) === 4 && in_array('supplier_sku', array_column($d['identifiers'], 'kind'), true), 'the screen lists the four');
$h = page($nora, '/variants/' . $vid . '/identifiers')['body'];
ok(str_contains($h, 'id="identifier-table"') && str_contains($h, 'id="identifier-row-' . $upc . '"') && str_contains($h, 'id="identifier-form"') && str_contains($h, 'id="identifier-row-' . $upc . '-remove-btn"'), 'the table, the row, the form, Remove');
ok(page($vera, '/variants/' . $vid . '/identifiers')['code'] === 200 && !str_contains(page($vera, '/variants/' . $vid . '/identifiers')['body'], 'id="identifier-form"'), 'Vera reads them without the form');
// the MPN shared by two sizes → ambiguous: the identifier index is unique per (kind, value), so the second size carries it on its own mpn column
act($nora, '/variants/save.php', ['variant' => $w['calking'], 'mpn' => 'NWCR-Q']);
pdo()->exec("SELECT set_config('app.member_id', '40', false)");
require_once dirname(__DIR__, 3) . '/app/bootstrap.php';
require_once dirname(__DIR__, 3) . '/app/features/catalog/queries.php';
$pdo = db();
$pdo->exec("SELECT set_config('app.member_id', '40', false)");
$r = variant_by_identifier($pdo, '850123450035');
ok(count($r) === 1 && $r[0]['variant_id'] === $vid && $r[0]['matched_on']['kind'] === 'gtin', 'variant_by_identifier(GTIN) answers one, matched on gtin');
$r = variant_by_identifier($pdo, 'NWCR-Q');
ok(count($r) === 2 && $r[0]['matched_on']['kind'] === 'mpn', 'an MPN shared by two sizes answers two (ambiguous)');
$r = variant_by_identifier($pdo, 'B0SMOKE001', 'asin');
ok(count($r) === 1 && $r[0]['matched_on']['kind'] === 'asin', 'an ASIN answers one, matched on asin');
$r = variant_by_identifier($pdo, 'DL-1001', 'supplier_sku', $src);
ok(count($r) === 1 && $r[0]['matched_on']['source_id'] === $src, 'a supplier SKU with its source');
ok(variant_by_identifier($pdo, 'nothing-here') === [], 'nothing: an empty list');
[$c, $b] = act($nora, '/variants/identifiers/remove.php', ['identifier' => $upc]);
ok($c === 200 && one('SELECT count(*) FROM variant_identifiers WHERE id = :id', ['id' => $upc]) === 0, 'removed');
ok(act($nora, '/variants/identifiers/remove.php', ['identifier' => $upc])[0] === 404, 'removing it again: 404');
ok(count(activity('variant.identifier_add', $since)) === 4 && count(activity('variant.identifier_remove', $since)) === 1 && str_contains((string) activity('variant.identifier_add', $since)[0]['after'], '"product_id"'), 'variant.identifier_add (4) and remove (1) logged with product_id');
finish();
