<?php
/** Images: three uploaded (jpeg, png; a PDF refused), the first primary, the primary moved, up and down, one removed (the file gone), /files/{id} to Vera, 401 anonymous, the log. */
require __DIR__ . '/lib.php';
$w = catalog_world();
$nora = as_member(40); $vera = as_member(43);
[$jpg, $png] = smoke_images();
echo "Images\n";
$since = last_activity_id();
$pid = $w['mattress'];
[$c, $b] = act_files($nora, '/products/images/add.php', ['product' => $pid, 'alt_text' => 'Queen on the floor'], ['file' => [$jpg, 'queen.jpg', 'image/jpeg']]);
ok($c === 200 && $b['image_id'] > 0 && str_ends_with((string) $b['location'], '#product-image-' . $b['image_id']), 'a JPEG uploaded: {image_id, location ending in the id}');
$i1 = (int) $b['image_id'];
ok(one('SELECT is_primary FROM product_images WHERE id = :id', ['id' => $i1]) === true, 'the first image is the primary one');
[$c, $b] = act_files($nora, '/products/images/add.php', ['product' => $pid, 'variant' => $w['calking']], ['file' => [$png, 'calking.png', 'image/png']]);
ok($c === 200 && (int) one('SELECT variant_id FROM product_images WHERE id = :id', ['id' => $b['image_id']]) === $w['calking'], 'a PNG uploaded for a size that looks different');
$i2 = (int) $b['image_id'];
[$c, $b] = act_files($nora, '/products/images/add.php', ['product' => $pid], ['file' => [$png, 'third.png', 'image/png']]);
$i3 = (int) $b['image_id'];
ok($c === 200 && (int) one('SELECT sort_order FROM product_images WHERE id = :id', ['id' => $i3]) === 2, 'a third, sorted last');
$pdf = sys_get_temp_dir() . '/inv-smoke.pdf';
file_put_contents($pdf, "%PDF-1.4\n1 0 obj << >> endobj\ntrailer << >>\n%%EOF\n");
[$c, $b] = act_files($nora, '/products/images/add.php', ['product' => $pid], ['file' => [$pdf, 'sheet.pdf', 'application/pdf']]);
ok($c === 422 && str_contains(msg($b), 'is an image'), 'a PDF is refused in words');
ok((int) one('SELECT count(*) FROM attachments WHERE record_type = \'product\' AND record_id = :p', ['p' => $pid]) === 2 && glob(dirname(__DIR__, 3) . '/storage/attachments/product/' . $pid . '/*.pdf') === [], 'and leaves no row and no file behind');
[$c, $b] = act_files($nora, '/products/images/add.php', ['product' => $pid], ['file' => [$jpg, 'evil.php', 'image/jpeg']]);
ok($c === 422, 'a file named .php is refused whatever its bytes');
[$c, $b] = act($nora, '/products/images/add.php', ['product' => $pid, 'image' => $i2, 'is_primary' => 'yes']);
ok($c === 200 && $b['image_id'] === $i2 && one('SELECT is_primary FROM product_images WHERE id = :id', ['id' => $i2]) === true && one('SELECT is_primary FROM product_images WHERE id = :id', ['id' => $i1]) === false, 'image_add with image and no file: the primary moved to the second');
[$c, $b] = act($nora, '/products/images/add.php', ['product' => $pid, 'image' => $i3, 'sort_order' => '0']);
ok($c === 200 && (int) one('SELECT sort_order FROM product_images WHERE id = :id', ['id' => $i3]) === 0 && (int) one('SELECT sort_order FROM product_images WHERE id = :id', ['id' => $i1]) === 2, 'moved up to the top: the orders swapped');
[$c, $b] = act($nora, '/products/images/add.php', ['product' => $pid, 'image' => $i3, 'sort_order' => '1']);
ok($c === 200 && (int) one('SELECT sort_order FROM product_images WHERE id = :id', ['id' => $i3]) === 1, 'and down one');
[$c, $b] = act($nora, '/products/images/add.php', ['product' => $pid, 'image' => $i1, 'alt_text' => 'Queen, side view']);
ok($c === 200 && one('SELECT alt_text FROM product_images WHERE id = :id', ['id' => $i1]) === 'Queen, side view', 'the alt text changed');
ok(act($nora, '/products/images/add.php', ['product' => $w['pillow'], 'image' => $i1, 'is_primary' => 'yes'])[0] === 404, 'an image of another product: 404');
ok(act($nora, '/products/images/add.php', ['product' => $pid])[0] === 422, 'neither a file nor an image: 422');
[$c, $d] = screen($nora, '/products/' . $pid . '/images');
ok($c === 200 && count($d['images']) === 3 && $d['images'][0]['image_id'] === $i2 && $d['images'][0]['is_primary'] === true && str_starts_with($d['images'][0]['url'], '/files/'), 'the screen lists three, the primary first, each with its /files URL');
[$c, $d] = screen($nora, '/products/' . $pid);
ok($d['product']['primary_image_attachment_id'] === one('SELECT attachment_id FROM product_images WHERE id = :id', ['id' => $i2]) * 1, 'the product\'s primary_image_attachment_id is the primary\'s');
$h = page($nora, '/products/' . $pid . '/images')['body'];
ok(str_contains($h, 'id="product-images-grid"') && str_contains($h, 'id="product-image-' . $i1 . '"') && str_contains($h, 'id="product-image-form"') && str_contains($h, 'id="product-image-' . $i1 . '-primary-btn"') && str_contains($h, 'id="product-image-' . $i1 . '-remove-btn"'), 'the grid, the upload form, Make primary, Remove');
$att = (int) one('SELECT attachment_id FROM product_images WHERE id = :id', ['id' => $i1]);
$r = page($vera, '/files/' . $att);
ok($r['code'] === 200 && str_contains($r['headers'], 'image/jpeg') && str_contains($r['headers'], 'inline'), '/files/{id} serves the JPEG inline to Vera (a reader)');
ok(page($vera, '/files/' . $att . '/thumb')['code'] === 200 && req('GET', '/files/' . $att)['code'] === 401, '/thumb serves the same; anonymous is 401');
$path = (string) one('SELECT storage_path FROM attachments WHERE id = :id', ['id' => $att]);
ok(is_file(dirname(__DIR__, 3) . '/storage/' . $path) && str_starts_with($path, 'attachments/product/' . $pid . '/' . $att . '-'), 'the file sits under storage/attachments/product/{id}/{attachment}-name');
[$c, $b] = act($nora, '/products/images/remove.php', ['image' => $i1]);
clearstatcache();
ok($c === 200 && one('SELECT count(*) FROM product_images WHERE id = :id', ['id' => $i1]) === 0 && one('SELECT count(*) FROM attachments WHERE id = :id', ['id' => $att]) === 0 && !is_file(dirname(__DIR__, 3) . '/storage/' . $path), 'removed: the row, the attachment and the file are gone (' . $c . ' row ' . one('SELECT count(*) FROM product_images WHERE id = :id', ['id' => $i1]) . ' att ' . one('SELECT count(*) FROM attachments WHERE id = :id', ['id' => $att]) . ' file ' . (is_file(dirname(__DIR__, 3) . '/storage/' . $path) ? 'there' : 'gone') . ')');
ok(page($vera, '/files/' . $att)['code'] === 404, 'and /files/{id} answers 404');
ok(act($nora, '/products/images/remove.php', ['image' => $i1])[0] === 404, 'removing it again: 404');
ok(act($vera, '/products/images/remove.php', ['image' => $i2])[0] === 403 && act_files($vera, '/products/images/add.php', ['product' => $pid], ['file' => [$jpg, 'v.jpg', 'image/jpeg']])[0] === 403, 'Vera may neither upload nor remove');
[$c, $b] = act($nora, '/products/images/remove.php', ['image' => $i2]);
ok($c === 200 && one('SELECT is_primary FROM product_images WHERE id = :id', ['id' => $i3]) === true, 'removing the primary makes the next image primary');
$log = activity('product.image_add', $since);
ok(count($log) >= 6 && str_contains((string) $log[0]['after'], '"attachment_id"') && !str_contains((string) $log[0]['after'], 'storage/') && str_contains((string) $log[3]['after'], '"updated": true'), 'product.image_add logged with attachment_id and never a path; an update says updated: true');
ok(count(activity('product.image_remove', $since)) === 2, 'product.image_remove logged twice');
finish();
