<?php
/** JSON mode: every handler under a signed action token answers {ok, did, record_id, location, refresh}; 422 names the field; the expert creates as source agent and is refused product_delete in words. */
require __DIR__ . '/lib.php';
$w = catalog_world();
echo "1. A person's action token\n";
$tok = person_token(40);
$H = ['X-Action-Token: ' . $tok];
[$c, $b] = act_token('/brands/save.php', ['name' => 'SMOKE Token brand'], $H);
ok($c === 200 && $b['ok'] === true && isset($b['did'], $b['record_id'], $b['location'], $b['refresh']) && !isset($b['error']), 'brand_save: {ok, did, record_id, location, refresh}');
$bid = (int) $b['record_id'];
[$c, $b] = act_token('/products/save.php', ['name' => 'SMOKE Token product', 'type' => 'mattress', 'brand' => $bid, 'kind' => 'single'], $H);
ok($c === 200 && $b['ok'] === true && $b['product_id'] === $b['record_id'] && $b['location'] === '/products/' . $b['record_id'] . '?notice=created', 'product_create');
$pid = (int) $b['record_id'];
[$c, $b] = act_token('/products/save.php', ['product' => $pid, 'status' => 'active', '_partial' => '1'], $H);
ok($c === 200 && one('SELECT status FROM products WHERE id = :id', ['id' => $pid]) === 'active' && one('SELECT name FROM products WHERE id = :id', ['id' => $pid]) === 'SMOKE Token product', 'product_update with _partial keeps the name');
[$c, $b] = act_token('/variants/save.php', ['product' => $pid, 'sku' => 'SMOKE-TOK-Q', 'option_values' => '{"Size":"Queen"}', 'barcode' => '850123450400', 'retail_price' => '500'], $H);
ok($c === 200 && $b['ok'] === true && $b['variant_id'] === $b['record_id'], 'variant_create');
$vid = (int) $b['record_id'];
[$c, $b] = act_token('/variants/save.php', ['product' => $pid, 'sku' => 'SMOKE-TOK-Q', 'option_values' => '{"Size":"King"}'], $H);
ok($c === 422 && $b['error']['code'] === 'invalid' && $b['error']['message'] === 'That SKU is already taken.', 'a duplicate SKU: 422 {error: {code: invalid, message}}');
[$c, $b] = act_token('/variants/save.php', ['product' => $pid, 'sku' => '', 'option_values' => '{}'], $H);
ok($c === 422 && isset($b['error']['fields']['sku']) && isset($b['error']['fields']['option_values']), '422 names the fields (sku, option_values)');
[$c, $b] = act_token('/variants/price.php', ['variant' => $vid, 'kind' => 'map', 'price' => '480', 'reason' => 'by token'], $H);
ok($c === 200 && $b['ok'] === true && $b['kind'] === 'map' && $b['after'] === '480.00', 'price_set');
[$c, $b] = act_token('/variants/identifiers/add.php', ['variant' => $vid, 'kind' => 'asin', 'value' => 'B0TOKEN'], $H);
ok($c === 200 && $b['identifier_id'] === $b['record_id'], 'identifier_add');
[$c, $b] = act_token('/variants/identifiers/remove.php', ['identifier' => $b['record_id']], $H);
ok($c === 200 && $b['ok'] === true, 'identifier_remove');
[$c, $b] = act_token('/products/discontinue.php', ['product' => $pid, 'discontinued' => 'yes'], $H);
ok($c === 200 && $b['discontinued'] === true, 'product_discontinue');
act_token('/products/discontinue.php', ['product' => $pid, 'discontinued' => 'no'], $H);
[$c, $b] = act_token('/product-types/save.php', ['name' => 'SMOKE Token type'], $H);
ok($c === 200 && $b['key'] === 'smoke_token_type', 'product_type_save');
[$c, $b] = act_token('/products/save.php', ['name' => 'SMOKE Token set', 'type' => 'mattress', 'kind' => 'bundle', 'status' => 'active'], $H);
[$c, $b] = act_token('/variants/save.php', ['product' => (int) $b['record_id'], 'sku' => 'SMOKE-TOK-SET', 'option_values' => '{"Size":"Queen"}'], $H);
[$c, $b] = act_token('/variants/bundle.php', ['bundle' => (int) $b['record_id'], 'components' => json_encode([['variant' => 'SMOKE-TOK-Q', 'qty' => 2]])], $H);
ok($c === 200 && $b['components'][0]['qty'] === 2 && $b['components'][0]['sku'] === 'SMOKE-TOK-Q', 'bundle_set with a component by SKU');
[$c, $b] = act_token('/products/delete.php', ['product' => $pid], $H);
ok($c === 403 && str_contains($b['error']['message'], 'You may not delete records'), 'Nora\'s token may not delete (records.delete): 403 in words');
ok(act_token('/products/save.php', ['name' => 'x', 'type' => 'mattress'], ['X-Action-Token: ' . person_token(40, -5)])[0] === 401, 'an expired token: 401');
echo "2. The expert under a run token\n";
$rt = run_token(45, 78);
kernel_state(function ($s) { $s['facts']['78'] = ['valid' => true, 'is_agent' => true, 'member_id' => 45, 'run_id' => 78, 'request_id' => 'req-run-78', 'trigger' => 'chat', 'endpoints' => [['name' => 'Records MCP']]]; return $s; });
pdo()->exec("UPDATE members SET roles = '{buyer,user}' WHERE id = 45");
$since = last_activity_id();
[$c, $b] = act_token('/products/save.php', ['name' => 'SMOKE Agent product', 'type' => 'mattress', 'brand' => 'SMOKE Zinus', 'attributes' => '{"type":"latex"}'], as_agent($rt));
ok($c === 200 && $b['ok'] === true, 'the expert creates a product');
$apid = (int) $b['record_id'];
$row = q("SELECT source, agent_run_id, request_id, actor_member_id FROM activity_log WHERE action = 'product.create' AND entity_id = :p", ['p' => $apid])[0];
ok($row['source'] === 'agent' && (int) $row['agent_run_id'] === 78 && $row['request_id'] === 'req-run-78' && (int) $row['actor_member_id'] === 45, 'logged as source agent, run 78, the run\'s request id, actor 45');
[$c, $b] = act_token('/variants/save.php', ['product' => $apid, 'sku' => 'SMOKE-AG-Q', 'option_values' => '{"Size":"Queen"}', 'retail_price' => '700', 'cost_price' => '300'], as_agent($rt));
ok($c === 200 && one('SELECT cost_price FROM product_variants WHERE id = :id', ['id' => $b['record_id']]) === '300.00', 'and a variant with cost (the expert holds buyer here)');
[$c, $b] = act_token('/products/delete.php', ['product' => $apid], as_agent($rt));
ok($c === 403 && str_contains($b['error']['message'], 'You may not delete records'), 'refused product_delete (no records.delete) in words');
[$c, $b] = act_token('/products/import.php', ['mapping' => '{}'], as_agent($rt));
ok($c === 422, 'the import without a file: 422 (an agent sends file + mapping in one POST)');
pdo()->exec("UPDATE members SET roles = '{user}' WHERE id = 45");
[$c, $b] = act_token('/products/save.php', ['name' => 'SMOKE Agent product 2', 'type' => 'mattress'], as_agent($rt));
ok($c === 403, 'with user alone (no catalog.write) the expert may not create');
kernel_state(function ($s) { unset($s['facts']); return $s; });
echo "3. Screens as JSON\n";
$nora = as_member(40);
[$c, $d] = screen($nora, '/products/new');
ok($c === 200 && $d['product'] === null && count($d['attribute_keys']) === 9 && $d['kinds'] === ['single', 'bundle'], 'the product form answers its vocabulary');
[$c, $d] = screen($nora, '/variants/new?product=' . $w['mattress']);
ok($c === 200 && count($d['sizes']) === 12 && $d['units'] === 'imperial' && $d['currency'] === 'USD', 'the variant form answers the sizes, units, currency');
[$c, $d] = screen($nora, '/products/' . $w['mattress'] . '/images');
ok($c === 200 && isset($d['max_bytes']), 'the images screen answers');
[$c, $d] = screen($nora, '/variants/' . $w['set_q'] . '/bundle');
ok($c === 200 && isset($d['availability']['sets_available']), 'the bundle editor answers');
ok(screen($nora, '/product-types/')[0] === 200 && screen($nora, '/brands/' . $w['brand_zinus'] . '/edit')[0] === 200 && screen($nora, '/catalog/import')[0] === 200, 'types, a brand form, the import answer');
finish();
