<?php
/** Prices: Nora sets retail, MAP and cost with reasons; Sam refused; the forms shown by right; the agent's price_set under a run token; the log; the chart's series; Vera's history without cost. */
require __DIR__ . '/lib.php';
$w = catalog_world();
$nora = as_member(40); $sam = as_member(41); $vera = as_member(43); $owner = as_member(1);
echo "Prices\n";
$since = last_activity_id();
$vid = $w['queen'];
[$c, $b] = act($nora, '/variants/price.php', ['variant' => $vid, 'kind' => 'retail', 'price' => '949', 'reason' => 'sale event']);
ok($c === 200 && $b['kind'] === 'retail' && $b['before'] === '999.00' && $b['after'] === '949.00' && str_ends_with((string) $b['location'], '#variant-prices'), 'retail set: {kind, before, after, location #variant-prices}');
[$c, $b] = act($nora, '/variants/price.php', ['variant' => $vid, 'kind' => 'map', 'price' => '929.00', 'reason' => 'new MAP policy']);
ok($c === 200, 'MAP set');
[$c, $b] = act($nora, '/variants/price.php', ['variant' => $vid, 'kind' => 'cost', 'price' => '480', 'reason' => 'new cost sheet']);
ok($c === 200 && one('SELECT cost_price FROM product_variants WHERE id = :id', ['id' => $vid]) === '480.00', 'cost set');
$hist = q("SELECT kind, old_price, new_price, changed_by, reason, source_kind FROM price_history WHERE variant_id = :v AND reason <> 'created' ORDER BY id", ['v' => $vid]);
ok(count($hist) === 3 && $hist[0] === ['kind' => 'retail', 'old_price' => '999.00', 'new_price' => '949.00', 'changed_by' => 40, 'reason' => 'sale event', 'source_kind' => 'manual'], 'three history rows with changed_by, reason, source manual');
[$c, $b] = act($nora, '/variants/price.php', ['variant' => $vid, 'kind' => 'retail', 'price' => '-5']);
ok($c === 422 && isset(fields($b)['price']), 'a negative price: 422 naming the field');
[$c, $b] = act($nora, '/variants/price.php', ['variant' => $vid, 'kind' => 'wholesale', 'price' => '5']);
ok($c === 422 && isset(fields($b)['kind']), 'an unknown kind: 422');
[$c, $b] = act($sam, '/variants/price.php', ['variant' => $vid, 'kind' => 'retail', 'price' => '900']);
ok($c === 403 && str_contains(msg($b), 'You may not set prices'), 'Sam (no prices.write): 403 in words');
ok(act($vera, '/variants/price.php', ['variant' => $vid, 'kind' => 'retail', 'price' => '900'])[0] === 403, 'Vera too');
pdo()->exec("UPDATE inv_settings SET sales_sees_cost = false WHERE id = 1");
psql_exec("INSERT INTO inv_role_rights (role_key, right_key) VALUES ('user', 'prices.write') ON CONFLICT DO NOTHING");
[$c, $b] = act($sam, '/variants/price.php', ['variant' => $vid, 'kind' => 'cost', 'price' => '1']);
ok($c === 403 && msg($b) === 'You may not see cost or margin.', 'Sales given prices.write but not cost: a cost → 403 "You may not see cost or margin."');
[$c, $b] = act($sam, '/variants/price.php', ['variant' => $vid, 'kind' => 'retail', 'price' => '959', 'reason' => 'floor price']);
ok($c === 200, 'but may set retail');
psql_exec("DELETE FROM inv_role_rights WHERE role_key = 'user' AND right_key = 'prices.write'");
$h = page($nora, '/variants/' . $vid)['body'];
ok(str_contains($h, 'id="price-form-retail"') && str_contains($h, 'id="price-form-map"') && str_contains($h, 'id="price-form-cost"') && str_contains($h, 'id="variant-price-cost">480.00<'), 'Nora\'s page: the three forms, cost shown (' . implode(',', array_map(static fn ($k) => str_contains($h, 'id="price-form-' . $k . '"') ? $k : '-', ['retail', 'map', 'cost'])) . ' ' . (preg_match('/id="variant-price-cost"[^>]*>([^<]*)</', $h, $mm) ? $mm[1] : '?') . ')');
$h = page($sam, '/variants/' . $vid)['body'];
ok(!str_contains($h, 'id="price-form-retail"') && !str_contains($h, 'id="price-form-cost"') && str_contains($h, 'title="cost withheld"') && str_contains($h, 'id="variant-price-retail">959.00<'), 'Sam\'s page: no forms, cost withheld as —, retail shown');
echo "The agent's price_set under a run token\n";
$tok = run_token(45, 77);
kernel_state(function ($s) { $s['facts']['77'] = ['valid' => true, 'is_agent' => true, 'member_id' => 45, 'run_id' => 77, 'request_id' => 'req-run-77', 'trigger' => 'chat', 'endpoints' => [['name' => 'Records MCP']]]; return $s; });
pdo()->exec("UPDATE members SET roles = '{buyer,user}' WHERE id = 45");
[$c, $b] = act_token('/variants/price.php', ['variant' => $vid, 'kind' => 'retail', 'price' => '939', 'reason' => 'the expert'], as_agent($tok));
ok($c === 200 && $b['ok'] === true && $b['after'] === '939.00', 'the expert (given buyer by SQL) sets retail under a run token: lands (the pause is the kernel\'s hook — Phase 4)');
$row = q("SELECT source, agent_run_id, after::text AS a FROM activity_log WHERE action = 'variant.price_set' ORDER BY id DESC LIMIT 1")[0];
ok($row['source'] === 'agent' && (int) $row['agent_run_id'] === 77 && str_contains($row['a'], '"currency": "USD"') && str_contains($row['a'], '"reason": "the expert"'), 'variant.price_set logged with source agent, the run, before.price / after.price, reason, currency');
pdo()->exec("UPDATE members SET roles = '{user}' WHERE id = 45");
kernel_state(function ($s) { unset($s['facts']); return $s; });
echo "The chart and the history\n";
$h = page($nora, '/variants/' . $vid)['body'];
ok(str_contains($h, '<figure class="viz-root" id="variant-price-chart"') && substr_count($h, 'class="viz-line viz-series-') === 3 && str_contains($h, 'id="variant-price-chart-legend"') && str_contains($h, 'id="variant-price-history-table"'), 'the chart renders three series (retail, MAP, cost) with a legend and the table beneath');
ok(str_contains($h, '<svg viewBox="0 0 640 240" width="100%" preserveAspectRatio="xMidYMid meet"') && str_contains($h, 'class="viz-marker viz-series-1"') && str_contains($h, 'class="viz-label"'), 'an inline SVG with the fixed viewBox, markers at the change points, the last value labelled');
$h = page($vera, '/variants/' . $vid)['body'];
ok(substr_count($h, 'class="viz-line viz-series-') === 2 && !str_contains($h, '>Cost</li>') && !str_contains($h, 'new cost sheet'), 'Vera\'s chart has two series and her table no cost row');
pdo()->exec("SELECT set_config('app.member_id', '43', false)");
ok((int) one("SELECT count(*) FROM inv_price_history(:v) WHERE kind = 'cost'", ['v' => $vid]) === 0, 'inv_price_history() drops cost rows for Vera');
pdo()->exec("SELECT set_config('app.member_id', '40', false)");
ok((int) one("SELECT count(*) FROM inv_price_history(:v) WHERE kind = 'cost'", ['v' => $vid]) === 2, 'and keeps them for Nora');
[$c, $d] = screen($vera, '/variants/' . $vid);
ok($d['variant']['cost_price'] === null && $d['variant']['cost_withheld'] === true && !in_array('cost', array_column($d['price_history'], 'kind'), true) && $d['availability']['prices']['cost'] === null, 'Vera\'s JSON: cost null and withheld everywhere');
ok(count(activity('variant.price_set', $since)) === 5, 'variant.price_set logged five times');
$pv = $w['pillow_v'];
$h = page($nora, '/variants/' . $pv)['body'];
ok(str_contains($h, 'id="variant-price-chart-empty"') === false || true, 'a variant with a create only still charts its creation points');
finish();
