<?php
/** Products: created as draft, attributes refused in words, activated, the kind rule, status=discontinued refused, discontinue/reactivate, the cards and filters, the logs. */
require __DIR__ . '/lib.php';
$w = catalog_world();
$nora = as_member(40); $vera = as_member(43); $owner = as_member(1);
echo "1. Create and update\n";
$since = last_activity_id();
[$c, $b] = act($nora, '/products/save.php', ['name' => 'SMOKE Draft Mattress', 'type' => 'mattress', 'brand' => 'SMOKE Zinus', 'attributes' => json_encode(['type' => 'memory_foam', 'firmness' => 7, 'certifications' => ['CertiPUR-US']]), 'tags' => 'foam, cooling, foam']);
ok($c === 200 && $b['ok'] === true && $b['record_id'] > 0 && $b['location'] === '/products/' . $b['record_id'] . '?notice=created' && $b['refresh'] === 'productChanged', 'created: {ok, record_id, location /products/{id}, refresh productChanged}');
$pid = (int) $b['record_id'];
$row = q('SELECT status, kind, options::text AS options, attributes::text AS attributes, tags::text AS tags, brand_id FROM products WHERE id = :id', ['id' => $pid])[0];
ok($row['status'] === 'draft' && $row['kind'] === 'single' && $row['options'] === '["Size"]', 'draft by default, single, options ["Size"]');
ok(json_decode($row['attributes'], true) === ['type' => 'memory_foam', 'firmness' => 7, 'certifications' => ['CertiPUR-US']] && $row['tags'] === '{foam,cooling}', 'attributes typed by key (a number as a number, a multi as a list); tags trimmed and unique');
ok((int) $row['brand_id'] === $w['brand_zinus'], 'the brand given by name resolved to its id (an agent\'s way)');
[$c, $b] = act($nora, '/products/save.php', ['name' => 'X', 'type' => 'mattress', 'attributes' => json_encode(['nope' => 1])]);
ok($c === 422 && str_starts_with(fields($b)['attributes'] ?? '', 'Unknown attribute: nope.'), 'an unknown attribute key: 422 in words naming the keys');
[$c, $b] = act($nora, '/products/save.php', ['name' => 'X', 'type' => 'mattress', 'attributes' => json_encode(['type' => 'jelly'])]);
ok($c === 422 && str_contains(fields($b)['attributes'] ?? '', 'is one of'), 'a choice outside its list: 422');
[$c, $b] = act($nora, '/products/save.php', ['name' => 'X', 'type' => 'nosuchtype']);
ok($c === 422 && isset(fields($b)['type']), 'a type that is not here: 422 naming the field');
[$c, $b] = act($nora, '/products/save.php', ['name' => 'X', 'type' => 'mattress', 'options' => ['Size', 'A', 'B', 'C']]);
ok($c === 422 && str_contains(fields($b)['options'] ?? '', 'at most three'), 'four options: 422');
[$c, $b] = act($nora, '/products/save.php', ['product' => $pid, 'status' => 'active']);
ok($c === 200 && one('SELECT status FROM products WHERE id = :id', ['id' => $pid]) === 'active' && one('SELECT name FROM products WHERE id = :id', ['id' => $pid]) === 'SMOKE Draft Mattress', 'activated through an update; the name stayed (a field left out stays)');
[$c, $b] = act($nora, '/products/save.php', ['product' => $pid, 'status' => 'discontinued']);
ok($c === 422 && str_contains(fields($b)['status'] ?? '', 'product_discontinue'), 'status=discontinued on save: refused pointing at product_discontinue');
[$c, $b] = act($nora, '/products/save.php', ['product' => $pid, 'options' => ['Size', 'Firmness']]);
ok($c === 200 && one('SELECT options::text FROM products WHERE id = :id', ['id' => $pid]) === '["Size", "Firmness"]', 'a second option added');
[$c, $b] = act($nora, '/products/save.php', ['product' => $pid, 'options' => ['Firmness']]);
ok($c === 200 && one('SELECT options::text FROM products WHERE id = :id', ['id' => $pid]) === '["Size", "Firmness"]', 'Size is fixed first: an options list without it gets it back');
// the kind rule: a product with a matched variant cannot change kind
act($nora, '/variants/save.php', ['product' => $pid, 'sku' => 'SMOKE-DRAFT-Q', 'option_values' => json_encode(['Size' => 'Queen', 'Firmness' => 'Medium'])]);
$vid = variant_id('SMOKE-DRAFT-Q');
[$c, $b] = act($nora, '/products/save.php', ['product' => $pid, 'options' => ['Size']]);
ok($c === 422 && str_contains(fields($b)['options'] ?? '', 'used by a variant'), 'removing an option a variant uses: refused in words');
pdo()->exec("INSERT INTO suppliers (name) VALUES ('SMOKE Dreamland') ON CONFLICT DO NOTHING");
$sup = (int) one("SELECT id FROM suppliers WHERE name = 'SMOKE Dreamland'");
pdo()->exec("INSERT INTO sources (name, connector, role, supplier_id, base_url, created_by) VALUES ('SMOKE Dreamland feed', 'manual', 'supplier', $sup, 'https://dreamland.example', 40)");
$src = (int) one("SELECT id FROM sources WHERE name = 'SMOKE Dreamland feed'");
pdo()->exec("INSERT INTO listings (source_id, external_id, title) VALUES ($src, 'ext-1', 'SMOKE Draft listing')");
$lid = (int) one("SELECT id FROM listings WHERE external_id = 'ext-1'");
pdo()->exec("INSERT INTO listing_variants (listing_id, external_variant_id, title, option_values, variant_id, match_kind) VALUES ($lid, 'ev-1', 'Queen', '{\"Size\":\"Queen\"}', $vid, 'manual')");
[$c, $b] = act($nora, '/products/save.php', ['product' => $pid, 'kind' => 'bundle']);
ok($c === 422 && str_contains(fields($b)['kind'] ?? '', 'cannot change'), 'a kind change on a product with a matched variant: the handler\'s sentence');
echo "2. Discontinue and reactivate\n";
[$c, $b] = act($nora, '/products/discontinue.php', ['product' => $pid]);
ok($c === 200 && $b['discontinued'] === true && one('SELECT status FROM products WHERE id = :id', ['id' => $pid]) === 'discontinued' && one('SELECT discontinued_at FROM products WHERE id = :id', ['id' => $pid]) !== null, 'discontinued: status and discontinued_at set by the trigger');
ok(act($nora, '/products/discontinue.php', ['product' => $pid])[0] === 422, 'discontinuing it again: 422');
ok(act($nora, '/products/save.php', ['product' => $pid, 'status' => 'active'])[0] === 422, 'activating a discontinued product through save: refused pointing at product_discontinue');
[$c, $b] = act($nora, '/products/discontinue.php', ['product' => $pid, 'discontinued' => 'no']);
ok($c === 200 && one('SELECT status FROM products WHERE id = :id', ['id' => $pid]) === 'active' && one('SELECT discontinued_at FROM products WHERE id = :id', ['id' => $pid]) === null, 'reactivated: active, discontinued_at cleared');
ok(act($vera, '/products/discontinue.php', ['product' => $pid])[0] === 403, 'Vera may not discontinue');
$log = activity('product.create', $since);
ok(count($log) === 1 && (int) $log[0]['entity_id'] === $pid && str_contains((string) $log[0]['after'], '"options"') && !str_contains((string) $log[0]['after'], 'A hybrid'), 'product.create logged with entity_id = the product, its options, never the description\'s words');
ok(count(activity('product.update', $since)) >= 2 && count(activity('product.discontinue', $since)) === 2, 'product.update (' . count(activity('product.update', $since)) . ') and product.discontinue logged');
echo "3. The cards and filters\n";
[$c, $d] = screen($nora, '/products/');
ok($c === 200 && $d['total'] >= 6 && isset($d['products'][0]['state']) && isset($d['products'][0]['variant_count']), 'the list answers JSON: total, products with their state and variant count');
act($nora, '/products/discontinue.php', ['product' => $pid]);
[$c, $d] = screen($nora, '/products/');
ok(!in_array($pid, array_column($d['products'], 'product_id'), true), 'the default status hides a discontinued product');
[$c, $d] = screen($nora, '/products/?status=all');
ok(in_array($pid, array_column($d['products'], 'product_id'), true), '?status=all shows it');
[$c, $d] = screen($nora, '/products/?status=discontinued');
ok(count($d['products']) === 1 && $d['products'][0]['product_id'] === $pid, '?status=discontinued shows only it');
act($nora, '/products/discontinue.php', ['product' => $pid, 'discontinued' => 'no']);
[$c, $d] = screen($nora, '/products/?q=cloudrest');
ok(count($d['products']) >= 2 && in_array($w['mattress'], array_column($d['products'], 'product_id'), true), '?q=cloudrest finds the Cloudrest products by name through inv_find');
[$c, $d] = screen($nora, '/products/?q=850123450035');
ok(count($d['products']) === 1 && $d['products'][0]['product_id'] === $w['mattress'], '?q= with a GTIN finds the one product (the barcode)');
[$c, $d] = screen($nora, '/products/?q=SMOKE-NW-CR-K');
ok(count($d['products']) === 1 && ($d['products'][0]['product_id'] ?? null) === $w['mattress'], '?q= with a SKU finds it (' . json_encode(array_column($d['products'], 'name')) . ')');
[$c, $d] = screen($nora, '/products/?brand=' . $w['brand_zinus']);
ok($d['products'] !== [] && count(array_unique(array_column($d['products'], 'brand_id'))) === 1, '?brand= filters');
[$c, $d] = screen($nora, '/products/?type=topper');
ok(count($d['products']) === 1 && $d['products'][0]['product_id'] === $w['topper'], '?type= by key filters');
[$c, $d] = screen($nora, '/products/?kind=bundle');
ok(count($d['products']) === 1 && $d['products'][0]['product_id'] === $w['set'], '?kind=bundle shows the set');
$h = page($nora, '/products/')['body'];
ok(str_contains($h, 'id="product-card-' . $w['mattress'] . '"') && str_contains($h, 'id="product-list-filters"') && str_contains($h, 'id="product-list-new-btn"') && str_contains($h, 'bundle</span>'), 'the cards, the filters, New product; the set wears its bundle chip');
ok(!str_contains(page($vera, '/products/')['body'], 'id="product-list-new-btn"'), 'Vera sees no New product');
[$c, $d] = screen($nora, '/products/' . $w['mattress']);
ok($c === 200 && $d['product']['name'] === 'SMOKE Cloudrest Hybrid' && count($d['variants']) === 6 && isset($d['variants'][0]['state']) && $d['may']['write'] === true, 'the product answers JSON: the product, six variants with their state, may.write');
$h = page($nora, '/products/' . $w['mattress'])['body'];
ok(str_contains($h, 'id="product-variants-table"') && str_contains($h, 'id="variant-row-' . $w['queen'] . '"') && str_contains($h, 'data-screen="product-view"') && str_contains($h, 'data-record-id="' . $w['mattress'] . '"'), 'the product page: the variants table, the context stamped');
ok(str_contains($h, 'id="product-view-edit-btn"') && str_contains($h, 'id="product-view-discontinue-btn"') && str_contains($h, 'id="product-view-add-variant-btn"') && !str_contains($h, 'id="product-view-delete-btn"'), 'Nora: Edit, Discontinue, Add variant; no Delete (records.delete is the admin\'s)');
foreach (['identifiers', 'bundle', 'images', 'sources', 'prices', 'notes', 'trail'] as $t) {
    $code = page($nora, '/products/' . $w['set'] . '?tab=' . $t)['code'];
    if ($code !== 200) { ok(false, "tab $t: $code"); }
}
ok(true, 'every tab of the set renders (identifiers, bundle, images, sources, prices, notes, trail)');
ok(str_contains(page($nora, '/products/' . $w['mattress'] . '?tab=sources')['body'], 'slice 3') && str_contains(page($nora, '/products/' . $w['mattress'] . '?tab=notes')['body'], 'slice 8'), 'the Sources and Notes tabs name their slices while empty');
ok(str_contains(page($nora, '/products/' . $pid . '?tab=sources')['body'], 'SMOKE Draft listing'), 'the Sources tab lists a listing matched to a variant');
ok(page($nora, '/products/999999')['code'] === 404 && page($nora, '/products/999999/edit')['code'] === 404, 'a product that does not exist: 404');
finish();
