<?php
/** Variants: size_key derived, GTIN-14, a bad check digit, duplicates, imperial inputs, the prices on a create, the update rules, _partial, inactive hides. */
require __DIR__ . '/lib.php';
$w = catalog_world();
$nora = as_member(40); $vera = as_member(43); $sam = as_member(41);
echo "1. Create\n";
$since = last_activity_id();
[$c, $b] = act($nora, '/variants/save.php', ['product' => $w['topper'], 'sku' => 'SMOKE-HP-LT-K-3', 'option_values' => json_encode(['Size' => 'King', 'Thickness' => '3 inch']), 'barcode' => '850123450127', 'mpn' => 'HPLT-K', 'retail_price' => '549', 'map_price' => '549', 'cost_price' => '250', 'weight' => '12.25', 'length' => '80', 'width' => '76', 'height' => '3']);
ok($c === 200 && $b['ok'] && $b['record_id'] > 0 && $b['location'] === '/variants/' . $b['record_id'] . '?notice=created' && $b['product_id'] === $w['topper'], 'created: {ok, record_id, location /variants/{id}, product_id}');
$vid = (int) $b['record_id'];
$v = q('SELECT sku, size_key, barcode, option_values::text AS ov, weight_g, length_mm, width_mm, height_mm, retail_price, map_price, cost_price, cost_updated_at FROM product_variants WHERE id = :id', ['id' => $vid])[0];
ok($v['size_key'] === 'king' && json_decode($v['ov'], true) === ['Size' => 'King', 'Thickness' => '3 inch'], 'size_key derived (king); the two option values kept');
ok($v['barcode'] === '00850123450127', 'the UPC stored as GTIN-14');
ok((int) $v['weight_g'] === 5557 && (int) $v['length_mm'] === 2032 && (int) $v['width_mm'] === 1930 && (int) $v['height_mm'] === 76, 'imperial inputs stored in g / mm (12.25 lb → 5557 g, 80 in → 2032 mm)');
ok($v['retail_price'] === '549.00' && $v['cost_price'] === '250.00' && $v['cost_updated_at'] !== null, 'the three prices on the create; cost_updated_at set');
$hist = q('SELECT kind, new_price, reason, source_kind FROM price_history WHERE variant_id = :v ORDER BY id', ['v' => $vid]);
ok(count($hist) === 3 && $hist[0]['reason'] === 'created' && $hist[0]['source_kind'] === 'manual' && array_column($hist, 'kind') === ['retail', 'map', 'cost'], 'three price_history rows with reason "created", source manual');
[$c, $d] = screen($nora, '/variants/' . $vid);
ok($c === 200 && $d['variant']['weight_g'] === 5557 && $d['variant']['size_name'] === 'King', 'the variant answers JSON');
$h = page($nora, '/variants/' . $vid . '/edit')['body'];
ok(str_contains($h, 'value="12.25"') && str_contains($h, 'value="80.0"') && str_contains($h, 'id="variant-form-prices-readonly"'), 'the edit form shows the weight and length back in imperial and the prices read-only' . (str_contains($h, 'value="12.25"') && str_contains($h, 'value="80.0"') && str_contains($h, 'prices-readonly') ? '' : ' (weight: ' . (preg_match('/id="variant-form-field-weight"[^>]*value="([^"]*)"/', $h, $mm) ? $mm[1] : '?') . ' length: ' . (preg_match('/id="variant-form-field-length"[^>]*value="([^"]*)"/', $h, $mm2) ? $mm2[1] : '?') . ' readonly: ' . (str_contains($h, 'prices-readonly') ? 'y' : 'n') . ' code ' . page($nora, '/variants/' . $vid . '/edit')['code'] . ')'));
[$c, $b] = act($nora, '/variants/save.php', ['product' => $w['mattress'], 'sku' => 'SMOKE-BAD', 'option_values' => json_encode(['Size' => 'Twin']), 'barcode' => '012345678906']);
ok($c === 422 && str_contains(msg($b), 'is not a GTIN'), 'a bad check digit: 422 with the trigger\'s sentence');
[$c, $b] = act($nora, '/variants/save.php', ['product' => $w['mattress'], 'sku' => 'smoke-nw-cr-q', 'option_values' => json_encode(['Size' => 'Twin'])]);
ok($c === 422 && msg($b) === 'That SKU is already taken.', 'a duplicate SKU (whatever its case): 422');
[$c, $b] = act($nora, '/variants/save.php', ['product' => $w['mattress'], 'sku' => 'SMOKE-DUP-BC', 'option_values' => json_encode(['Size' => 'Twin']), 'barcode' => '850123450035']);
ok($c === 422 && str_contains(msg($b), 'barcode is already'), 'a duplicate barcode: 422');
[$c, $b] = act($nora, '/variants/save.php', ['product' => $w['mattress'], 'sku' => '', 'option_values' => json_encode(['Size' => 'Twin'])]);
ok($c === 422 && isset(fields($b)['sku']), 'an empty SKU: 422 naming the field');
[$c, $b] = act($nora, '/variants/save.php', ['product' => $w['mattress'], 'sku' => 'SMOKE-NOSIZE', 'option_values' => json_encode([])]);
ok($c === 422 && isset(fields($b)['option_values']), 'no Size on a product with Size: 422');
[$c, $b] = act($nora, '/variants/save.php', ['product' => $w['mattress'], 'sku' => 'SMOKE-WRONGOPT', 'option_values' => json_encode(['Size' => 'Twin', 'Colour' => 'Blue'])]);
ok($c === 422 && str_contains(fields($b)['option_values'] ?? '', 'no option "Colour"'), 'an option the product does not have: 422 in words');
[$c, $b] = act($nora, '/variants/save.php', ['product' => $w['mattress'], 'sku' => 'SMOKE-NW-CR-SQ', 'option_values' => json_encode(['Size' => 'Split Cal King']), 'retail_price' => '2199']);
ok($c === 200 && one('SELECT size_key FROM product_variants WHERE id = :id', ['id' => $b['record_id']]) === 'split_california_king', 'a synonym ("Split Cal King") lands on its size key');
[$c, $b] = act($nora, '/variants/save.php', ['product' => $w['mattress'], 'sku' => 'SMOKE-NW-CR-ODD', 'option_values' => json_encode(['Size' => 'Olympic Queen Plus']), 'retail_price' => '2199']);
ok($c === 200 && one('SELECT size_key FROM product_variants WHERE id = :id', ['id' => $b['record_id']]) === 'olympic_queen_plus', 'an unknown size is its own slug (two unknown spellings still agree)');
ok(act($nora, '/variants/save.php', ['product' => 999999, 'sku' => 'X'])[0] === 404, 'a product that does not exist: 404');
ok(act($vera, '/variants/save.php', ['product' => $w['mattress'], 'sku' => 'SMOKE-VERA'])[0] === 403, 'Vera may not create a variant');
ok(act($sam, '/variants/save.php', ['product' => $w['mattress'], 'sku' => 'SMOKE-SAM', 'option_values' => json_encode(['Size' => 'Twin']), 'cost_price' => '1'])[0] === 403, 'Sam (no catalog.write) may not either');
echo "2. Update\n";
[$c, $b] = act($nora, '/variants/save.php', ['variant' => $vid, 'retail_price' => '599']);
ok($c === 422 && str_contains(fields($b)['retail_price'] ?? '', 'price_set'), 'an update with retail_price: refused pointing at price_set');
[$c, $b] = act($nora, '/variants/save.php', ['variant' => $vid, 'cost_price' => '1']);
ok($c === 422 && isset(fields($b)['cost_price']), 'and with cost_price');
[$c, $b] = act($nora, '/variants/save.php', ['variant' => $vid, 'mpn' => 'HPLT-K2', 'reorder_point' => '3', 'reorder_qty' => '6']);
ok($c === 200 && q('SELECT mpn, reorder_point, reorder_qty, sku, weight_g FROM product_variants WHERE id = :id', ['id' => $vid])[0] === ['mpn' => 'HPLT-K2', 'reorder_point' => 3, 'reorder_qty' => 6, 'sku' => 'SMOKE-HP-LT-K-3', 'weight_g' => 5557], 'an update changes what was sent and keeps the rest (the SKU, the weight)');
$log = activity('variant.update', $since);
ok($log !== [] && str_contains((string) end($log)['after'], '"product_id"') && str_contains((string) end($log)['before'], 'HPLT-K"'), 'variant.update logged with before/after and product_id');
[$c, $b] = act($nora, '/variants/save.php', ['variant' => $vid, 'active' => 'no']);
ok($c === 200 && one('SELECT active FROM product_variants WHERE id = :id', ['id' => $vid]) === false, 'deactivated');
pdo()->exec("SELECT set_config('app.member_id', '40', false)");
ok((int) one("SELECT count(*) FROM inv_find('SMOKE-HP-LT-K-3') WHERE sku = 'SMOKE-HP-LT-K-3'") === 0, 'an inactive variant is hidden from inv_find');
act($nora, '/variants/save.php', ['variant' => $vid, 'active' => 'yes']);
pdo()->exec("SELECT set_config('app.member_id', '40', false)");
ok((int) one("SELECT count(*) FROM inv_find('SMOKE-HP-LT-K-3') WHERE sku = 'SMOKE-HP-LT-K-3'") === 1, 'and found again once active');
[$c, $b] = act($nora, '/variants/save.php', ['variant' => $vid, 'weight_g' => '6000', 'length_mm' => '2000']);
ok($c === 200 && (int) one('SELECT weight_g FROM product_variants WHERE id = :id', ['id' => $vid]) === 6000, 'an agent may send weight_g / length_mm directly (stored as given)');
echo "3. The agent's door: _partial\n";
$tok = person_token(40);
[$c, $b] = act_token('/variants/save.php', ['variant' => $vid, 'mpn' => 'HPLT-K3', '_partial' => '1'], ['X-Action-Token: ' . $tok]);
ok($c === 200 && one('SELECT mpn FROM product_variants WHERE id = :id', ['id' => $vid]) === 'HPLT-K3' && one('SELECT sku FROM product_variants WHERE id = :id', ['id' => $vid]) === 'SMOKE-HP-LT-K-3' && (int) one('SELECT weight_g FROM product_variants WHERE id = :id', ['id' => $vid]) === 6000, '_partial=1 under the action token keeps the untouched fields');
$cnt = count(activity('variant.create', $since));
ok($cnt >= 3 && str_contains((string) activity('variant.create', $since)[0]['after'], '"retail_price"'), "variant.create logged ($cnt) with the prices set");
finish();
