<?php
/** Adjustments (stock.md "Proof — Adjustments"): a damaged unit, a donation, the CHECK and the trigger in their words, a return reason refused, cost walled, cancel, the log. */
require __DIR__ . '/lib.php';
$w = stock_world();
$wes = as_member(42);
$nora = as_member(40);
$since = last_activity_id();
$q0 = on_hand($w['queen'], $w['wh']);
echo "1. Damaged\n";
[$c, $b] = act($wes, '/adjustments/save.php', ['location' => $w['wh'], 'reason' => 'damaged', 'notes' => 'forklift']);
ok($c === 200 && $b['ok'] === true, 'Wes drafts a damaged adjustment at the Warehouse');
$aid = (int) $b['record_id'];
ok(preg_match('/^ADJ-\d{5}$/', (string) one('SELECT number FROM inventory_adjustments WHERE id = :id', ['id' => $aid])) === 1, 'numbered ADJ-…');
[$c, $b] = act($wes, '/adjustments/lines/save.php', ['adjustment' => $aid, 'barcode' => '00850123450035', 'qty_delta' => '-1']);
ok($c === 200 && (int) one('SELECT qty_delta FROM inventory_adjustment_lines WHERE id = :id', ['id' => $b['record_id']]) === -1, 'a line −1 Queen by its scanned GTIN');
[$c, $b] = act($wes, '/adjustments/lines/save.php', ['adjustment' => $aid, 'variant' => $w['queen'], 'qty_delta' => '0']);
ok($c === 422 && fields($b)['qty_delta'] === 'The quantity change is never zero.', 'a zero delta is refused: "The quantity change is never zero."');
$sql = psql_exec("SET ROLE inventory_rw; INSERT INTO inventory_adjustment_lines (adjustment_id, line_no, variant_id, qty_delta) VALUES ($aid, 7, {$w['queen']}, 0)");
ok(str_contains($sql, 'inventory_adjustment_lines_qty_delta_check'), '…and by the CHECK when SQL tries');
[$c, $b] = act($wes, '/adjustments/lines/save.php', ['adjustment' => $aid, 'barcode' => '00850123450035']);
ok($c === 422 && isset(fields($b)['qty_delta']), 'a scan with no change typed is refused by field (the screen stops at the delta)');
[$c, $b] = act($wes, '/adjustments/lines/save.php', ['adjustment' => $aid, 'variant' => $w['king'], 'qty_delta' => '-1', 'unit_cost' => '10.00']);
ok($c === 422 && fields($b)['unit_cost'] === 'You may not set a cost on an adjustment — leave unit cost empty.', 'Wes (no cost wall) sending unit_cost is refused in words, not dropped');
[$c, $d] = screen($wes, '/adjustments/' . $aid);
ok($c === 200 && count($d['lines']) === 1 && $d['cost_withheld'] === true && $d['lines'][0]['unit_cost'] === null, 'Wes reads the adjustment with cost withheld');
[$c, $b] = act($wes, '/adjustments/post.php', ['adjustment' => $aid]);
ok($c === 200 && $b['units_delta'] === -1, 'posted (stock_adjust): −1');
ok(on_hand($w['queen'], $w['wh']) === $q0 - 1, "on hand Queen at the Warehouse: $q0 → " . ($q0 - 1));
$t = txns('adjustment', $aid)[0];
$qc = (string) one('SELECT cost_price FROM product_variants WHERE id = :v', ['v' => $w['queen']]);
ok($t['txn_type'] === 'adjustment' && $t['counterparty_kind'] === 'none' && (int) $t['reason_code_id'] === (int) one("SELECT id FROM reason_codes WHERE code = 'damaged'") && $t['unit_cost'] === $qc, "the movement: adjustment, counterparty none, reason damaged, at the variant's cost ($qc)");
$l = last_log('stock.adjust', $since);
ok($l !== null && (int) $l['location_id'] === $w['wh'] && after_of($l)['units_delta'] === -1 && after_of($l)['amount'] === '-' . $qc && after_of($l)['reason_code'] === 'damaged', "stock.adjust logged: location_id, units_delta −1, amount −$qc, reason");
echo "2. A donation, a shortfall, a wrong reason\n";
[, $b] = act($nora, '/adjustments/save.php', ['location' => $w['wh'], 'reason' => 'donation', 'lines' => json_encode([['variant' => 'SMOKE-NW-CR-F', 'qty_delta' => -1, 'unit_cost' => '140.00', 'note' => 'to the shelter']])]);
$don = (int) $b['record_id'];
ok((int) one('SELECT count(*) FROM inventory_adjustment_lines WHERE adjustment_id = :a', ['a' => $don]) === 1 && one('SELECT unit_cost FROM inventory_adjustment_lines WHERE adjustment_id = :a', ['a' => $don]) === '140.00', 'Nora drafts a donation with `lines` JSON by SKU and a cost (she sees cost)');
[$c, $b] = act($nora, '/adjustments/post.php', ['adjustment' => $don]);
$t = txns('adjustment', $don)[0];
ok($c === 200 && $t['counterparty_kind'] === 'disposal' && $t['unit_cost'] === '140.00', 'a donation posts with counterparty disposal at the line\'s cost');
[, $b] = act($wes, '/adjustments/save.php', ['location' => $w['wh'], 'reason' => 'lost']);
$short = (int) $b['record_id'];
act($wes, '/adjustments/lines/save.php', ['adjustment' => $short, 'variant' => $w['queen'], 'qty_delta' => '-5']);
[$c, $b] = act($wes, '/adjustments/post.php', ['adjustment' => $short]);
ok($c === 422 && str_contains(msg($b), 'Not enough on hand'), '−5 where 1 is on hand: the trigger\'s "' . msg($b) . '"');
ok(one('SELECT status FROM inventory_adjustments WHERE id = :id', ['id' => $short]) === 'draft' && count(txns('adjustment', $short)) === 0, 'the draft stays a draft and nothing posted');
[$c, $b] = act($wes, '/adjustments/save.php', ['location' => $w['wh'], 'reason' => 'comfort']);
ok($c === 422 && fields($b)['reason'] === 'The reason Comfort is not an adjustment reason', 'a return reason on an adjustment: "' . (fields($b)['reason'] ?? '') . '"');
[$c, $b] = act($wes, '/adjustments/save.php', ['adjustment' => $short, 'location' => $w['sr']]);
ok($c === 422 && str_contains(msg($b), 'changes only while it has no lines'), 'the location of a draft with lines does not change: "' . msg($b) . '"');
[$c, $b] = act($wes, '/adjustments/save.php', ['adjustment' => $short, 'reason' => 'correction', '_partial' => '1']);
ok($c === 200 && one('SELECT rc.code FROM inventory_adjustments a JOIN reason_codes rc ON rc.id = a.reason_code_id WHERE a.id = :id', ['id' => $short]) === 'correction' && (int) one('SELECT location_id FROM inventory_adjustments WHERE id = :id', ['id' => $short]) === $w['wh'], 'the reason changes, the location stays (_partial)');
$line = (int) one('SELECT id FROM inventory_adjustment_lines WHERE adjustment_id = :a', ['a' => $short]);
[$c, $b] = act($wes, '/adjustments/lines/remove.php', ['line' => $line]);
ok($c === 200 && last_log('stock.adjustment_line_remove', $since) !== null, 'a line removed, logged');
[$c, $b] = act($wes, '/adjustments/cancel.php', ['adjustment' => $short]);
ok($c === 200 && one('SELECT status FROM inventory_adjustments WHERE id = :id', ['id' => $short]) === 'cancelled' && last_log('stock.adjustment_cancel', $since) !== null, 'the draft cancelled, logged');
[$c, $b] = act($wes, '/adjustments/cancel.php', ['adjustment' => $aid]);
ok($c === 422 && str_contains(msg($b), 'is posted — reverse its movements instead'), 'a posted adjustment does not cancel');
[$c, $b] = act(as_member(41), '/adjustments/save.php', ['location' => $w['wh'], 'reason' => 'found']);
ok($c === 403, 'Sam (no stock.adjust) may not adjust');
[$c, $d] = screen($wes, '/adjustments/new?variant=' . $w['king'] . '&location=' . $w['wh']);
ok($c === 200 && count($d['reasons']) === 7, 'the new-adjustment form offers the seven adjustment reasons');
[$c, $b] = act($wes, '/adjustments/save.php', ['location' => $w['wh'], 'reason' => 'found', 'variant' => $w['king'], 'qty_delta' => '1']);
ok($c === 200 && (int) one('SELECT qty_delta FROM inventory_adjustment_lines WHERE adjustment_id = :a', ['a' => $b['record_id']]) === 1, 'adjustment-add with a variant drafts its first line');
act($wes, '/adjustments/cancel.php', ['adjustment' => $b['record_id']]);
finish();
