<?php
/** Counts (stock.md "Proof — Counts"): one open per location, the running count by scan, a typed 0, a new line for a variant with nothing there, the schema's rule (a receipt mid-count is not counted twice), uncounted lines untouched, the deletion approval. */
require __DIR__ . '/lib.php';
$w = stock_world();
$wes = as_member(42);
$since = last_activity_id();
psql_exec("SELECT inv_post_txn('receipt', {$w['pillow_v']}, {$w['sr']}, 2, NULL, 'opening', 2, 'smoke-opening-pillow-sr')");
$k0 = on_hand($w['king'], $w['sr']);
$f0 = on_hand($w['full'], $w['sr']);
echo "1. Start\n";
[$c, $b] = act($wes, '/counts/start.php', ['location' => $w['sr'], 'notes' => 'Friday count']);
ok($c === 200 && $b['ok'] === true && $b['location'] === '/counts/' . $b['record_id'] . '?notice=started', 'Wes starts a count at the Showroom');
$cid = (int) $b['record_id'];
$lines = q('SELECT variant_id, system_qty, counted_qty FROM inventory_count_lines WHERE count_id = :c ORDER BY variant_id', ['c' => $cid]);
$sys = array_column($lines, 'system_qty', 'variant_id');
ok(count($lines) === 3 && (int) $sys[$w['king']] === $k0 && (int) $sys[$w['full']] === $f0 && (int) $sys[$w['pillow_v']] === 2, "a line per variant held there, the system quantity frozen (King $k0, Full $f0, Pillow 2)");
ok(preg_match('/^CNT-\d{5}$/', (string) one('SELECT number FROM inventory_counts WHERE id = :id', ['id' => $cid])) === 1 && after_of(last_log('stock.count_start', $since))['lines'] === 3, 'numbered CNT-…; stock.count_start logged with lines 3');
[$c, $b] = act($wes, '/counts/start.php', ['location' => $w['sr']]);
ok($c === 422 && msg($b) === 'A count is already open at that location', 'a second start at the Showroom: "A count is already open at that location"');
echo "2. Count\n";
foreach ([1, 2, 3] as $n) { [$c, $b] = act($wes, '/counts/lines/save.php', ['count' => $cid, 'barcode' => '850123450042']); }
ok($c === 200 && $b['counted_qty'] === 3 && $b['created'] === false, 'the King scanned three times: counted 3 (the running count)');
[$c, $b] = act($wes, '/counts/lines/save.php', ['count' => $cid, 'variant' => $w['full'], 'counted_qty' => '0']);
ok($c === 200 && (int) one('SELECT counted_qty FROM inventory_count_lines WHERE count_id = :c AND variant_id = :v', ['c' => $cid, 'v' => $w['full']]) === 0, 'Wes types 0 for the Full');
$l = last_log('stock.count_line', $since);
ok($l !== null && after_of($l)['counted_qty'] === 0 && after_of($l)['system_qty'] === $f0 && (int) $l['location_id'] === $w['sr'], 'stock.count_line logged with sku, system_qty, counted_qty, location_id');
[$c, $b] = act($wes, '/counts/lines/save.php', ['count' => $cid, 'barcode' => '850123450004']);
ok($c === 200 && $b['created'] === true && $b['system_qty'] === 0 && $b['counted_qty'] === 1, 'the Twin (nothing there) scanned: a new line, system 0, counted 1');
[$c, $b] = act($wes, '/counts/lines/save.php', ['count' => $cid, 'variant' => $w['full'], 'counted_qty' => '-1']);
ok($c === 422 && isset(fields($b)['counted_qty']), 'a negative count is refused');
[$c, $b] = act($wes, '/counts/lines/save.php', ['count' => $cid, 'variant' => $w['full']]);
ok($c === 422 && isset(fields($b)['counted_qty']), 'a typed line with no quantity is refused (only a scan adds one)');
[$c, $b] = act($wes, '/counts/lines/save.php', ['count' => $cid, 'barcode' => 'SMOKE-SET-Q']);
ok($c === 422 && str_contains(fields($b)['barcode'] ?? '', 'A bundle never holds stock'), 'a bundle is refused');
[$c, $d] = screen($wes, '/counts/' . $cid);
ok($c === 200 && $d['count']['lines_counted'] === 3 && $d['count']['lines_differing'] === 3 && count($d['lines']) === 4, 'the counting screen: 4 lines, 3 counted, 3 differing');
echo "3. A receipt mid-count, then post\n";
[, $b] = act($wes, '/receipts/save.php', ['location' => $w['sr'], 'lines' => json_encode([['variant' => 'SMOKE-NW-CR-K', 'qty' => 2]])]);
act($wes, '/receipts/post.php', ['receipt' => $b['record_id']]);
ok(on_hand($w['king'], $w['sr']) === $k0 + 2, 'a receipt of 2 King posted at the Showroom mid-count (on hand ' . ($k0 + 2) . ')');
[$c, $b] = act($wes, '/counts/post.php', ['count' => $cid]);
ok($c === 200 && $b['corrections'] === 3, 'posted: three corrections');
$t = q("SELECT variant_id, qty, txn_type, reason_code_id FROM inventory_transactions WHERE reference_kind = 'count' AND reference_id = :c ORDER BY variant_id", ['c' => $cid]);
$by = array_column($t, 'qty', 'variant_id');
ok((int) $by[$w['king']] === 3 - ($k0 + 2), 'the King\'s correction is counted − on hand NOW: 3 − ' . ($k0 + 2) . ' = ' . (3 - ($k0 + 2)) . ' (the mid-count receipt is not counted twice)');
ok((int) $by[$w['full']] === -$f0 && (int) $by[$w['twin']] === 1, "the Full −$f0, the Twin +1");
ok(!isset($by[$w['pillow_v']]) && on_hand($w['pillow_v'], $w['sr']) === 2, 'the uncounted pillow is untouched');
ok($t[0]['txn_type'] === 'count_correction' && (int) $t[0]['reason_code_id'] === (int) one("SELECT id FROM reason_codes WHERE code = 'correction'"), 'count_correction movements, reason correction');
ok(on_hand($w['king'], $w['sr']) === 3 && on_hand($w['full'], $w['sr']) === 0 && on_hand($w['twin'], $w['sr']) === 1, 'the Showroom now holds what was counted: King 3, Full 0, Twin 1');
$a = after_of(last_log('stock.count_post', $since));
ok($a['corrections'] === 3 && $a['lines'] === 4 && $a['units_delta'] === (3 - ($k0 + 2)) - $f0 + 1, 'stock.count_post logged: lines, corrections, units_delta');
[$c, $b] = act($wes, '/counts/lines/save.php', ['count' => $cid, 'variant' => $w['full'], 'counted_qty' => '5']);
ok($c === 422 && str_contains(msg($b), 'is posted — only an open count changes'), 'a line after posting is refused: "' . msg($b) . '"');
$sql = psql_exec("SET ROLE inventory_rw; UPDATE inventory_count_lines SET counted_qty = 9 WHERE count_id = $cid");
ok(str_contains($sql, 'change only while it is open, it is posted'), '…and by the trigger when SQL tries');
[$c, $d] = screen($wes, '/counts/' . $cid);
$kl = array_values(array_filter($d['lines'], static fn ($l) => $l['variant_id'] === $w['king']))[0];
ok($kl['correction_transaction_id'] !== null && $kl['correction_qty'] === 3 - ($k0 + 2), 'the posted count shows each line\'s correction');
echo "4. Cancel, the approval\n";
[$c, $b] = act($wes, '/counts/start.php', ['location' => $w['sr']]);
ok($c === 200, 'a new count may open now the first is posted');
$c2 = (int) $b['record_id'];
act($wes, '/counts/lines/save.php', ['count' => $c2, 'variant' => $w['king'], 'counted_qty' => '50']);
$n = (int) one('SELECT count(*) FROM inventory_transactions');
[$c, $b] = act($wes, '/counts/cancel.php', ['count' => $c2]);
ok($c === 200 && one('SELECT status FROM inventory_counts WHERE id = :id', ['id' => $c2]) === 'cancelled' && (int) one('SELECT count(*) FROM inventory_transactions') === $n && on_hand($w['king'], $w['sr']) === 3, 'cancelling an open count posts nothing');
[$c, $b] = act($wes, '/counts/cancel.php', ['count' => $cid]);
ok($c === 422 && str_contains(msg($b), 'is posted'), 'a posted count does not cancel');
$reg = json_decode((string) file_get_contents(dirname(__DIR__, 3) . '/mcp/action_registry.json'), true)['actions'];
ok($reg['count_post']['approval'] === 'deletion' && $reg['stock_adjust']['approval'] === 'deletion', 'the registry: count_post and stock_adjust pause an agent (deletion)');
ok(page(as_member(41), '/counts/')['code'] === 403 && page(as_member(41), '/receipts/')['code'] === 403, 'Sam (no stock.count / stock.receive) cannot open counts or receipts');
finish();
