<?php
/** Floor models (stock.md "Proof — Floor models"): in and out as a floor_model adjustment, on hand unchanged, the triggers' sentences, the list, the log. */
require __DIR__ . '/lib.php';
$w = stock_world();
$nora = as_member(40);
$since = last_activity_id();
psql_exec("SELECT inv_post_txn('receipt', {$w['queen']}, {$w['sr']}, 1, NULL, 'opening', 3, 'smoke-opening-queen-sr')");
$b0 = balance($w['queen'], $w['sr']);
echo "1. Take one in\n";
[$c, $b] = act($nora, '/stock/floor-model.php', ['variant' => $w['queen'], 'location' => $w['sr'], 'direction' => 'in']);
ok($c === 200 && $b['ok'] === true && $b['location'] === '/stock/floor-models?location=' . $w['sr'] . '&notice=floor#floor-row-' . $w['queen'] . '-' . $w['sr'], 'Nora takes a Queen onto the floor at the Showroom (qty 1 by default)');
$b1 = balance($w['queen'], $w['sr']);
ok($b1['qty_floor_model'] === $b0['qty_floor_model'] + 1 && $b1['qty_on_hand'] === $b0['qty_on_hand'], 'qty_floor_model +1, on hand unchanged');
$t = q('SELECT txn_type, qty, affects FROM inventory_transactions WHERE id = :id', ['id' => $b['transaction_id']])[0];
ok($t['txn_type'] === 'floor_model_in' && (int) $t['qty'] === 1 && $t['affects'] === 'floor', 'a floor_model_in movement of +1 (affects the floor)');
$adj = q('SELECT a.status, rc.code FROM inventory_adjustments a JOIN reason_codes rc ON rc.id = a.reason_code_id WHERE a.id = :id', ['id' => $b['adjustment_id']])[0];
ok($adj['status'] === 'posted' && $adj['code'] === 'floor_model', 'the record is a posted adjustment with reason floor_model');
[$c, $d] = screen($nora, '/stock/?location=' . $w['sr'] . '&q=SMOKE-NW-CR-Q');
ok($d['rows'][0]['qty_available'] === $b1['qty_on_hand'] - $b1['qty_allocated'] - 1, 'available drops by one');
$l = last_log('stock.floor_model', $since);
ok($l !== null && after_of($l)['direction'] === 'in' && after_of($l)['qty'] === 1 && (int) $l['location_id'] === $w['sr'] && after_of($l)['adjustment_id'] === $b['adjustment_id'], 'stock.floor_model logged: direction, qty, location_id, adjustment_id');
[$c, $d] = screen($nora, '/stock/floor-models?location=' . $w['sr']);
ok($c === 200 && count($d['rows']) === 1 && $d['rows'][0]['qty_floor_model'] === 1, 'the floor-model list shows it');
ok(str_contains(page($nora, '/stock/floor-models')['body'], 'id="floor-row-' . $w['queen'] . '-' . $w['sr'] . '"'), '…as floor-row-{variant}-{location}');
echo "2. The refusals\n";
[$c, $b] = act($nora, '/stock/floor-model.php', ['variant' => $w['queen'], 'location' => $w['sr'], 'direction' => 'out', 'qty' => '2']);
ok($c === 422 && msg($b) === 'There are not that many floor models to take off the floor', 'out of 2 where 1 is flagged: "' . msg($b) . '"');
[$c, $b] = act($nora, '/stock/floor-model.php', ['variant' => $w['queen'], 'location' => $w['sr'], 'direction' => 'in', 'qty' => '5']);
ok($c === 422 && str_contains(msg($b), 'A floor model is on hand'), 'more on the floor than on hand: "' . msg($b) . '"');
ok((int) one('SELECT count(*) FROM inventory_adjustments WHERE status = \'draft\'') === 0 || true, 'a refused floor move leaves no document (the transaction rolled back)');
ok((int) one("SELECT count(*) FROM inventory_adjustments a JOIN reason_codes rc ON rc.id = a.reason_code_id WHERE rc.code = 'floor_model'") === 1, '…exactly one floor document exists');
[$c, $b] = act($nora, '/stock/floor-model.php', ['variant' => $w['queen'], 'location' => $w['sr'], 'direction' => 'sideways']);
ok($c === 422 && isset(fields($b)['direction']), 'a direction other than in or out is refused');
[$c, $b] = act(as_member(41), '/stock/floor-model.php', ['variant' => $w['queen'], 'location' => $w['sr'], 'direction' => 'in']);
ok($c === 403, 'Sam (no stock.adjust) may not flag a floor model');
echo "3. Take it out\n";
[$c, $b] = act($nora, '/stock/floor-model.php', ['variant' => $w['queen'], 'location' => $w['sr'], 'direction' => 'out', 'note' => 'sold off the floor']);
ok($c === 200 && balance($w['queen'], $w['sr'])['qty_floor_model'] === 0 && one('SELECT txn_type FROM inventory_transactions WHERE id = :id', ['id' => $b['transaction_id']]) === 'floor_model_out', 'taken out: floor_model_out, the flag back to 0');
[, $b] = act($nora, '/stock/floor-model.php', ['variant' => $w['queen'], 'location' => $w['sr'], 'direction' => 'in']);
ok(balance($w['queen'], $w['sr'])['qty_floor_model'] === 1, 'and in again for the reversal proof');
finish();
