<?php
/** JSON mode (stock.md "Proof — JSON mode"): every handler under a signed action token answers {ok, did, record_id, location, refresh}; lines JSON by barcode; quantities; _partial; 422 fields; the expert as source agent. */
require __DIR__ . '/lib.php';
$w = stock_world();
$H = ['X-Action-Token: ' . person_token(42)];
$shape = static fn (int $c, array $b): bool => $c === 200 && ($b['ok'] ?? false) === true && isset($b['did'], $b['record_id'], $b['location']) && ($b['refresh'] ?? '') === 'stockChanged';
echo "1. Wes's action token\n";
[$c, $b] = act_token('/receipts/save.php', ['location' => $w['wh'], 'delivery_note_ref' => 'DN-TOKEN', 'notes' => 'by token', 'lines' => json_encode([['barcode' => '850123450042', 'qty' => 2, 'unit_cost' => '181.00'], ['variant' => 'SMOKE-NW-CR-F', 'qty' => 1, 'putaway_location' => $w['sr']]])], $H);
ok($shape($c, $b), 'receipt_draft: {ok, did, record_id, location, refresh}');
$rid = (int) $b['record_id'];
$ls = q('SELECT variant_id, qty, unit_cost, putaway_location_id FROM goods_receipt_lines WHERE goods_receipt_id = :r ORDER BY line_no', ['r' => $rid]);
ok(count($ls) === 2 && (int) $ls[0]['variant_id'] === $w['king'] && $ls[0]['unit_cost'] === '181.00' && (int) $ls[1]['putaway_location_id'] === $w['sr'], 'the lines JSON lands whole (one by barcode, one by SKU with a put-away)');
[$c, $b] = act_token('/receipts/save.php', ['location' => $w['wh'], 'lines' => json_encode([['barcode' => '000000000000', 'qty' => 1], ['variant' => 'SMOKE-NW-CR-Q', 'qty' => 0]])], $H);
ok($c === 422 && $b['error']['code'] === 'invalid' && isset($b['error']['fields']['lines.0.barcode'], $b['error']['fields']['lines.1.qty']) && str_starts_with($b['error']['fields']['lines.0.barcode'], 'Line 1: '), '422 {error: {code: invalid, fields}} names each bad line');
ok((int) one('SELECT count(*) FROM goods_receipts WHERE id > :r', ['r' => $rid]) === 0, '…and nothing was drafted');
[$c, $b] = act_token('/receipts/save.php', ['receipt' => $rid, 'received_on' => date('Y-m-d', strtotime('-1 day')), '_partial' => '1'], $H);
$r = q('SELECT received_on, delivery_note_ref, notes, location_id FROM goods_receipts WHERE id = :id', ['id' => $rid])[0];
ok($c === 200 && $r['received_on'] === date('Y-m-d', strtotime('-1 day')) && $r['delivery_note_ref'] === 'DN-TOKEN' && $r['notes'] === 'by token' && (int) $r['location_id'] === $w['wh'], '_partial on a receipt header changes the date and keeps the rest');
[$c, $b] = act_token('/receipts/lines/save.php', ['receipt' => $rid, 'variant' => 'SMOKE-NW-CR-T', 'qty' => '1'], $H);
ok($shape($c, $b) && $b['line_id'] === $b['record_id'], 'receipt_line_add by SKU (an agent may pass a SKU as `variant`)');
[$c, $b] = act_token('/receipts/lines/remove.php', ['line' => $b['record_id']], $H);
ok($shape($c, $b), 'receipt_line_remove');
[$c, $b] = act_token('/receipts/post.php', ['receipt' => $rid], $H);
ok($shape($c, $b) && $b['units'] === 3, 'receipt_post');
[$c, $b] = act_token('/adjustments/save.php', ['location' => $w['wh'], 'reason' => 'found', 'lines' => json_encode([['variant' => 'SMOKE-NW-CR-K', 'qty_delta' => 1]])], $H);
ok($shape($c, $b), 'adjustment_draft with lines');
$aid = (int) $b['record_id'];
[$c, $b] = act_token('/adjustments/lines/save.php', ['adjustment' => $aid, 'variant' => 'SMOKE-NW-CR-F', 'qty_delta' => '1'], $H);
ok($shape($c, $b), 'adjustment_line_add');
[$c, $b] = act_token('/adjustments/lines/remove.php', ['line' => $b['record_id']], $H);
ok($shape($c, $b), 'adjustment_line_remove');
[$c, $b] = act_token('/adjustments/post.php', ['adjustment' => $aid], $H);
ok($shape($c, $b) && $b['units_delta'] === 1, 'stock_adjust (a person\'s token posts; an agent\'s pauses on the MCP path — Phase 4)');
[, $b] = act_token('/adjustments/save.php', ['location' => $w['wh'], 'reason' => 'lost'], $H);
[$c, $b] = act_token('/adjustments/cancel.php', ['adjustment' => $b['record_id']], $H);
ok($shape($c, $b), 'adjustment_cancel');
[$c, $b] = act_token('/transfers/save.php', ['from_location' => $w['wh'], 'to_location' => $w['sr'], 'lines' => json_encode([['variant' => 'SMOKE-NW-CR-K', 'qty' => 2], ['variant' => 'SMOKE-NW-CR-F', 'qty' => 1]])], $H);
ok($shape($c, $b), 'transfer_draft with lines');
$tid = (int) $b['record_id'];
[$c, $b] = act_token('/transfers/lines/save.php', ['transfer' => $tid, 'barcode' => '850123450042'], $H);
ok($shape($c, $b) && $b['incremented'] === true, 'transfer_line_add by barcode increments the King line');
[$c, $b] = act_token('/transfers/send.php', ['transfer' => $tid], $H);
ok($shape($c, $b) && $b['units'] === 4, 'transfer_send (4 units)');
$kl = (int) one('SELECT id FROM inventory_transfer_lines WHERE transfer_id = :t AND line_no = 1', ['t' => $tid]);
[$c, $b] = act_token('/transfers/receive.php', ['transfer' => $tid, 'quantities' => json_encode([(string) $kl => 2])], $H);
ok($shape($c, $b) && $b['units_received'] === 3 && $b['left_in_transit'] === 1, 'transfer_receive with quantities: 3 of 4, 1 left in transit');
[, $b] = act_token('/transfers/save.php', ['from_location' => $w['wh'], 'to_location' => $w['sr']], $H);
[$c, $b] = act_token('/transfers/cancel.php', ['transfer' => $b['record_id']], $H);
ok($shape($c, $b), 'transfer_cancel');
[$c, $b] = act_token('/counts/start.php', ['location' => $w['ret']], $H);
ok($shape($c, $b), 'count_start');
$cid = (int) $b['record_id'];
[$c, $b] = act_token('/counts/lines/save.php', ['count' => $cid, 'variant' => 'SMOKE-NW-PIL-STD', 'counted_qty' => '1'], $H);
ok($shape($c, $b), 'count_line_set');
[$c, $b] = act_token('/counts/post.php', ['count' => $cid], $H);
ok($shape($c, $b), 'count_post');
[, $b] = act_token('/counts/start.php', ['location' => $w['ret']], $H);
[$c, $b] = act_token('/counts/cancel.php', ['count' => $b['record_id']], $H);
ok($shape($c, $b), 'count_cancel');
[$c, $b] = act_token('/stock/floor-model.php', ['variant' => 'SMOKE-NW-CR-K', 'location' => $w['sr'], 'direction' => 'in'], $H);
ok($shape($c, $b) && isset($b['adjustment_id'], $b['transaction_id']), 'floor_model_set');
[$c, $b] = act_token('/stock/reverse.php', ['transaction' => $b['transaction_id']], $H);
ok($shape($c, $b) && isset($b['reverses_id']), 'stock_reverse');
[$c, $b] = act_token('/locations/save.php', ['name' => 'SMOKE Token place'], ['X-Action-Token: ' . person_token(1)]);
ok($c === 200 && $b['ok'] === true && $b['refresh'] === 'locationChanged', 'location_create (the owner\'s token): refresh locationChanged');
[$c, $b] = act_token('/locations/archive.php', ['location' => $b['record_id'], 'active' => 'no'], ['X-Action-Token: ' . person_token(1)]);
ok($c === 200 && $b['ok'] === true, 'location_archive');
[$c, $b] = act_token('/locations/save.php', ['name' => 'SMOKE Wes place'], $H);
ok($c === 403 && $b['error']['code'] === 'forbidden', 'Wes\'s token may not make a location: 403 forbidden');
echo "2. The expert under a run token\n";
$rt = run_token(45, 81);
kernel_state(function ($s) { $s['facts']['81'] = ['valid' => true, 'is_agent' => true, 'member_id' => 45, 'run_id' => 81, 'request_id' => 'req-run-81', 'trigger' => 'chat', 'endpoints' => [['name' => 'Records MCP']]]; return $s; });
pdo()->exec("UPDATE members SET roles = '{warehouse,user}' WHERE id = 45");
[$c, $b] = act_token('/transfers/save.php', ['from_location' => $w['wh'], 'to_location' => $w['sr'], 'lines' => json_encode([['variant' => 'SMOKE-NW-CR-K', 'qty' => 1]])], as_agent($rt));
ok($c === 200 && $b['ok'] === true, 'the expert drafts a transfer');
$row = q("SELECT source, agent_run_id, request_id, actor_member_id, location_id FROM activity_log WHERE action = 'stock.transfer_draft' AND entity_id = :t", ['t' => $b['record_id']])[0];
ok($row['source'] === 'agent' && (int) $row['agent_run_id'] === 81 && $row['request_id'] === 'req-run-81' && (int) $row['actor_member_id'] === 45 && (int) $row['location_id'] === $w['wh'], 'logged as source agent, run 81, actor 45, location_id the origin');
ok((int) one('SELECT created_by FROM inventory_transfers WHERE id = :t', ['t' => $b['record_id']]) === 45, 'the draft is the expert\'s (created_by 45)');
pdo()->exec("UPDATE members SET roles = '{user}' WHERE id = 45");
[$c, $b] = act_token('/transfers/save.php', ['from_location' => $w['wh'], 'to_location' => $w['sr']], as_agent($rt));
ok($c === 403, 'with user alone the expert may not move stock');
kernel_state(function ($s) { unset($s['facts']); return $s; });
echo "3. Screens as JSON\n";
$wes = as_member(42);
foreach (['/stock/', '/stock/movements', '/stock/floor-models', '/locations/', '/locations/' . $w['wh'], '/receipts/', '/receipts/new', '/receipts/' . $rid, '/receipts/' . $rid . '/edit', '/adjustments/', '/adjustments/new', '/adjustments/' . $aid,
          '/transfers/', '/transfers/new', '/transfers/' . $tid, '/counts/', '/counts/new', '/counts/' . $cid] as $p) {
    [$c, $d] = screen($wes, $p);
    if ($c !== 200 && !($p === '/receipts/' . $rid . '/edit' && $c === 422)) { ok(false, "$p answers JSON ($c)"); }
}
ok(screen($wes, '/receipts/' . $rid . '/edit')[0] === 422, 'a posted receipt\'s edit screen refuses in words');
ok(screen(as_member(1), '/locations/new')[0] === 200 && isset(screen(as_member(1), '/locations/new')[1]['kinds']), 'the location form answers its kinds');
ok(true, 'every stock screen answers JSON (18 screens)');
finish();
