<?php
/** Levels and movements (stock.md "Proof — Levels and movements"): the table agrees with the ledger's own answer; the filters; the CSV; the movements with their documents; the type filter; the 30-day window. */
require __DIR__ . '/lib.php';
$w = stock_world();
$vera = as_member(43);
$owner = as_member(1);
$since = last_activity_id();
echo "1. The levels\n";
[$c, $d] = screen($vera, '/stock/');
ok($c === 200 && $d['totals']['rows'] === count($d['rows']) && count($d['rows']) > 5, 'Vera reads the levels (' . count($d['rows']) . ' rows)');
$agree = true;
foreach ($d['rows'] as $r) {
    $own = psql_exec("SELECT qty_on_hand || ',' || qty_allocated || ',' || qty_floor_model || ',' || qty_available FROM inv_own_stock({$r['variant_id']}) WHERE location_id = {$r['location_id']}");
    if ($own !== $r['qty_on_hand'] . ',' . $r['qty_allocated'] . ',' . $r['qty_floor_model'] . ',' . $r['qty_available']) { $agree = false; echo "    $own vs {$r['sku']} @ {$r['location_name']}\n"; }
}
ok($agree, 'every row agrees with inv_own_stock() (on hand, allocated, floor, available)');
$sum = (int) one('SELECT sum(qty_on_hand) FROM inventory_balances');
ok($d['totals']['on_hand'] === $sum, "the totals agree with the balances (on hand $sum)");
ok(!in_array(0, array_map(static fn ($r) => abs($r['qty_on_hand']) + $r['qty_allocated'] + $r['qty_floor_model'], $d['rows']), true), 'only nonzero rows');
[$c, $d] = screen($vera, '/stock/?location=' . $w['wh']);
ok(count(array_unique(array_column($d['rows'], 'location_id'))) === 1 && $d['rows'][0]['location_id'] === $w['wh'], 'filtered by location');
[$c, $d] = screen($vera, '/stock/?brand=' . $w['brand_zinus']);
ok($d['rows'] === [], 'filtered by a brand with nothing on hand: none');
[$c, $d] = screen($vera, '/stock/?brand=' . $w['brand_cloudrest']);
ok(count($d['rows']) > 0 && !in_array('SMOKE-NW-PIL-STD', array_column($d['rows'], 'sku'), true), 'filtered by brand: the pillow (no brand) is out');
[$c, $d] = screen($vera, '/stock/?q=SMOKE-NW-CR-K');
ok(array_unique(array_column($d['rows'], 'sku')) === ['SMOKE-NW-CR-K'], 'q by SKU');
[$c, $d] = screen($vera, '/stock/?q=850123450042');
ok(array_unique(array_column($d['rows'], 'sku')) === ['SMOKE-NW-CR-K'], 'q by a barcode as scanned');
[$c, $d] = screen($vera, '/stock/?type=pillow');
ok(array_unique(array_column($d['rows'], 'sku')) === ['SMOKE-NW-PIL-STD'], 'filtered by product type');
[$c, $d] = screen($vera, '/stock/?below_reorder=1');
ok($d['rows'] === [], 'below reorder: none while no point is set (the default 0)');
psql_exec("UPDATE product_variants SET reorder_point = 50 WHERE id = {$w['queen']}");
[$c, $d] = screen($vera, '/stock/?below_reorder=1');
ok(count($d['rows']) > 0 && array_unique(array_column($d['rows'], 'sku')) === ['SMOKE-NW-CR-Q'] && $d['rows'][0]['below_reorder'] === true, 'a reorder point of 50 on the Queen: the Queen is below reorder');
ok(str_contains(page($vera, '/stock/')['body'], 'id="level-row-' . $w['queen'] . '-' . $w['wh'] . '-reorder"'), 'the levels table marks it "below reorder"');
psql_exec("UPDATE product_variants SET reorder_point = NULL WHERE id = {$w['queen']}");
[$c, $d] = screen($vera, '/stock/?variant=' . $w['king']);
ok(array_unique(array_column($d['rows'], 'sku')) === ['SMOKE-NW-CR-K'] && str_contains(page($vera, '/stock/?variant=' . $w['king'])['body'], 'id="levels-table-totals"'), 'filtered to one variant, with a totals row');
echo "2. The CSV\n";
$r = req('GET', '/stock/?location=' . $w['wh'] . '&format=csv', ['jar' => $vera]);
$lines = array_values(array_filter(explode("\n", trim($r['body']))));
[, $d] = screen($vera, '/stock/?location=' . $w['wh']);
ok($r['code'] === 200 && preg_match('#^Content-Type: text/csv#mi', $r['headers']) === 1, 'format=csv answers text/csv');
ok($lines[0] === 'sku,product,size,location,on_hand,allocated,floor_model,available,below_reorder' && count($lines) - 1 === count($d['rows']), 'the same rows as the screen (' . (count($lines) - 1) . ')');
$l = last_log('screen.view', $since);
$csvLog = q("SELECT after FROM activity_log WHERE action = 'screen.view' AND screen = 'stock-levels' AND id > :s AND after->>'format' = 'csv'", ['s' => $since]);
ok(count($csvLog) === 1 && (int) json_decode($csvLog[0]['after'], true)['location_id'] === $w['wh'], 'logged as screen.view with after.format = csv');
echo "3. The movements\n";
[$c, $d] = screen($vera, '/stock/movements');
$all = (int) one('SELECT count(*) FROM inventory_transactions');
ok($c === 200 && count($d['rows']) === $all, "every posting is on the screen ($all)");
$kinds = array_unique(array_column($d['rows'], 'reference_kind'));
sort($kinds);
ok($kinds === ['adjustment', 'count', 'goods_receipt', 'opening', 'reversal', 'transfer'], 'receipts, adjustments, transfers, counts, reversals and openings');
$gr = array_values(array_filter($d['rows'], static fn ($m) => $m['reference_kind'] === 'goods_receipt'))[0];
ok(preg_match('#^/receipts/\d+$#', (string) $gr['document_url']) === 1 && str_starts_with((string) $gr['document_number'], 'GR-'), 'a receipt movement links its document (' . $gr['document_number'] . ')');
$adj = array_values(array_filter($d['rows'], static fn ($m) => $m['reason_code'] === 'damaged' && $m['reference_kind'] === 'adjustment'))[0] ?? null;
ok($adj !== null && str_starts_with((string) $adj['document_number'], 'ADJ-'), 'an adjustment movement shows its reason (damaged)');
$tr = array_values(array_filter($d['rows'], static fn ($m) => $m['txn_type'] === 'transfer_in'))[0];
ok($tr['counterparty_name'] === 'SMOKE Warehouse', 'a transfer_in names the location it came from');
[$c, $d] = screen($vera, '/stock/movements?type=count_correction');
ok(count($d['rows']) === 3 && array_unique(array_column($d['rows'], 'txn_type')) === ['count_correction'], 'the type filter (3 count corrections)');
[$c, $d] = screen($vera, '/stock/movements?location=' . $w['ret']);
ok($d['rows'] === [], 'filtered by location: nothing moved at Returns');
psql_exec("SELECT inv_post_txn('receipt', {$w['pillow_v']}, {$w['ret']}, 1, NULL, 'opening', 9, 'smoke-old-opening', 'none', NULL, NULL, NULL, 1, NULL, 'forty days ago', now() - interval '40 days')");
[$c, $d] = screen($vera, '/stock/movements?location=' . $w['ret']);
ok($d['rows'] === [], 'a movement 40 days old is outside the 30-day default');
[$c, $d] = screen($vera, '/stock/movements?location=' . $w['ret'] . '&from=' . date('Y-m-d', strtotime('-60 days')));
ok(count($d['rows']) === 1, '…and in when From reaches back');
$html = page($vera, '/stock/movements')['body'];
ok(str_contains($html, 'id="movements-table"') && str_contains($html, 'The last 30 days'), 'the screen says it shows the last 30 days');
finish();
