<?php
/** Locations (stock.md "Proof — Locations"): three made; a duplicate refused; Nora refused in words; archive refused while units are held, an empty one archived and restored; the cards; the log. */
require __DIR__ . '/lib.php';
$w = stock_world();
$owner = as_member(1);
$nora = as_member(40);
echo "1. Make and change\n";
$since = last_activity_id();
[$c, $b] = act($owner, '/locations/save.php', ['name' => 'smoke warehouse', 'kind' => 'store']);
ok($c === 422 && msg($b) === 'That name is already taken.', 'a duplicate name (case aside) is refused: "That name is already taken."');
[$c, $b] = act($owner, '/locations/save.php', ['name' => 'SMOKE Offsite', 'kind' => 'shed']);
ok($c === 422 && isset(fields($b)['kind']), 'an unknown kind is refused by field');
[$c, $b] = act($owner, '/locations/save.php', ['name' => '']);
ok($c === 422 && isset(fields($b)['name']), 'a location needs a name');
[$c, $b] = act($nora, '/locations/save.php', ['name' => 'SMOKE Nora place']);
ok($c === 403 && str_contains(msg($b), 'settings'), 'Nora (no settings.manage) is refused in words: ' . msg($b));
$dept = (int) one('SELECT id FROM departments WHERE archived_at IS NULL ORDER BY id LIMIT 1');
[$c, $b] = act($owner, '/locations/save.php', ['name' => 'SMOKE Offsite', 'kind' => 'offsite', 'department' => $dept, 'address' => "9 Far Lane\nOuttown", 'is_sellable' => 'no']);
ok($c === 200 && $b['ok'] === true && $b['location'] === '/locations/' . $b['record_id'] . '?notice=created' && $b['refresh'] === 'locationChanged', 'the owner makes SMOKE Offsite: {ok, record_id, location, refresh locationChanged}');
$off = (int) $b['record_id'];
$row = last_log('location.create', $since);
ok($row !== null && (int) $row['location_id'] === $off && after_of($row)['kind'] === 'offsite' && after_of($row)['department_id'] === $dept, 'location.create logged with location_id and after (kind, department)');
ok(count(activity('location.create')) >= 4, 'the world\'s three and this one each logged location.create');
[$c, $b] = act($owner, '/locations/save.php', ['location' => $off, 'allow_negative' => 'yes', '_partial' => '1']);
ok($c === 200 && one('SELECT allow_negative FROM locations WHERE id = :id', ['id' => $off]) === true && one('SELECT name FROM locations WHERE id = :id', ['id' => $off]) === 'SMOKE Offsite' && (int) one('SELECT department_id FROM locations WHERE id = :id', ['id' => $off]) === $dept, '_partial changes one field and keeps the rest');
$row = last_log('location.update', $since);
ok($row !== null && after_of($row) == ['allow_negative' => true, 'name' => 'SMOKE Offsite'] && json_decode($row['before'], true) == ['allow_negative' => false], 'location.update logs only what changed (inv_diff)');
echo "2. Archive\n";
[$c, $b] = act($owner, '/locations/archive.php', ['location' => $off, 'active' => 'no']);
ok($c === 200 && one('SELECT active FROM locations WHERE id = :id', ['id' => $off]) === false, 'an empty location archives');
ok(after_of(last_log('location.archive', $since))['active'] === false, 'location.archive logged with after.active');
[$c, $b] = act($owner, '/locations/archive.php', ['location' => $off, 'active' => 'no']);
ok($c === 422 && str_contains(msg($b), 'already archived'), 'archiving it again: "already archived"');
[$c, $d] = screen($owner, '/locations/');
ok($c === 200 && !in_array($off, array_column($d['locations'], 'location_id'), true), 'an archived location leaves the cards');
[$c, $d] = screen($owner, '/locations/?archived=1');
ok(in_array($off, array_column($d['locations'], 'location_id'), true), '…and shows with "archived too"');
[$c, $b] = act($owner, '/locations/archive.php', ['location' => $off, 'active' => 'yes']);
ok($c === 200 && one('SELECT active FROM locations WHERE id = :id', ['id' => $off]) === true, 'restored');
// units at the Warehouse: an opening movement as postgres (receipts are proven in receipts.php)
psql_exec("SELECT inv_post_txn('receipt', {$w['pillow_v']}, $off, 3, NULL, 'opening', 1, 'smoke-opening-loc')");
[$c, $b] = act($owner, '/locations/archive.php', ['location' => $off, 'active' => 'no']);
ok($c === 422 && msg($b) === 'SMOKE Offsite still holds 3 units — move or adjust them first', 'archive refused while units are held, in words: ' . msg($b));
[$c, $b] = act($owner, '/locations/save.php', ['location' => $off, 'active' => 'no', '_partial' => '1']);
ok($c === 422 && str_contains(implode(' ', fields($b)), 'still holds 3 units'), 'the edit form\'s Active box is held to the same rule');
echo "3. The cards and the view\n";
[$c, $d] = screen(as_member(43), '/locations/');
$card = array_values(array_filter($d['locations'], static fn ($l) => $l['location_id'] === $off))[0] ?? null;
ok($c === 200 && $card !== null && $card['units_on_hand'] === 3 && $card['kind'] === 'offsite' && $card['is_sellable'] === false && $card['department_name'] !== null, 'Vera reads the cards: units on hand 3, kind, sellable no, the department');
$html = page(as_member(43), '/locations/')['body'];
ok(str_contains($html, 'id="location-card-' . $off . '"') && str_contains($html, 'allows negative') && !str_contains($html, 'id="location-list-new-btn"'), 'the card says "allows negative"; Vera has no New location');
[$c, $d] = screen($owner, '/locations/' . $off);
ok($c === 200 && $d['holds'] === 3 && count($d['levels']) === 1 && $d['levels'][0]['sku'] === 'SMOKE-NW-PIL-STD', 'the location view answers its levels');
ok(page($owner, '/locations/' . $off . '?tab=trail')['code'] === 200 && page($owner, '/locations/' . $off . '?tab=movements')['code'] === 200 && page($owner, '/locations/' . $off . '/edit')['code'] === 200, 'the trail and movements tabs and the edit form open');
ok(page($nora, '/locations/new')['code'] === 403, 'Nora cannot open the new-location form');
finish();
