<?php
/** Receipts (stock.md "Proof — Receipts"): scanning, the scan rule, refusals in words, posting into put-away locations, the cost following, the PO received, the log. */
require __DIR__ . '/lib.php';
$w = stock_world();
$wes = as_member(42);
$sam = as_member(41);
$since = last_activity_id();
echo "1. A free receipt, scanned\n";
[$c, $b] = act($wes, '/receipts/save.php', ['location' => $w['wh'], 'delivery_note_ref' => 'DN-77']);
ok($c === 200 && $b['ok'] === true && $b['location'] === '/receipts/' . $b['record_id'] . '?notice=created', 'Wes drafts a free receipt at the Warehouse: record_id and location');
$rid = (int) $b['record_id'];
$num = (string) one('SELECT number FROM goods_receipts WHERE id = :id', ['id' => $rid]);
ok(preg_match('/^GR-\d{5}$/', $num) === 1 && one('SELECT status FROM goods_receipts WHERE id = :id', ['id' => $rid]) === 'draft', "numbered at creation ($num), a draft");
$l = last_log('stock.receipt_draft', $since);
ok($l !== null && (int) $l['location_id'] === $w['wh'] && after_of($l)['number'] === $num, 'stock.receipt_draft logged with location_id and the number');
[$c, $b] = act($wes, '/receipts/lines/save.php', ['receipt' => $rid, 'barcode' => '00850123450035']);
ok($c === 200 && $b['incremented'] === false && (int) one('SELECT qty FROM goods_receipt_lines WHERE id = :id', ['id' => $b['record_id']]) === 1, 'the Queen\'s GTIN scanned: a line of 1');
$qline = (int) $b['record_id'];
[$c, $b] = act($wes, '/receipts/lines/save.php', ['receipt' => $rid, 'barcode' => '00850123450035']);
ok($c === 200 && $b['incremented'] === true && (int) $b['record_id'] === $qline && (int) one('SELECT qty FROM goods_receipt_lines WHERE id = :id', ['id' => $qline]) === 2, 'scanned again: the same line goes to 2');
ok((int) one('SELECT count(*) FROM goods_receipt_lines WHERE goods_receipt_id = :r', ['r' => $rid]) === 1, 'still one line');
ok(after_of(last_log('stock.receipt_line', $since))['incremented'] === true, 'stock.receipt_line logged incremented: true');
[$c, $b] = act($wes, '/receipts/lines/save.php', ['receipt' => $rid, 'barcode' => '850123450004']);
ok($c === 200 && (int) one('SELECT variant_id FROM goods_receipt_lines WHERE id = :id', ['id' => $b['record_id']]) === $w['twin'], 'a 12-digit UPC resolves (the Twin)');
$twinLine = (int) $b['record_id'];
[$c, $b] = act($wes, '/receipts/lines/save.php', ['receipt' => $rid, 'barcode' => 'smoke-nw-pil-std']);
ok($c === 200 && (int) one('SELECT variant_id FROM goods_receipt_lines WHERE id = :id', ['id' => $b['record_id']]) === $w['pillow_v'], 'a SKU typed into the scan field resolves (any case)');
$pilLine = (int) $b['record_id'];
[$c, $b] = act($wes, '/receipts/lines/save.php', ['receipt' => $rid, 'barcode' => '00812345000123']);
ok($c === 422 && fields($b)['barcode'] === 'No variant has the code 00812345000123.', 'an unknown code: "No variant has the code 00812345000123."');
[$c, $b] = act($wes, '/receipts/lines/save.php', ['receipt' => $rid, 'barcode' => 'SMOKE-SET-Q']);
ok($c === 422 && fields($b)['barcode'] === 'A bundle never holds stock — receive its components', 'a bundle\'s SKU: "A bundle never holds stock — receive its components"');
[$c, $b] = act($wes, '/receipts/lines/save.php', ['receipt' => $rid, 'variant' => $w['set_q']]);
ok($c === 422 && str_contains(fields($b)['variant'] ?? '', 'A bundle never holds stock'), '…and from the picker too');
[$c, $b] = act($wes, '/receipts/lines/remove.php', ['line' => $twinLine]);
ok($c === 200 && one('SELECT count(*) FROM goods_receipt_lines WHERE id = :id', ['id' => $twinLine]) === 0 && last_log('stock.receipt_line_remove', $since) !== null, 'receipt_line_remove takes the Twin off, logged');
act($wes, '/receipts/lines/remove.php', ['line' => $pilLine]);
echo "2. A typed line with cost and put-away\n";
[$c, $b] = act($wes, '/receipts/lines/save.php', ['receipt' => $rid, 'variant' => $w['king'], 'qty' => '4', 'unit_cost' => '189.00', 'putaway_location' => $w['sr'], 'discrepancy_kind' => 'over', 'discrepancy_note' => 'one carton extra']);
ok($c === 200 && $b['incremented'] === false, 'Wes types a line of 4 King at 189.00, put away at the Showroom');
$kline = (int) $b['record_id'];
$kl = q('SELECT qty, unit_cost, putaway_location_id, discrepancy_kind FROM goods_receipt_lines WHERE id = :id', ['id' => $kline])[0];
ok((int) $kl['qty'] === 4 && $kl['unit_cost'] === '189.00' && (int) $kl['putaway_location_id'] === $w['sr'] && $kl['discrepancy_kind'] === 'over', 'the line carries qty, cost, put-away, discrepancy');
[$c, $b] = act($wes, '/receipts/lines/save.php', ['receipt' => $rid, 'variant' => $w['king'], 'qty' => '0']);
ok($c === 422 && isset(fields($b)['qty']), 'a quantity of 0 is refused by field');
[$c, $b] = act($wes, '/receipts/lines/save.php', ['receipt' => $rid, 'variant' => $w['king'], 'putaway_location' => 999999]);
ok($c === 422 && isset(fields($b)['putaway_location']), 'a put-away location that is not here is refused');
[$c, $b] = act($wes, '/receipts/lines/save.php', ['receipt' => $rid, 'line' => $kline, 'qty' => '4', 'unit_cost' => '189.00']);
ok($c === 200 && (int) $b['record_id'] === $kline && (int) one('SELECT putaway_location_id FROM goods_receipt_lines WHERE id = :id', ['id' => $kline]) === $w['sr'], 'changing a line by `line` keeps what was left out (the put-away)');
[$c, $d] = screen($wes, '/receipts/' . $rid);
ok($c === 200 && count($d['lines']) === 2 && $d['amount'] !== null && $d['cost_withheld'] === false, 'Wes reads the draft with cost (Warehouse sees receipt cost)');
echo "3. Posting\n";
$hist0 = (int) one("SELECT count(*) FROM price_history WHERE variant_id = :v AND kind = 'cost'", ['v' => $w['king']]);
[$c, $b] = act($wes, '/receipts/post.php', ['receipt' => $rid]);
ok($c === 200 && $b['ok'] === true && $b['units'] === 6 && $b['location'] === '/receipts/' . $rid . '?notice=posted', 'posted: 6 units; JSON {ok, units, location}');
$t = txns('goods_receipt', $rid);
ok(count($t) === 2 && $t[0]['txn_type'] === 'receipt' && $t[0]['counterparty_kind'] === 'none', 'two receipt movements; a free receipt has no counterparty');
ok(on_hand($w['queen'], $w['wh']) === 2 && on_hand($w['king'], $w['sr']) === 4 && on_hand($w['king'], $w['wh']) === 0, 'the balances: Queen 2 at the Warehouse, King 4 at the Showroom (its put-away)');
ok(one('SELECT cost_price FROM product_variants WHERE id = :v', ['v' => $w['king']]) === '189.00', 'the King\'s cost follows the receipt (cost_source last_receipt): 189.00');
$h = q("SELECT source_kind, reason FROM price_history WHERE variant_id = :v AND kind = 'cost' ORDER BY id DESC LIMIT 1", ['v' => $w['king']])[0];
ok((int) one("SELECT count(*) FROM price_history WHERE variant_id = :v AND kind = 'cost'", ['v' => $w['king']]) === $hist0 + 1 && $h['source_kind'] === 'last_receipt' && $h['reason'] === 'receipt ' . $num, 'price history: source last_receipt, reason "receipt ' . $num . '"');
$l = last_log('stock.receive', $since);
$a = after_of($l);
ok($l !== null && (int) $l['location_id'] === $w['wh'] && $a['units'] === 6 && $a['lines'] === 2 && $a['amount'] === '756.00' && $a['currency'] === 'USD' && $a['discrepancies'] === 1, 'stock.receive logged: location_id, units 6, lines 2, amount 756.00 (4 × 189), USD, 1 discrepancy');
[$c, $b] = act($wes, '/receipts/post.php', ['receipt' => $rid]);
ok($c === 422 && str_contains(msg($b), "$num is posted — only a draft posts"), 'a second post: "' . msg($b) . '"');
[$c, $b] = act($wes, '/receipts/cancel.php', ['receipt' => $rid]);
ok($c === 422 && msg($b) === "$num is posted — reverse its movements instead", 'cancel after posting: "' . msg($b) . '"');
[$c, $b] = act($wes, '/receipts/lines/save.php', ['receipt' => $rid, 'variant' => $w['queen']]);
ok($c === 422 && str_contains(msg($b), 'only a draft receipt changes'), 'a line on a posted receipt is refused by the handler');
$sql = psql_exec("SET ROLE inventory_rw; INSERT INTO goods_receipt_lines (goods_receipt_id, line_no, variant_id, qty) VALUES ($rid, 9, {$w['queen']}, 1)");
ok(str_contains($sql, 'change only while it is draft, it is posted'), '…and by the trigger in its own words when SQL tries');
[$c, $b] = act($wes, '/receipts/lines/remove.php', ['line' => $kline]);
ok($c === 422, 'a posted line cannot be removed');
echo "4. Drafts that do not post\n";
[, $b] = act($wes, '/receipts/save.php', ['location' => $w['wh']]);
$empty = (int) $b['record_id'];
[$c, $b] = act($wes, '/receipts/post.php', ['receipt' => $empty]);
ok($c === 422 && str_contains(msg($b), 'has no lines'), 'a draft with no lines: "' . msg($b) . '"');
[$c, $b] = act($wes, '/receipts/cancel.php', ['receipt' => $empty]);
ok($c === 200 && one('SELECT status FROM goods_receipts WHERE id = :id', ['id' => $empty]) === 'cancelled' && last_log('stock.receipt_cancel', $since) !== null, 'a draft cancels, logged');
[$c, $b] = act($wes, '/receipts/save.php', ['location' => $w['wh'], 'received_on' => date('Y-m-d', strtotime('+2 days'))]);
ok($c === 422 && isset(fields($b)['received_on']), 'a received date in the future is refused');
[$c, $b] = act($sam, '/receipts/save.php', ['location' => $w['wh']]);
ok($c === 403 && str_contains(msg($b), 'receive'), 'Sam (no stock.receive) is refused in words — so a unit cost from Sam never reaches a line: ' . msg($b));
echo "5. Against a purchase order\n";
[$c, $b] = act($wes, '/receipts/save.php', ['location' => $w['wh'], 'supplier' => $w['supplier'], 'purchase_order' => $w['po_other']]);
ok($c === 422 && str_contains(fields($b)['purchase_order'] ?? '', 'SMOKE Other Supplier'), 'a PO of another supplier is refused: ' . (fields($b)['purchase_order'] ?? ''));
[$c, $d] = screen($wes, '/receipts/new?purchase_order=' . $w['po']);
ok($c === 200 && count($d['po_open_lines']) === 2 && (int) $d['po_open_lines'][0]['qty_open'] === 10, 'the new-receipt screen offers the PO\'s two open lines');
[$c, $d] = screen($wes, '/receipts/po-options?supplier=' . $w['supplier']);
ok($c === 200 && array_column($d['purchase_orders'], 'purchase_order_id') === [$w['po']], 'po-options answers the supplier\'s open stock PO');
$plKing = (int) one('SELECT id FROM purchase_order_lines WHERE purchase_order_id = :p AND line_no = 1', ['p' => $w['po']]);
$plFull = (int) one('SELECT id FROM purchase_order_lines WHERE purchase_order_id = :p AND line_no = 2', ['p' => $w['po']]);
[$c, $b] = act($wes, '/receipts/save.php', ['location' => $w['wh'], 'purchase_order' => $w['po'], 'po_lines' => [$plKing, $plFull], 'po_qty' => [$plKing => '6', $plFull => '5']]);
ok($c === 200, 'Wes creates the receipt from the PO\'s open lines (King 6 of 10, Full 5)');
$prid = (int) $b['record_id'];
$pr = q('SELECT supplier_id, purchase_order_id FROM goods_receipts WHERE id = :id', ['id' => $prid])[0];
ok((int) $pr['supplier_id'] === $w['supplier'] && (int) $pr['purchase_order_id'] === $w['po'], 'the supplier is taken from the PO');
$pl = q('SELECT variant_id, qty, unit_cost, purchase_order_line_id FROM goods_receipt_lines WHERE goods_receipt_id = :r ORDER BY line_no', ['r' => $prid]);
ok(count($pl) === 2 && (int) $pl[0]['qty'] === 6 && $pl[0]['unit_cost'] === '180.00' && (int) $pl[0]['purchase_order_line_id'] === $plKing, 'the lines carry the PO line and its cost (180.00)');
[$c, $b] = act($wes, '/receipts/lines/save.php', ['receipt' => $prid, 'variant' => $w['queen'], 'purchase_order_line' => $plKing]);
ok($c === 422 && str_contains(fields($b)['purchase_order_line'] ?? '', 'another variant'), 'a PO line of another variant is refused');
[$c, $b] = act($wes, '/receipts/post.php', ['receipt' => $prid]);
ok($c === 200 && (int) one('SELECT qty_received FROM purchase_order_lines WHERE id = :id', ['id' => $plKing]) === 6 && one('SELECT status FROM purchase_order_lines WHERE id = :id', ['id' => $plFull]) === 'received', 'posted: the PO lines received 6 and 5 (the Full line received)');
ok(one('SELECT status FROM purchase_orders WHERE id = :id', ['id' => $w['po']]) === 'partial', 'the PO is partial (4 King still open)');
$t = txns('goods_receipt', $prid);
ok($t[0]['counterparty_kind'] === 'supplier' && (int) $t[0]['counterparty_id'] === $w['supplier'], 'the movements name the supplier as counterparty');
$l = last_log('stock.receive', $since);
ok((int) $l['purchase_order_id'] === $w['po'] && after_of($l)['purchase_order_id'] === $w['po'], 'stock.receive carries the purchase_order_id audit key');
ok(on_hand($w['king'], $w['wh']) === 6 && on_hand($w['full'], $w['wh']) === 5, 'the balances: King 6 and Full 5 at the Warehouse');
finish();
