<?php
/** Reversals (stock.md "Proof — Reverse"): the damaged movement reversed, once; a floor move reversed as the opposite floor move; the referee refuses SQL that edits the ledger or a balance. */
require __DIR__ . '/lib.php';
$w = stock_world();
$wes = as_member(42);
$since = last_activity_id();
$dmg = (int) one("SELECT t.id FROM inventory_transactions t JOIN reason_codes rc ON rc.id = t.reason_code_id WHERE t.reference_kind = 'adjustment' AND rc.code = 'damaged' ORDER BY t.id LIMIT 1");
$q0 = on_hand($w['queen'], $w['wh']);
echo "1. Reverse the damaged unit\n";
[$c, $b] = act($wes, '/stock/reverse.php', ['transaction' => $dmg, 'note' => 'it was fine']);
ok($c === 200 && $b['ok'] === true && $b['reverses_id'] === $dmg && str_contains($b['location'], '#movement-row-' . $b['record_id']), 'Wes reverses the damaged movement: lands on the new row');
$r = q('SELECT txn_type, qty, reverses_id, reference_kind, reference_id, note FROM inventory_transactions WHERE id = :id', ['id' => $b['record_id']])[0];
ok($r['txn_type'] === 'reversal' && (int) $r['qty'] === 1 && (int) $r['reverses_id'] === $dmg && $r['reference_kind'] === 'reversal' && $r['note'] === 'it was fine', 'a reversal +1 linked by reverses_id, with the note');
ok(on_hand($w['queen'], $w['wh']) === $q0 + 1, 'on hand back up by one (' . ($q0 + 1) . ')');
[$c, $b] = act($wes, '/stock/reverse.php', ['transaction' => $dmg]);
ok($c === 422 && msg($b) === 'That transaction is already reversed', 'reversing it again: "That transaction is already reversed"');
$l = last_log('stock.reverse', $since);
ok($l !== null && after_of($l)['reverses_id'] === $dmg && after_of($l)['txn_type'] === 'adjustment' && after_of($l)['reference_kind'] === 'adjustment' && (int) $l['location_id'] === $w['wh'], 'stock.reverse logged: reverses_id, txn_type, reference, location_id');
[$c, $d] = screen($wes, '/stock/movements?variant=' . $w['queen']);
$row = array_values(array_filter($d['rows'], static fn ($m) => $m['transaction_id'] === $dmg))[0] ?? null;
ok($row !== null && $row['reversed_by'] !== null, 'the movements screen marks the reversed row');
$html = page($wes, '/stock/movements?variant=' . $w['queen'])['body'];
ok(str_contains($html, 'id="movement-row-' . $dmg . '-reversed"') && !str_contains($html, 'id="movement-row-' . $dmg . '-reverse"'), 'the reversed row shows "reversed" and no Reverse button');
echo "2. A floor move reverses as the opposite floor move\n";
$fin = (int) one("SELECT id FROM inventory_transactions WHERE txn_type = 'floor_model_in' ORDER BY id DESC LIMIT 1");
$f0 = balance($w['queen'], $w['sr']);
[$c, $b] = act($wes, '/stock/reverse.php', ['transaction' => $fin]);
ok($c === 200 && one('SELECT txn_type FROM inventory_transactions WHERE id = :id', ['id' => $b['record_id']]) === 'floor_model_out', 'reversing a floor_model_in posts a floor_model_out');
$f1 = balance($w['queen'], $w['sr']);
ok($f1['qty_floor_model'] === $f0['qty_floor_model'] - 1 && $f1['qty_on_hand'] === $f0['qty_on_hand'], 'the flag drops, on hand unchanged');
echo "3. The referee\n";
$sql = psql_exec("SET ROLE inventory_rw; UPDATE inventory_transactions SET qty = 99 WHERE id = $dmg");
ok(str_contains($sql, 'permission denied for table inventory_transactions'), 'the application\'s role may not UPDATE a movement at all (INSERT and SELECT only)');
$sql = psql_exec("UPDATE inventory_transactions SET qty = 99 WHERE id = $dmg");
ok(str_contains($sql, 'A transaction is never changed or deleted — reverse it'), 'and even the owner\'s UPDATE meets the trigger: "A transaction is never changed or deleted — reverse it"');
$sql = psql_exec("DELETE FROM inventory_transactions WHERE id = $dmg");
ok(str_contains($sql, 'never changed or deleted'), 'a direct DELETE likewise');
$sql = psql_exec("SET ROLE inventory_rw; UPDATE inventory_balances SET qty_on_hand = 500 WHERE variant_id = {$w['queen']}");
ok(str_contains($sql, 'A balance is maintained only by transactions'), 'a direct UPDATE of a balance: "A balance is maintained only by transactions — post a receipt, an adjustment, a transfer, a count, or allocate"');
[$c, $b] = act($wes, '/stock/reverse.php', ['transaction' => 999999]);
ok($c === 404, 'a movement that is not here: 404');
[$c, $b] = act(as_member(43), '/stock/reverse.php', ['transaction' => $fin]);
ok($c === 403, 'Vera (no stock.adjust) may not reverse');
[$c, $d] = screen(as_member(43), '/stock/movements?variant=' . $w['queen']);
ok(!str_contains(page(as_member(43), '/stock/movements')['body'], '-reverse"'), 'Vera sees no Reverse button');
finish();
