<?php
/** Transfers (stock.md "Proof — Transfers"): a draft, from = to refused, send, a line refused after sending, a short receive, a full one, the refusals in the database's words, the log. */
require __DIR__ . '/lib.php';
$w = stock_world();
$wes = as_member(42);
$since = last_activity_id();
$kw0 = on_hand($w['king'], $w['wh']);
$ks0 = on_hand($w['king'], $w['sr']);
echo "1. Draft and send\n";
[$c, $b] = act($wes, '/transfers/save.php', ['from_location' => $w['wh'], 'to_location' => $w['wh']]);
ok($c === 422 && fields($b)['to_location'] === 'A transfer goes from one location to another — choose two different ones.', 'from = to is refused in words');
$sql = psql_exec("SET ROLE inventory_rw; INSERT INTO inventory_transfers (number, from_location_id, to_location_id) VALUES ('', {$w['wh']}, {$w['wh']})");
ok(str_contains($sql, 'inventory_transfers_check'), '…and by the CHECK when SQL tries');
[$c, $b] = act($wes, '/transfers/save.php', ['from_location' => $w['wh'], 'to_location' => $w['sr'], 'notes' => 'for the floor']);
ok($c === 200 && $b['ok'] === true, 'Wes drafts Warehouse → Showroom');
$tid = (int) $b['record_id'];
ok(preg_match('/^TR-\d{5}$/', (string) one('SELECT number FROM inventory_transfers WHERE id = :id', ['id' => $tid])) === 1, 'numbered TR-…');
[$c, $b] = act($wes, '/transfers/lines/save.php', ['transfer' => $tid, 'barcode' => '850123450042']);
ok($c === 200 && $b['incremented'] === false, 'the King scanned: a line of 1');
$tl = (int) $b['record_id'];
[$c, $b] = act($wes, '/transfers/lines/save.php', ['transfer' => $tid, 'barcode' => '850123450042']);
ok($c === 200 && $b['incremented'] === true && (int) one('SELECT qty FROM inventory_transfer_lines WHERE id = :id', ['id' => $tl]) === 2, 'scanned again: the line goes to 2 King');
[$c, $b] = act($wes, '/transfers/lines/save.php', ['transfer' => $tid, 'variant' => $w['set_q']]);
ok($c === 422 && str_contains(fields($b)['variant'] ?? '', 'A bundle never holds stock — move its components'), 'a bundle is refused: "A bundle never holds stock — move its components"');
[$c, $b] = act($wes, '/transfers/send.php', ['transfer' => $tid]);
ok($c === 200 && $b['units'] === 2, 'sent: 2 units');
$t = txns('transfer', $tid);
ok(count($t) === 1 && $t[0]['txn_type'] === 'transfer_out' && (int) $t[0]['qty'] === -2 && (int) $t[0]['location_id'] === $w['wh'] && $t[0]['counterparty_kind'] === 'location' && (int) $t[0]['counterparty_id'] === $w['sr'], 'transfer_out −2 at the Warehouse, counterparty the Showroom');
ok(on_hand($w['king'], $w['wh']) === $kw0 - 2 && on_hand($w['king'], $w['sr']) === $ks0, "the Warehouse holds " . ($kw0 - 2) . ' King; the Showroom unchanged (in transit on the document)');
ok(one('SELECT status FROM inventory_transfers WHERE id = :id', ['id' => $tid]) === 'in_transit', 'the transfer is in transit');
$l = last_log('stock.transfer_send', $since);
ok($l !== null && (int) $l['location_id'] === $w['wh'] && after_of($l)['units'] === 2 && after_of($l)['to_location_id'] === $w['sr'], 'stock.transfer_send logged at the origin');
[$c, $b] = act($wes, '/transfers/lines/save.php', ['transfer' => $tid, 'variant' => $w['queen']]);
ok($c === 422 && str_contains(msg($b), 'is in transit — only a draft transfer changes'), 'a line after sending is refused: "' . msg($b) . '"');
$sql = psql_exec("SET ROLE inventory_rw; UPDATE inventory_transfer_lines SET qty = 9 WHERE id = $tl");
ok(str_contains($sql, 'The lines of a transfer change only while it is a draft, it is in_transit'), '…and by the guard when SQL tries');
[$c, $b] = act($wes, '/transfers/send.php', ['transfer' => $tid]);
ok($c === 422 && str_contains(msg($b), 'only a draft is sent'), 'sending twice: "' . msg($b) . '"');
[$c, $b] = act($wes, '/transfers/cancel.php', ['transfer' => $tid]);
ok($c === 422 && str_contains(msg($b), 'is in transit'), 'an in-transit transfer does not cancel');
echo "2. A short receive\n";
[$c, $d] = screen($wes, '/transfers/' . $tid);
ok($c === 200 && $d['transfer']['status'] === 'in_transit' && count($d['movements']) === 1, 'the view answers in transit with the sending half');
[$c, $b] = act($wes, '/transfers/receive.php', ['transfer' => $tid, 'quantities' => json_encode([(string) $tl => 3])]);
ok($c === 422 && str_contains(msg($b), 'receives between 0 and 2'), 'receiving more than was sent: "' . msg($b) . '"');
[$c, $b] = act($wes, '/transfers/receive.php', ['transfer' => $tid, 'quantities' => json_encode(['999999' => 1])]);
ok($c === 422 && str_contains(implode(' ', fields($b)), 'is not on'), 'a line of another transfer is refused');
[$c, $b] = act($wes, '/transfers/receive.php', ['transfer' => $tid, 'quantities' => json_encode([(string) $tl => 1])]);
ok($c === 200 && $b['units_received'] === 1 && $b['left_in_transit'] === 1 && str_contains($b['did'], '1 left in transit'), 'received 1 of 2: "' . ($b['did'] ?? '') . '"');
$t = txns('transfer', $tid);
ok(count($t) === 2 && $t[1]['txn_type'] === 'transfer_in' && (int) $t[1]['qty'] === 1 && (int) $t[1]['location_id'] === $w['sr'] && $t[0]['group_id'] !== $t[1]['group_id'], 'transfer_in +1 at the Showroom');
ok((int) one('SELECT qty_received FROM inventory_transfer_lines WHERE id = :id', ['id' => $tl]) === 1 && on_hand($w['king'], $w['sr']) === $ks0 + 1, 'qty_received 1; the Showroom holds ' . ($ks0 + 1));
$a = after_of(last_log('stock.transfer_receive', $since));
ok(($a['short'] ?? null) == [['sku' => 'SMOKE-NW-CR-K', 'qty' => 2, 'qty_received' => 1]] && (int) last_log('stock.transfer_receive', $since)['location_id'] === $w['sr'], 'stock.transfer_receive logged at the destination with short [{sku, qty 2, qty_received 1}]');
$html = page($wes, '/transfers/' . $tid)['body'];
ok(str_contains($html, '1 left in transit') && str_contains($html, 'id="transfer-view-left"'), 'the screen says "1 left in transit"');
[$c, $b] = act($wes, '/transfers/receive.php', ['transfer' => $tid]);
ok($c === 422 && str_contains(msg($b), 'only one in transit is received'), 'receiving it again: "' . msg($b) . '"');
echo "3. A full receive, the refusals\n";
[, $b] = act($wes, '/transfers/save.php', ['from_location' => $w['wh'], 'to_location' => $w['sr'], 'lines' => json_encode([['variant' => 'SMOKE-NW-CR-F', 'qty' => 2], ['barcode' => '850123450042', 'qty' => 1]])]);
$t2 = (int) $b['record_id'];
ok((int) one('SELECT count(*) FROM inventory_transfer_lines WHERE transfer_id = :t', ['t' => $t2]) === 2, 'a draft with `lines` JSON (one by SKU, one by barcode)');
[$c, $b] = act($wes, '/transfers/receive.php', ['transfer' => $t2]);
ok($c === 422 && str_contains(msg($b), 'is draft — only one in transit is received'), 'receiving a draft: "' . msg($b) . '"');
$f0 = on_hand($w['full'], $w['sr']);
act($wes, '/transfers/send.php', ['transfer' => $t2]);
[$c, $b] = act($wes, '/transfers/receive.php', ['transfer' => $t2]);
ok($c === 200 && $b['left_in_transit'] === 0 && $b['short'] === [] && on_hand($w['full'], $w['sr']) === $f0 + 2, 'a full receive with no quantities: every line in full, nothing short');
[, $b] = act($wes, '/transfers/save.php', ['from_location' => $w['wh'], 'to_location' => $w['sr'], 'lines' => json_encode([['variant' => 'SMOKE-NW-CR-Q', 'qty' => 50]])]);
$t3 = (int) $b['record_id'];
[$c, $b] = act($wes, '/transfers/send.php', ['transfer' => $t3]);
ok($c === 422 && str_contains(msg($b), 'Not enough on hand'), 'sending more than on hand: the trigger\'s "' . msg($b) . '"');
ok(one('SELECT status FROM inventory_transfers WHERE id = :id', ['id' => $t3]) === 'draft' && count(txns('transfer', $t3)) === 0, 'the draft stays a draft, nothing moved');
[$c, $b] = act($wes, '/transfers/save.php', ['transfer' => $t3, 'to_location' => $w['ret'], '_partial' => '1']);
ok($c === 200 && (int) one('SELECT to_location_id FROM inventory_transfers WHERE id = :id', ['id' => $t3]) === $w['ret'] && (int) one('SELECT from_location_id FROM inventory_transfers WHERE id = :id', ['id' => $t3]) === $w['wh'], 'a draft\'s header changes (_partial keeps from)');
$line = (int) one('SELECT id FROM inventory_transfer_lines WHERE transfer_id = :t', ['t' => $t3]);
[$c, $b] = act($wes, '/transfers/lines/save.php', ['transfer' => $t3, 'line' => $line, 'qty' => '1']);
ok($c === 200 && (int) one('SELECT qty FROM inventory_transfer_lines WHERE id = :id', ['id' => $line]) === 1, 'a line\'s quantity changes by `line`');
[$c, $b] = act($wes, '/transfers/lines/remove.php', ['line' => $line]);
ok($c === 200 && last_log('stock.transfer_line_remove', $since) !== null, 'a line removed, logged');
[$c, $b] = act($wes, '/transfers/cancel.php', ['transfer' => $t3]);
ok($c === 200 && one('SELECT status FROM inventory_transfers WHERE id = :id', ['id' => $t3]) === 'cancelled' && last_log('stock.transfer_cancel', $since) !== null, 'a draft cancels, logged');
[$c, $d] = screen($wes, '/transfers/?status=in_transit');
ok($c === 200 && array_column($d['transfers'], 'transfer_id') === [], 'nothing left in transit by status (the short one is received, its difference on the document)');
ok(page(as_member(41), '/transfers/')['code'] === 403, 'Sam (no stock.transfer) cannot open the transfers');
finish();
